#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EventCombo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/DiscoverEvents.cshtml")]
    public partial class _Views_Home_DiscoverEvents_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_DiscoverEvents_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Home\DiscoverEvents.cshtml"
  
    ViewBag.Title = "DiscoverEvents";

            
            #line default
            #line hidden
WriteLiteral("\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 53), Tuple.Create("\"", 89)
, Tuple.Create(Tuple.Create("", 60), Tuple.Create<System.Object, System.Int32>(Href("~/Content/filter-dropdown.css")
, 60), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 117), Tuple.Create("\"", 147)
, Tuple.Create(Tuple.Create("", 124), Tuple.Create<System.Object, System.Int32>(Href("~/Content/jquery-ui.css")
, 124), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<div");

WriteLiteral(" id=\"dvProgress\"");

WriteLiteral(" class=\"loding_bg\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 213), Tuple.Create("\"", 243)
, Tuple.Create(Tuple.Create("", 219), Tuple.Create<System.Object, System.Int32>(Href("~/Images/ajax-loader.gif")
, 219), false)
);

WriteLiteral(" /></div>\r\n<div");

WriteLiteral(" class=\"container-fluid cont_margin no-padding con_scr0l_home\"");

WriteLiteral(" id=\"scrollhome\"");

WriteLiteral(">\r\n    \r\n    <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 ot_main_pad mb10\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-9 no_pad\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"dis_event_ser_title \"");

WriteLiteral("><h2>Events </h2></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-3 text-right no_pad\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav nav-pills dis_fil_nav_right\"");

WriteLiteral(">\r\n                <li>Sort by:</li>\r\n");

            
            #line 17 "..\..\Views\Home\DiscoverEvents.cshtml"
                
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Home\DiscoverEvents.cshtml"
                 if (@TempData["tSort"] != null && @TempData["tSort"].ToString() == "dat")
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateRelevenceFilter(\'rel\');\"");

WriteLiteral(">Relevence</a></li>\r\n");

WriteLiteral("                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateRelevenceFilter(\'dat\');\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">Date</a></li>\r\n");

            
            #line 21 "..\..\Views\Home\DiscoverEvents.cshtml"

                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateRelevenceFilter(\'rel\');\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">Relevence</a></li>\r\n");

WriteLiteral("                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateRelevenceFilter(\'dat\');\"");

WriteLiteral(">Date</a></li>\r\n");

            
            #line 27 "..\..\Views\Home\DiscoverEvents.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </ul>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"col-sm-3 col-xs-12 ot_main_pad\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-12 no_pad\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" id=\"accordion\"");

WriteLiteral(" class=\"accordion side_accordian\"");

WriteLiteral(">\r\n");

            
            #line 37 "..\..\Views\Home\DiscoverEvents.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Home\DiscoverEvents.cshtml"
                     if (@TempData["tDateFilter"].ToString() != null && @TempData["tDateFilter"].ToString() != "none")
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" class=\"open\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"link\"");

WriteLiteral(">All Dates<i");

WriteLiteral(" class=\"glyphicon  glyphicon-triangle-bottom\"");

WriteLiteral("></i></div>\r\n                        <ul");

WriteLiteral(" class=\"submenu submenu_side\"");

WriteLiteral(" style=\"display:block;\"");

WriteLiteral(">\r\n                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'today\');\"");

WriteLiteral(">Today</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'tommarow\');\"");

WriteLiteral(">Tomorrow</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'thisweek\');\"");

WriteLiteral(">This Week</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'thisweekend\');\"");

WriteLiteral(">This Weekend</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'nextweek\');\"");

WriteLiteral(">Next Week</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'thismonth\');\"");

WriteLiteral(">This Month</a></li>\r\n                            <li>\r\n                         " +
"       <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"CustDateMain\"");

WriteLiteral(">Custom Date</a>\r\n                                <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                                <div");

WriteLiteral(" class=\"CustDate col-sm-12 ot_main_pad mb10\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\" col-sm-10 no_pad mb10\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" class=\"label-control desc_date_lebel\"");

WriteLiteral(">Start Date</label>\r\n                                        <input");

WriteLiteral(" class=\"date_picker form-control\"");

WriteLiteral(" id=\"txtstartDate\"");

WriteLiteral(" placeholder=\"mm/dd/yyyy\"");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"    <div");

WriteLiteral(" class=\"col-sm-10 no_pad mb10\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" class=\"label-control desc_date_lebel\"");

WriteLiteral(">End Date</label>\r\n                                        <input");

WriteLiteral(" class=\"date_picker form-control\"");

WriteLiteral(" id=\"txtEndDate\"");

WriteLiteral(" placeholder=\"mm/dd/yyyy\"");

WriteLiteral(" />\r\n                                    </div>\r\n\r\n                              " +
"      <button");

WriteLiteral(" class=\"btn btn-lg fiter_btn_pop_sub \"");

WriteLiteral(" onclick=\"DateFiltersCustom();\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Search</button>\r\n                                </div>\r\n                       " +
"     </li>\r\n                        </ul>\r\n                    </li>\r\n");

            
            #line 66 "..\..\Views\Home\DiscoverEvents.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li>\r\n                            <div");

WriteLiteral(" class=\"link\"");

WriteLiteral(">All Dates<i");

WriteLiteral(" class=\"glyphicon  glyphicon-triangle-bottom\"");

WriteLiteral("></i></div>\r\n                            <ul");

WriteLiteral(" class=\"submenu submenu_side\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n                                <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'today\');\"");

WriteLiteral(">Today</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'tommarow\');\"");

WriteLiteral(">Tomorrow</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'thisweek\');\"");

WriteLiteral(">This Week</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'thisweekend\');\"");

WriteLiteral(">This Weekend</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'nextweek\');\"");

WriteLiteral(">Next Week</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"DateFilters(\'thismonth\');\"");

WriteLiteral(">This Month</a></li>\r\n                                <li>\r\n                     " +
"               <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"CustDateMain\"");

WriteLiteral(">Custom Date</a>\r\n                                    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                                    <div");

WriteLiteral(" class=\"CustDate col-sm-12 ot_main_pad mb10\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\" col-sm-10 no_pad mb10\"");

WriteLiteral(">\r\n                                            <label");

WriteLiteral(" class=\"label-control desc_date_lebel\"");

WriteLiteral(">Start Date</label>\r\n                                            <input");

WriteLiteral(" class=\"date_picker form-control\"");

WriteLiteral(" id=\"txtstartDate\"");

WriteLiteral(" placeholder=\"mm/dd/yyyy\"");

WriteLiteral(" />\r\n                                        </div>\r\n                            " +
"            <div");

WriteLiteral(" class=\"col-sm-10 no_pad mb10\"");

WriteLiteral(">\r\n                                            <label");

WriteLiteral(" class=\"label-control desc_date_lebel\"");

WriteLiteral(">End Date</label>\r\n                                            <input");

WriteLiteral(" class=\"date_picker form-control\"");

WriteLiteral(" id=\"txtEndDate\"");

WriteLiteral(" placeholder=\"mm/dd/yyyy\"");

WriteLiteral(" />\r\n                                        </div>\r\n\r\n                          " +
"              <button");

WriteLiteral(" class=\"btn btn-lg fiter_btn_pop_sub \"");

WriteLiteral(" onclick=\"DateFiltersCustom();\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Search</button>\r\n                                    </div>\r\n                   " +
"             </li>\r\n                            </ul>\r\n                        <" +
"/li>\r\n");

            
            #line 96 "..\..\Views\Home\DiscoverEvents.cshtml"

                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                </ul>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" id=\"dvMap\"");

WriteLiteral(" class=\"col-sm-12 no_pad mt10 map_height\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-sm-12 no_pad mt10\"");

WriteLiteral(">\r\n                <form>\r\n                    <div");

WriteLiteral(" class=\"input-group stylish-input-group\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtAddress\"");

WriteLiteral(" class=\"form-control dis_search_control\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"input-group-addon dis_search_addon\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"submit dis_search_sub\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-map-marker\"");

WriteLiteral("></i>\r\n                            </button>\r\n                        </span>\r\n  " +
"                  </div>\r\n                </form>\r\n            </div>\r\n         " +
"   <div");

WriteLiteral(" class=\"col-sm-12 no_pad\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12 no_pad\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"side_fliter_by_type\"");

WriteLiteral(">\r\n");

            
            #line 119 "..\..\Views\Home\DiscoverEvents.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 119 "..\..\Views\Home\DiscoverEvents.cshtml"
                         if (@ViewData["tempPrice"].ToString() == "FREE")
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetPriceFilter(\'ALL\');\"");

WriteLiteral(">All Prices</a></li>\r\n");

WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(" onclick=\"GetPriceFilter(\'FREE\');\"");

WriteLiteral(">Free</a></li>\r\n");

WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetPriceFilter(\'PAID\');\"");

WriteLiteral(">Paid</a></li>\r\n");

            
            #line 124 "..\..\Views\Home\DiscoverEvents.cshtml"
                        }
                        else if (@ViewData["tempPrice"].ToString() == "PAID")
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetPriceFilter(\'ALL\');\"");

WriteLiteral(">All Prices</a></li>\r\n");

WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetPriceFilter(\'FREE\');\"");

WriteLiteral(">Free</a></li>\r\n");

WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(" onclick=\"GetPriceFilter(\'PAID\');\"");

WriteLiteral(">Paid</a></li>\r\n");

            
            #line 130 "..\..\Views\Home\DiscoverEvents.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetPriceFilter(\'ALL\');\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">All Prices</a></li>\r\n");

WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetPriceFilter(\'FREE\');\"");

WriteLiteral(">Free</a></li>\r\n");

WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetPriceFilter(\'PAID\');\"");

WriteLiteral(">Paid</a></li>\r\n");

            
            #line 136 "..\..\Views\Home\DiscoverEvents.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-12 no_pad\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"side_desc_fil_head\"");

WriteLiteral(">Event Type</p>\r\n                    <ul");

WriteLiteral(" class=\"nav nav-pills dis_side_fliter_tag dis_side_fliter_scrol\"");

WriteLiteral(">\r\n");

            
            #line 142 "..\..\Views\Home\DiscoverEvents.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 142 "..\..\Views\Home\DiscoverEvents.cshtml"
                     if (ViewBag.ETSelected != null)
                    {
                        foreach (var item in (List<EventCombo.Models.EventType>)ViewBag.ETSelected)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteAttribute("onclick", Tuple.Create("  onclick=\"", 9166), Tuple.Create("\"", 9213)
, Tuple.Create(Tuple.Create("", 9177), Tuple.Create("FilterEventType(\'", 9177), true)
            
            #line 146 "..\..\Views\Home\DiscoverEvents.cshtml"
                        , Tuple.Create(Tuple.Create("", 9194), Tuple.Create<System.Object, System.Int32>(item.EventTypeID
            
            #line default
            #line hidden
, 9194), false)
, Tuple.Create(Tuple.Create("", 9211), Tuple.Create("\')", 9211), true)
);

WriteLiteral(">");

            
            #line 146 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                                                        Write(item.EventType1);

            
            #line default
            #line hidden
WriteLiteral(" </a> <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"can_badg \"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 9284), Tuple.Create("\"", 9337)
, Tuple.Create(Tuple.Create("", 9294), Tuple.Create("DeleteFilterEventType(\'", 9294), true)
            
            #line 146 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                                                                                   , Tuple.Create(Tuple.Create("", 9317), Tuple.Create<System.Object, System.Int32>(item.EventTypeID
            
            #line default
            #line hidden
, 9317), false)
, Tuple.Create(Tuple.Create("", 9334), Tuple.Create("\');", 9334), true)
);

WriteLiteral(">X</a></li>\r\n");

            
            #line 147 "..\..\Views\Home\DiscoverEvents.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetAllEventType();\"");

WriteLiteral(">ALL</a></li>\r\n");

            
            #line 149 "..\..\Views\Home\DiscoverEvents.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetAllEventType();\"");

WriteLiteral(">ALL</a></li>\r\n");

            
            #line 153 "..\..\Views\Home\DiscoverEvents.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    \r\n");

            
            #line 155 "..\..\Views\Home\DiscoverEvents.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 155 "..\..\Views\Home\DiscoverEvents.cshtml"
                     foreach (var item in (List<EventCombo.Models.EventType>)ViewBag.Eventtype)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 9889), Tuple.Create("\"", 9935)
, Tuple.Create(Tuple.Create("", 9899), Tuple.Create("FilterEventType(\'", 9899), true)
            
            #line 157 "..\..\Views\Home\DiscoverEvents.cshtml"
    , Tuple.Create(Tuple.Create("", 9916), Tuple.Create<System.Object, System.Int32>(item.EventTypeID
            
            #line default
            #line hidden
, 9916), false)
, Tuple.Create(Tuple.Create("", 9933), Tuple.Create("\')", 9933), true)
);

WriteLiteral(">");

            
            #line 157 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                                    Write(item.EventType1);

            
            #line default
            #line hidden
WriteLiteral(" </a></li>\r\n");

            
            #line 158 "..\..\Views\Home\DiscoverEvents.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-12 no_pad mt10\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"side_desc_fil_head\"");

WriteLiteral(">Category</p>\r\n                    <ul");

WriteLiteral(" class=\"nav nav-pills dis_side_fliter_tag dis_side_fliter_scrol\"");

WriteLiteral(">\r\n");

            
            #line 165 "..\..\Views\Home\DiscoverEvents.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 165 "..\..\Views\Home\DiscoverEvents.cshtml"
                         if(ViewBag.ECatSelected != null)
                        {
                            foreach (var item in (List<EventCombo.Models.EventCategory>)ViewBag.ECatSelected)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteAttribute("onclick", Tuple.Create("  onclick=\"", 10556), Tuple.Create("\"", 10611)
, Tuple.Create(Tuple.Create("", 10567), Tuple.Create("FilterEventCategory(\'", 10567), true)
            
            #line 169 "..\..\Views\Home\DiscoverEvents.cshtml"
                               , Tuple.Create(Tuple.Create("", 10588), Tuple.Create<System.Object, System.Int32>(item.EventCategoryID
            
            #line default
            #line hidden
, 10588), false)
, Tuple.Create(Tuple.Create("", 10609), Tuple.Create("\')", 10609), true)
);

WriteLiteral(">");

            
            #line 169 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                                                                    Write(item.EventCategory1);

            
            #line default
            #line hidden
WriteLiteral("</a> <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"can_badg \"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 10685), Tuple.Create("\"", 10746)
, Tuple.Create(Tuple.Create("", 10695), Tuple.Create("DeleteFilterEventCategory(\'", 10695), true)
            
            #line 169 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                                                                                                     , Tuple.Create(Tuple.Create("", 10722), Tuple.Create<System.Object, System.Int32>(item.EventCategoryID
            
            #line default
            #line hidden
, 10722), false)
, Tuple.Create(Tuple.Create("", 10743), Tuple.Create("\');", 10743), true)
);

WriteLiteral(">X</a></li>\r\n");

            
            #line 170 "..\..\Views\Home\DiscoverEvents.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetAllEventCategories();\"");

WriteLiteral(">ALL</a></li>\r\n");

            
            #line 172 "..\..\Views\Home\DiscoverEvents.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"GetAllEventCategories();\"");

WriteLiteral(">ALL</a></li>\r\n");

            
            #line 176 "..\..\Views\Home\DiscoverEvents.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        \r\n");

            
            #line 178 "..\..\Views\Home\DiscoverEvents.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 178 "..\..\Views\Home\DiscoverEvents.cshtml"
                         foreach (var item in (List<EventCombo.Models.EventCategory>)ViewBag.EventCat)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 11357), Tuple.Create("\"", 11411)
, Tuple.Create(Tuple.Create("", 11367), Tuple.Create("FilterEventCategory(\'", 11367), true)
            
            #line 180 "..\..\Views\Home\DiscoverEvents.cshtml"
           , Tuple.Create(Tuple.Create("", 11388), Tuple.Create<System.Object, System.Int32>(item.EventCategoryID
            
            #line default
            #line hidden
, 11388), false)
, Tuple.Create(Tuple.Create("", 11409), Tuple.Create("\')", 11409), true)
);

WriteLiteral(">");

            
            #line 180 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                                                Write(item.EventCategory1);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 181 "..\..\Views\Home\DiscoverEvents.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                </div>\r\n            </div>\r\n\r\n        " +
"</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-sm-9 col-xs-12 ot_main_pad\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-12 no_pad\"");

WriteLiteral(">\r\n");

            
            #line 190 "..\..\Views\Home\DiscoverEvents.cshtml"
            
            
            #line default
            #line hidden
            
            #line 190 "..\..\Views\Home\DiscoverEvents.cshtml"
             foreach (var item in (PagedList.IPagedList<EventCombo.Models.DiscoverEvent>)ViewBag.DisEvnt)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"col-md-4 col-xs-12 col-sm-6 ot_pad\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 in_shadw no_pad\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 in_pad\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-4 no_pad\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"dis_evnt_img\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create("  src=\"", 12108), Tuple.Create("\"", 12131)
            
            #line 196 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 12115), Tuple.Create<System.Object, System.Int32>(item.EventImage
            
            #line default
            #line hidden
, 12115), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral("></div>\r\n                                <div");

WriteLiteral(" class=\"col-sm-12 no_pad text-center desc_list_event_type\"");

WriteLiteral(">");

            
            #line 197 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                          Write(item.PriceLable);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-sm-8 no_pad\"");

WriteLiteral(">\r\n                                <h1");

WriteLiteral(" class=\"list_event_desc_title\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\'", 12430), Tuple.Create("\'", 12638)
            
            #line 200 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 12437), Tuple.Create<System.Object, System.Int32>(Url.Action("ViewEvent", "ViewEvent", new { strEventDs = System.Text.RegularExpressions.Regex.Replace(@item.EventTitle.Replace(" ", "-"), "[^a-zA-Z0-9_-]+", ""), strEventId = @item.EventId.ToString()})
            
            #line default
            #line hidden
, 12437), false)
);

WriteLiteral(">");

            
            #line 200 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                                                                                                                                                                                                                 Write(item.EventTitle);

            
            #line default
            #line hidden
WriteLiteral("</a></h1>\r\n                                <p");

WriteLiteral(" class=\"list_event_desc\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"des_hover\"");

WriteLiteral(">");

            
            #line 202 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                       Write(item.EventAddress);

            
            #line default
            #line hidden
WriteLiteral(" </span>\r\n                                    ");

WriteLiteral("\r\n                                </p>\r\n                                <p");

WriteLiteral(" class=\"list_event_date_time\"");

WriteLiteral(">");

            
            #line 207 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                           Write(item.EventTimings);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n                                   <div");

WriteLiteral(" class=\"desc_hide\"");

WriteLiteral(">\r\n                                    <p> ");

            
            #line 209 "..\..\Views\Home\DiscoverEvents.cshtml"
                                   Write(item.EventAddress);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n                                </div>\r\n                            </div>" +
"\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no_pad de_ev_li_border\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-10 no_pad\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"nav nav-pills list_inner_cat_tag\"");

WriteLiteral(">\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 13637), Tuple.Create("\"", 13682)
, Tuple.Create(Tuple.Create("", 13647), Tuple.Create("FilterEventType(", 13647), true)
            
            #line 216 "..\..\Views\Home\DiscoverEvents.cshtml"
              , Tuple.Create(Tuple.Create("", 13663), Tuple.Create<System.Object, System.Int32>(item.EventTypeId
            
            #line default
            #line hidden
, 13663), false)
, Tuple.Create(Tuple.Create("", 13680), Tuple.Create(");", 13680), true)
);

WriteLiteral(">#");

            
            #line 216 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                                                Write(item.EventType);

            
            #line default
            #line hidden
WriteLiteral(" </a></li>\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 13781), Tuple.Create("\"", 13829)
, Tuple.Create(Tuple.Create("", 13791), Tuple.Create("FilterEventCategory(", 13791), true)
            
            #line 217 "..\..\Views\Home\DiscoverEvents.cshtml"
                  , Tuple.Create(Tuple.Create("", 13811), Tuple.Create<System.Object, System.Int32>(item.EventCatId
            
            #line default
            #line hidden
, 13811), false)
, Tuple.Create(Tuple.Create("", 13827), Tuple.Create(");", 13827), true)
);

WriteLiteral(">#");

            
            #line 217 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                                                                   Write(item.EventCat);

            
            #line default
            #line hidden
WriteLiteral(" </a></li>\r\n                                </ul>\r\n                            </" +
"div>\r\n                            <div");

WriteLiteral(" class=\"col-sm-2 no_pad text-right\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" class=\"desc_btn_bg_none \"");

WriteLiteral(" title=\"Your Favourite\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-share-alt\"");

WriteLiteral("></i>\r\n                                </button>\r\n                               " +
" <button");

WriteLiteral(" class=\"desc_btn_bg_none desc_btn_bg_active\"");

WriteLiteral(" title=\"Your Favourite\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-heart\"");

WriteLiteral("></i>\r\n                                </button>\r\n                            </d" +
"iv>\r\n                        </div>\r\n                    </div>\r\n               " +
" </div>\r\n");

            
            #line 231 "..\..\Views\Home\DiscoverEvents.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n        <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 text-center\"");

WriteLiteral(">\r\n            <nav>\r\n                <ul");

WriteLiteral(" class=\"pagination desc_pagination\"");

WriteLiteral(">\r\n                    <li>\r\n                        <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">\r\n                            <span><i");

WriteLiteral(" class=\"fa fa-angle-left\"");

WriteLiteral("></i> </span>\r\n                        </a>\r\n                    </li>\r\n");

            
            #line 242 "..\..\Views\Home\DiscoverEvents.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 242 "..\..\Views\Home\DiscoverEvents.cshtml"
                     for(int i=1;i<= Convert.ToInt32(@TempData["TotalPages"]);i++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 15104), Tuple.Create("\"", 15127)
, Tuple.Create(Tuple.Create("", 15114), Tuple.Create("NextPage(", 15114), true)
            
            #line 244 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 15123), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 15123), false)
, Tuple.Create(Tuple.Create("", 15125), Tuple.Create(");", 15125), true)
);

WriteLiteral(">");

            
            #line 244 "..\..\Views\Home\DiscoverEvents.cshtml"
                                                                            Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 245 "..\..\Views\Home\DiscoverEvents.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    <li>\r\n                        <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">\r\n                            <span><i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral("></i> </span>\r\n                        </a>\r\n                    </li>\r\n         " +
"       </ul>\r\n            </nav>\r\n            <div");

WriteLiteral(" class=\"col-sm-12 pagination_desc\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hdEventType\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16061), Tuple.Create("\"", 16095)
            
            #line 265 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 16069), Tuple.Create<System.Object, System.Int32>(TempData["ETypeSelected"]
            
            #line default
            #line hidden
, 16069), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hdEventCat\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16141), Tuple.Create("\"", 16174)
            
            #line 266 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 16149), Tuple.Create<System.Object, System.Int32>(TempData["ECatSelected"]
            
            #line default
            #line hidden
, 16149), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hdPrice\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16217), Tuple.Create("\"", 16247)
            
            #line 267 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 16225), Tuple.Create<System.Object, System.Int32>(ViewData["tempPrice"]
            
            #line default
            #line hidden
, 16225), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hdlat\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16288), Tuple.Create("\"", 16313)
            
            #line 268 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 16296), Tuple.Create<System.Object, System.Int32>(TempData["tLat"]
            
            #line default
            #line hidden
, 16296), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hdlng\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16354), Tuple.Create("\"", 16379)
            
            #line 269 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 16362), Tuple.Create<System.Object, System.Int32>(TempData["tLng"]
            
            #line default
            #line hidden
, 16362), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hdSort\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16421), Tuple.Create("\"", 16447)
            
            #line 270 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 16429), Tuple.Create<System.Object, System.Int32>(TempData["tSort"]
            
            #line default
            #line hidden
, 16429), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hdDateFilter\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16495), Tuple.Create("\"", 16527)
            
            #line 271 "..\..\Views\Home\DiscoverEvents.cshtml"
, Tuple.Create(Tuple.Create("", 16503), Tuple.Create<System.Object, System.Int32>(TempData["tDateFilter"]
            
            #line default
            #line hidden
, 16503), false)
);

WriteLiteral(" />\r\n\r\n</div>\r\n\r\n\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 16556), Tuple.Create("\"", 16595)
, Tuple.Create(Tuple.Create("", 16562), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/bootstrap-datepicker.js")
, 16562), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 16615), Tuple.Create("\"", 16643)
, Tuple.Create(Tuple.Create("", 16621), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-ui.js")
, 16621), false)
);

WriteLiteral("></script>\r\n\r\n<script");

WriteLiteral(" src=\"https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=plac" +
"es\"");

WriteLiteral(@"></script>
<script>

    function DateFilters(vvalue) {
        $(""#hdDateFilter"").val(vvalue);
        NextPage(1);
    }

    function DateFiltersCustom() {
        //vvalue = ""custom-"" + $(""#txtstartDate"").val() + ""-"" + $(""#txtEndDate"").val();
        vvalue = """";
        $(""#hdDateFilter"").val(vvalue);
        NextPage(1);
    }

    function DateRelevenceFilter(vvalue)
    {
        $(""#hdSort"").val(vvalue);
        NextPage(1);
    }

    function NextPage(vIndex)
    {
        var vUrl = '");

            
            #line 303 "..\..\Views\Home\DiscoverEvents.cshtml"
               Write(Url.RouteUrl("EvType", new { strEt = "evt", strEc = "evc", strPrice="all", strPageIndex="Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral(@"';

        var vECat = ($(""#hdEventCat"").val() != '' ? $(""#hdEventCat"").val() : ""evc"");
        var vEtype = ($(""#hdEventType"").val() != '' ? $(""#hdEventType"").val() : ""evt"");
        var vPrice = ($(""#hdPrice"").val() != '' ? $(""#hdPrice"").val() : ""ALL"");
        var vLat = ($(""#hdlat"").val() != '' ? $(""#hdlat"").val() : ""lat"");
        var vlng = ($(""#hdlng"").val() != '' ? $(""#hdlng"").val() : ""long"");
        var vSort = ($(""#hdSort"").val() != '' ? $(""#hdSort"").val() : ""rel"");
        var vDateFilter = ($(""#hdDateFilter"").val() != '' ? $(""#hdDateFilter"").val() : ""none"");

        
        vUrl = vUrl.replace(""all"", vPrice);
        vUrl = vUrl.replace(""evc"", vECat);
        vUrl = vUrl.replace(""evt"", vEtype);
        vUrl = vUrl.replace(""lat"", vLat);
        vUrl = vUrl.replace(""long"", vlng);
        vUrl = vUrl.replace(""rel"", vSort);
        vUrl = vUrl.replace(""none"", vDateFilter);

        window.location.href = vUrl;
    }
    function GetPriceFilter(strPrice) {
        var vUrl = '");

            
            #line 325 "..\..\Views\Home\DiscoverEvents.cshtml"
               Write(Url.RouteUrl("EvType", new { strEt = "evt", strEc = "evc", strPrice="all", strPageIndex = "Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral(@"';
        var vECat = ($(""#hdEventCat"").val() != '' ? $(""#hdEventCat"").val() : ""evc"");
        var Price = (strPrice != '' ? strPrice : ""ALL"");
        var vEtype = ($(""#hdEventType"").val() != '' ? $(""#hdEventType"").val() : ""evt"");
        var vLat = ($(""#hdlat"").val() != '' ? $(""#hdlat"").val() : ""lat"");
        var vlng = ($(""#hdlng"").val() != '' ? $(""#hdlng"").val() : ""long"");
        var vSort = ($(""#hdSort"").val() != '' ? $(""#hdSort"").val() : ""rel"");
        var vDateFilter = ($(""#hdDateFilter"").val() != '' ? $(""#hdDateFilter"").val() : ""none"");

        vUrl = vUrl.replace(""all"", Price);
        vUrl = vUrl.replace(""evc"", vECat);
        vUrl = vUrl.replace(""evt"", vEtype);
        vUrl = vUrl.replace(""lat"", vLat);
        vUrl = vUrl.replace(""long"", vlng);
        vUrl = vUrl.replace(""rel"", vSort);
        vUrl = vUrl.replace(""none"", vDateFilter);
        window.location.href = vUrl;
    }

    function GetAllEventType() {
        var vUrl = '");

            
            #line 345 "..\..\Views\Home\DiscoverEvents.cshtml"
               Write(Url.RouteUrl("EvType", new { strEt = "evt", strEc = "evc", strPrice="all", strPageIndex = "Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral(@"';
        var vECat = ($(""#hdEventCat"").val() != '' ? $(""#hdEventCat"").val() : ""evc"");
        var Price = ($(""#hdPrice"").val() != '' ? $(""#hdPrice"").val() : ""ALL"");
        var vLat = ($(""#hdlat"").val() != '' ? $(""#hdlat"").val() : ""lat"");
        var vlng = ($(""#hdlng"").val() != '' ? $(""#hdlng"").val() : ""long"");
        var vSort = ($(""#hdSort"").val() != '' ? $(""#hdSort"").val() : ""rel"");
        var vDateFilter = ($(""#hdDateFilter"").val() != '' ? $(""#hdDateFilter"").val() : ""none"");

        vUrl = vUrl.replace(""all"", Price);
        vUrl = vUrl.replace(""evc"", vECat);
        vUrl = vUrl.replace(""lat"", vLat);
        vUrl = vUrl.replace(""long"", vlng);
        vUrl = vUrl.replace(""rel"", vSort);
        vUrl = vUrl.replace(""none"", vDateFilter);
        window.location.href = vUrl;
    }
    function GetAllEventCategories() {
         var vUrl = '");

            
            #line 362 "..\..\Views\Home\DiscoverEvents.cshtml"
                Write(Url.RouteUrl("EvType", new { strEt = "evt", strEc = "evc", strPrice = "all", strPageIndex = "Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral(@"';
        var vEtype = ($(""#hdEventType"").val() != '' ? $(""#hdEventType"").val() : ""evt"");
        var Price = ($(""#hdPrice"").val() != '' ? $(""#hdPrice"").val() : ""ALL"");
        var vLat = ($(""#hdlat"").val() != '' ? $(""#hdlat"").val() : ""lat"");
        var vlng = ($(""#hdlng"").val() != '' ? $(""#hdlng"").val() : ""long"");
        var vSort = ($(""#hdSort"").val() != '' ? $(""#hdSort"").val() : ""rel"");
        var vDateFilter = ($(""#hdDateFilter"").val() != '' ? $(""#hdDateFilter"").val() : ""none"");

        vUrl = vUrl.replace(""all"", Price);
        vUrl = vUrl.replace(""evt"", vEtype);
        vUrl = vUrl.replace(""lat"", vLat);
        vUrl = vUrl.replace(""long"", vlng);
        vUrl = vUrl.replace(""rel"", vSort);
        vUrl = vUrl.replace(""none"", vDateFilter);
        window.location.href = vUrl;
    }
    function DeleteFilterEventType(vEvTypeId)
    {
        var vValue="""";
        var vAry = $(""#hdEventType"").val().split(',');
        for (i = 0; i < vAry.length; i++)
        {
            if (vAry[i] != vEvTypeId)
            {
                if (vValue == """")
                    vValue = vAry[i];
                else
                    vValue = vValue + "","" + vAry[i];
            }
        }
        var vUrl = '");

            
            #line 392 "..\..\Views\Home\DiscoverEvents.cshtml"
               Write(Url.RouteUrl("EvType", new { strEt = "evt", strEc = "evc", strPrice = "all", strPageIndex = "Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral(@"';
        var vECat = ($(""#hdEventCat"").val() != '' ? $(""#hdEventCat"").val() : ""evc"");
        var Price = ($(""#hdPrice"").val() != '' ? $(""#hdPrice"").val() : ""ALL"");
        var vLat = ($(""#hdlat"").val() != '' ? $(""#hdlat"").val() : ""lat"");
        var vlng = ($(""#hdlng"").val() != '' ? $(""#hdlng"").val() : ""long"");
        var vSort = ($(""#hdSort"").val() != '' ? $(""#hdSort"").val() : ""rel"");
        var vDateFilter = ($(""#hdDateFilter"").val() != '' ? $(""#hdDateFilter"").val() : ""none"");

        vUrl = vUrl.replace(""evt"", (vValue == """" ? ""evt"" : vValue));
        vUrl = vUrl.replace(""evc"", vECat);
        vUrl = vUrl.replace(""all"", Price);
        vUrl = vUrl.replace(""lat"", vLat);
        vUrl = vUrl.replace(""long"", vlng);
        vUrl = vUrl.replace(""rel"", vSort);
        vUrl = vUrl.replace(""none"", vDateFilter);
        window.location.href = vUrl;

    }
    function DeleteFilterEventCategory(vEvCatId) {
        var vValue = """";
        var vAry = $(""#hdEventCat"").val().split(',');
        for (i = 0; i < vAry.length; i++) {
            if (vAry[i] != vEvCatId) {
                if (vValue == """")
                    vValue = vAry[i];
                else
                    vValue = vValue + "","" + vAry[i];
            }
        }
        var vUrl = '");

            
            #line 421 "..\..\Views\Home\DiscoverEvents.cshtml"
               Write(Url.RouteUrl("EvType", new { strEt = "evt", strEc = "evc", strPrice = "all", strPageIndex = "Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral(@"';
        var vEtype = ($(""#hdEventType"").val() != '' ? $(""#hdEventType"").val() : ""evt"");
        vUrl = vUrl.replace(""evc"", (vValue == """" ? ""evc"" : vValue));
        vUrl = vUrl.replace(""evt"", vEtype);
        var Price = ($(""#hdPrice"").val() != '' ? $(""#hdPrice"").val() : ""ALL"");
        var vLat = ($(""#hdlat"").val() != '' ? $(""#hdlat"").val() : ""lat"");
        var vlng = ($(""#hdlng"").val() != '' ? $(""#hdlng"").val() : ""long"");
        var vSort = ($(""#hdSort"").val() != '' ? $(""#hdSort"").val() : ""rel"");
        var vDateFilter = ($(""#hdDateFilter"").val() != '' ? $(""#hdDateFilter"").val() : ""none"");

        vUrl = vUrl.replace(""all"", Price);
        vUrl = vUrl.replace(""lat"", vLat);
        vUrl = vUrl.replace(""long"", vlng);
        vUrl = vUrl.replace(""rel"", vSort);
        vUrl = vUrl.replace(""none"", vDateFilter);
        window.location.href = vUrl;

    }
    function FilterEventType(vEvTypeId) {
        if ($(""#hdEventType"").val() == """" || $(""#hdEventType"").val() == ""~"" || $(""#hdEventType"").val() == ""evt"") {
            $(""#hdEventType"").val(vEvTypeId);
        }
        else {
            vIds = $(""#hdEventType"").val();
            // alert(vIds.indexOf(vEvTypeId));
            if (vIds.indexOf(vEvTypeId) < 0) {
                vIds = vIds.concat("","", vEvTypeId);
                $(""#hdEventType"").val(vIds);
            }
        }
        var vUrl = '");

            
            #line 451 "..\..\Views\Home\DiscoverEvents.cshtml"
               Write(Url.RouteUrl("EvType",new { strEt = "evt", strEc = "evc", strPrice = "all", strPageIndex = "Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral(@"';
        var vECat = ($(""#hdEventCat"").val() != '' ? $(""#hdEventCat"").val() : ""evc"");
        vUrl = vUrl.replace(""evt"", $(""#hdEventType"").val());
        vUrl = vUrl.replace(""evc"", vECat);
        var Price = ($(""#hdPrice"").val() != '' ? $(""#hdPrice"").val() : ""all"");
        var vLat = ($(""#hdlat"").val() != '' ? $(""#hdlat"").val() : ""lat"");
        var vlng = ($(""#hdlng"").val() != '' ? $(""#hdlng"").val() : ""long"");
        var vSort = ($(""#hdSort"").val() != '' ? $(""#hdSort"").val() : ""rel"");
        var vDateFilter = ($(""#hdDateFilter"").val() != '' ? $(""#hdDateFilter"").val() : ""none"");

        vUrl = vUrl.replace(""lat"", vLat);
        vUrl = vUrl.replace(""long"", vlng);
        vUrl = vUrl.replace(""all"", Price);
        vUrl = vUrl.replace(""rel"", vSort);
        vUrl = vUrl.replace(""none"", vDateFilter);
        window.location.href = vUrl;
        // alert($(""#hdEventType"").val());

    }
    function FilterEventCategory(vEvCatId) {
        if ($(""#hdEventCat"").val() == """" || $(""#hdEventCat"").val() == ""~"" || $(""#hdEventCat"").val() == ""evc"") {
            $(""#hdEventCat"").val(vEvCatId);
        }
        else {
            vIds = $(""#hdEventCat"").val();
            if (vIds.indexOf(vEvCatId) < 0) {
                vIds = vIds.concat("","", vEvCatId);
                $(""#hdEventCat"").val(vIds);
            }
        }

        var vUrl = '");

            
            #line 482 "..\..\Views\Home\DiscoverEvents.cshtml"
               Write(Url.RouteUrl("EvType",new { strEt = "evt", strEc = "evc", strPrice = "all", strPageIndex = "Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral(@"';
        var vEType = ($(""#hdEventType"").val() != '' ? $(""#hdEventType"").val() : ""evt"");
        vUrl = vUrl.replace(""evt"", vEType);
        vUrl = vUrl.replace(""evc"", $(""#hdEventCat"").val());
        var Price = ($(""#hdPrice"").val() != '' ? $(""#hdPrice"").val() : ""all"");
        var vLat = ($(""#hdlat"").val() != '' ? $(""#hdlat"").val() : ""lat"");
        var vlng = ($(""#hdlng"").val() != '' ? $(""#hdlng"").val() : ""long"");
        var vSort = ($(""#hdSort"").val() != '' ? $(""#hdSort"").val() : ""rel"");
        var vDateFilter = ($(""#hdDateFilter"").val() != '' ? $(""#hdDateFilter"").val() : ""none"");

        vUrl = vUrl.replace(""all"", Price);
        vUrl = vUrl.replace(""lat"", vLat);
        vUrl = vUrl.replace(""long"", vlng);
        vUrl = vUrl.replace(""rel"", vSort);
        vUrl = vUrl.replace(""none"", vDateFilter);
        window.location.href = vUrl;

        // alert($(""#hdEventType"").val());

    }

    function FilterbySingleEventCategory(vEvCatId) {
        var vUrl = '");

            
            #line 504 "..\..\Views\Home\DiscoverEvents.cshtml"
               Write(Url.RouteUrl("EvType",new { strEt = "evt", strEc = "evc", strPrice = "all", strPageIndex = "Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral(@"';
        //vUrl = vUrl.replace(""evt"", ""~"");
        vUrl = vUrl.replace(""evc"", vEvCatId);
        var Price = ($(""#hdPrice"").val() != '' ? $(""#hdPrice"").val() : ""ALL"");
        var vLat = ($(""#hdlat"").val() != '' ? $(""#hdlat"").val() : ""lat"");
        var vlng = ($(""#hdlng"").val() != '' ? $(""#hdlng"").val() : ""long"");
        var vSort = ($(""#hdSort"").val() != '' ? $(""#hdSort"").val() : ""rel"");
        var vDateFilter = ($(""#hdDateFilter"").val() != '' ? $(""#hdDateFilter"").val() : ""none"");

        vUrl = vUrl.replace(""all"", Price);
        vUrl = vUrl.replace(""lat"", vLat);
        vUrl = vUrl.replace(""long"", vlng);
        vUrl = vUrl.replace(""rel"", vSort);
        vUrl = vUrl.replace(""none"", vDateFilter);
        window.location.href = vUrl;
    }


    function FilterbySingleEventType(vEvTypeId) {
        var vUrl = '");

            
            #line 523 "..\..\Views\Home\DiscoverEvents.cshtml"
               Write(Url.RouteUrl("EvType",new { strEt = "evt", strEc = "", strPrice = "all", strPageIndex = "Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        vUrl = vUrl.replace(\"evt\", vEvTypeId);\r\n        var Price = ($(\"#hdPr" +
"ice\").val() != \'\' ? $(\"#hdPrice\").val() : \"ALL\");\r\n        var vLat = ($(\"#hdlat" +
"\").val() != \'\' ? $(\"#hdlat\").val() : \"lat\");\r\n        var vlng = ($(\"#hdlng\").va" +
"l() != \'\' ? $(\"#hdlng\").val() : \"long\");\r\n        var vSort = ($(\"#hdSort\").val(" +
") != \'\' ? $(\"#hdSort\").val() : \"rel\");\r\n        var vDateFilter = ($(\"#hdDateFil" +
"ter\").val() != \'\' ? $(\"#hdDateFilter\").val() : \"none\");\r\n\r\n        vUrl = vUrl.r" +
"eplace(\"all\", Price);\r\n        vUrl = vUrl.replace(\"lat\", vLat);\r\n        vUrl =" +
" vUrl.replace(\"long\", vlng);\r\n        vUrl = vUrl.replace(\"rel\", vSort);\r\n      " +
"  vUrl = vUrl.replace(\"none\", vDateFilter);\r\n        //vUrl = vUrl.replace(\"evc\"" +
", \"\");\r\n        window.location.href = vUrl;\r\n    }\r\n\r\n\r\n\r\n    $(document).ready" +
"(function () {\r\n        var input = document.getElementById(\'txtAddress\');\r\n    " +
"    var autocomplete = new google.maps.places.Autocomplete(input);\r\n\r\n        go" +
"ogle.maps.event.addListener(autocomplete, \'place_changed\', function () {\r\n      " +
"      var mapOptions = {\r\n                center: new google.maps.LatLng(6.9167," +
" 79.8473),\r\n                zoom: 10,\r\n                mapTypeId: google.maps.Ma" +
"pTypeId.ROADMAP\r\n            };\r\n            var map = new google.maps.Map(docum" +
"ent.getElementById(\"dvMap\"),\r\n              mapOptions);\r\n            // create " +
"a marker\r\n            var latlng = new google.maps.LatLng(6.9167, 79.8473);\r\n\r\n " +
"           var marker = new google.maps.Marker({\r\n                position: latl" +
"ng,\r\n                map: map,\r\n                title: \'My Place\'\r\n\r\n           " +
" });\r\n\r\n            var place = autocomplete.getPlace();\r\n            var vUrl =" +
" \'");

            
            #line 565 "..\..\Views\Home\DiscoverEvents.cshtml"
                   Write(Url.RouteUrl("EvType", new { strEt = "evt", strEc = "evc", strPrice="all", strPageIndex="Page", strLat = "lat", strLong = "long", strSort = "rel", strDateFilter = "none" }));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            var vLat = place.geometry.location.lat();\r\n            var vLong " +
"= place.geometry.location.lng();\r\n            vUrl = vUrl.replace(\"lat\", vLat);\r" +
"\n            vUrl = vUrl.replace(\"long\", vLong);\r\n     \r\n            window.loca" +
"tion.href = vUrl;\r\n\r\n            if (place.geometry.viewport) {\r\n               " +
" map.fitBounds(place.geometry.viewport);\r\n            }\r\n            else {\r\n   " +
"             map.setCenter(place.geometry.location);\r\n                map.setZoo" +
"m(17);\r\n\r\n            }\r\n            marker.setIcon(({\r\n                url: pla" +
"ce.icon,\r\n                size: new google.maps.Size(71, 71),\r\n                o" +
"rigin: new google.maps.Point(0, 0),\r\n                anchor: new google.maps.Poi" +
"nt(17, 34),\r\n                scaledSize: new google.maps.Size(35, 35)\r\n         " +
"   }));\r\n            marker.setPosition(place.geometry.location);\r\n            m" +
"arker.setVisible(true);\r\n\r\n\r\n\r\n            var address = \'\';\r\n            if (pl" +
"ace.address_components) {\r\n                address = [\r\n                  (place" +
".address_components[0] && place.address_components[0].short_name || \'\'),\r\n      " +
"            (place.address_components[1] && place.address_components[1].short_na" +
"me || \'\'),\r\n                  (place.address_components[2] && place.address_comp" +
"onents[2].short_name || \'\')\r\n                ].join(\' \');\r\n            }\r\n\r\n    " +
"    });\r\n\r\n        if ($(\"#hdlat\").val() == \"\" && $(\"#hdlng\").val() == \"\") {\r\n  " +
"          if (navigator.geolocation) {\r\n                navigator.geolocation.ge" +
"tCurrentPosition(function (p) {\r\n                    var LatLng = new google.map" +
"s.LatLng(p.coords.latitude, p.coords.longitude);\r\n                    var geocod" +
"er = new google.maps.Geocoder;\r\n                    var infowindow = new google." +
"maps.InfoWindow;\r\n                    var mapOptions = {\r\n                      " +
"  center: { lat: p.coords.latitude, lng: p.coords.longitude },\r\n                " +
"        zoom: 13,\r\n                        mapTypeId: google.maps.MapTypeId.ROAD" +
"MAP\r\n                    };\r\n                    var map = new google.maps.Map(d" +
"ocument.getElementById(\"dvMap\"), mapOptions);\r\n                    var marker = " +
"new google.maps.Marker({\r\n                        position: LatLng,\r\n           " +
"             map: map\r\n                    });\r\n                    google.maps." +
"event.addListener(marker, \"click\", function (e) {\r\n                        geoco" +
"deLatLng(geocoder, map, infowindow);\r\n                        var infoWindow = n" +
"ew google.maps.InfoWindow();\r\n                        infoWindow.setContent(mark" +
"er.title);\r\n                        infoWindow.open(map, marker);\r\n             " +
"       });\r\n\r\n                });\r\n\r\n            } else {\r\n                alert" +
"(\'Geo Location feature is not supported in this browser.\');\r\n            }\r\n    " +
"    }\r\n        else\r\n        {\r\n            var LatLng = new google.maps.LatLng(" +
"$(\"#hdlat\").val(), $(\"#hdlng\").val());\r\n            var geocoder = new google.ma" +
"ps.Geocoder;\r\n            var infowindow = new google.maps.InfoWindow;\r\n        " +
"    var mapOptions = {\r\n                center: LatLng,\r\n                zoom: 1" +
"3,\r\n                mapTypeId: google.maps.MapTypeId.ROADMAP\r\n            };\r\n  " +
"          var map = new google.maps.Map(document.getElementById(\"dvMap\"), mapOpt" +
"ions);\r\n            var marker = new google.maps.Marker({\r\n                posit" +
"ion: LatLng,\r\n                map: map\r\n            });\r\n            google.maps" +
".event.addListener(marker, \"click\", function (e) {\r\n                geocodeLatLn" +
"g(geocoder, map, infowindow);\r\n                var infoWindow = new google.maps." +
"InfoWindow();\r\n                infoWindow.setContent(marker.title);\r\n           " +
"     infoWindow.open(map, marker);\r\n            });\r\n\r\n            var locationu" +
"rl = \'http://maps.googleapis.com/maps/api/geocode/json?latlng=\' + $(\"#hdlat\").va" +
"l() + \',\' + $(\"#hdlng\").val() + \'&sensor=true\';\r\n            $.ajax({\r\n         " +
"       url: locationurl,\r\n                type: \"Post\",\r\n                success" +
": function (response) {\r\n                    debugger;\r\n                    docu" +
"ment.getElementById(\'txtAddress\').value = response.results[0].formatted_address;" +
"\r\n                }\r\n            });\r\n        }\r\n        //title: \"<div style = " +
"\'height:60px;width:200px\'><b>Your location:</b><br />Latitude: \" + p.coords.lati" +
"tude + \"<br />Longitude: \" + p.coords.longitude\r\n\r\n\r\n        //function initMap(" +
") {\r\n        //    var map = new google.maps.Map(document.getElementById(\'dvMap\'" +
"), {\r\n        //        zoom: 8,\r\n        //        center: { lat: 40.731, lng: " +
"-73.997 }\r\n        //    });\r\n        //    var geocoder = new google.maps.Geoco" +
"der;\r\n        //    var infowindow = new google.maps.InfoWindow;\r\n\r\n        //  " +
"  document.getElementById(\'submit\').addEventListener(\'click\', function () {\r\n   " +
"     //        geocodeLatLng(geocoder, map, infowindow);\r\n        //    });\r\n   " +
"     //}\r\n\r\n        function geocodeLatLng(geocoder, map, infowindow) {\r\n       " +
"     var input = document.getElementById(\'txtAddress\').value;\r\n            var l" +
"atlngStr = input.split(\',\', 2);\r\n            var latlng = { lat: parseFloat(latl" +
"ngStr[0]), lng: parseFloat(latlngStr[1]) };\r\n            geocoder.geocode({ \'loc" +
"ation\': latlng }, function (results, status) {\r\n                if (status === g" +
"oogle.maps.GeocoderStatus.OK) {\r\n                    if (results[1]) {\r\n        " +
"                map.setZoom(11);\r\n                        var marker = new googl" +
"e.maps.Marker({\r\n                            position: latlng,\r\n                " +
"            map: map\r\n                        });\r\n                        infow" +
"indow.setContent(results[1].formatted_address);\r\n                        infowin" +
"dow.open(map, marker);\r\n                    } else {\r\n                        wi" +
"ndow.alert(\'No results found\');\r\n                    }\r\n                } else {" +
"\r\n                    window.alert(\'Geocoder failed due to: \' + status);\r\n      " +
"          }\r\n            });\r\n        }\r\n\r\n\r\n\r\n\r\n\r\n        //var geocoder = new " +
"google.maps.Geocoder();\r\n        //geocoder.geocode({\r\n        //    \"address\": " +
"firstResult\r\n        //}, function (results, status) {\r\n        //    if (status" +
" == google.maps.GeocoderStatus.OK) {\r\n        //        var lat = results[0].geo" +
"metry.location.lat(),\r\n        //            lng = results[0].geometry.location." +
"lng(),\r\n        //            placeName = results[0].address_components[0].long_" +
"name,\r\n        //            latlng = new google.maps.LatLng(lat, lng);\r\n\r\n     " +
"   //        moveMarker(placeName, latlng);\r\n        //        $(\"txtAddress\").v" +
"al(firstResult);\r\n        //        alert(firstResult)\r\n        //    }\r\n       " +
" //});\r\n\r\n\r\n\r\n\r\n\r\n\r\n        $(\"#dvProgress\").hide();\r\n\r\n\r\n\r\n\r\n\r\n\r\n        $(\'.da" +
"te_picker\').datepicker({\r\n            format: \"mm/dd/yyyy\",\r\n        })\r\n       " +
"   .on(\'changeDate\', function (ev) {\r\n              $(\'.date_picker\').datepicker" +
"(\'hide\');\r\n          });\r\n\r\n        $(\".desc_hide\").css({ \"display\": \"none\" });\r" +
"\n        $(\".des_hover\").mouseover(function (e) {\r\n            var $target = $(e" +
".currentTarget);\r\n            $target.css({ \"display\": \"none\" });\r\n            $" +
"target.closest(\"div\").find(\".desc_hide\").css({ \"display\": \"block\" });\r\n        }" +
");\r\n        $(\".desc_hide\").mouseout(function (e) {\r\n            var $target = $" +
"(e.currentTarget);\r\n            $target.css({ \"display\": \"none\" });\r\n           " +
" $target.parent(\"div\").find(\".des_hover\").css({ \"display\": \"block\" });\r\n        " +
"});\r\n\r\n        $(\".CustDate\").css({ \"display\": \"none\" });\r\n        $(\".CustDateM" +
"ain\").click(function () {\r\n            $(\'.CustDate\').slideToggle(function () {\r" +
"\n                $(\'.CustDateMain\').toggleClass(\'active\');\r\n            });\r\n\r\n " +
"       });\r\n\r\n    });\r\n\r\n\r\n    $(function () {\r\n\r\n        var Accordion = functi" +
"on (el, multiple) {\r\n            this.el = el || {};\r\n            this.multiple " +
"= multiple || false;\r\n\r\n            // Variables privadas\r\n            var links" +
" = this.el.find(\'.link\');\r\n            // Evento\r\n            links.on(\'click\', " +
"{ el: this.el, multiple: this.multiple }, this.dropdown)\r\n        }\r\n\r\n        A" +
"ccordion.prototype.dropdown = function (e) {\r\n            var $el = e.data.el;\r\n" +
"            $this = $(this),\r\n            $next = $this.next();\r\n\r\n            $" +
"next.slideToggle();\r\n            $this.parent().toggleClass(\'open\');\r\n\r\n        " +
"    if (!e.data.multiple) {\r\n                $el.find(\'.submenu\').not($next).sli" +
"deUp().parent().removeClass(\'open\');\r\n            };\r\n        }\r\n\r\n        var a" +
"ccordion = new Accordion($(\'#accordion\'), false);\r\n    });\r\n</script>\r\n\r\n\r\n\r\n\r\n\r" +
"\n");

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
