#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EventCombo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Eventcombo - Find and Enjoy Cool Events, Create Your Own, Sell Tickets For Free";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"container-fluid cont_margin no-padding con_scr0l_home\"");

WriteLiteral(" id=\"scrollhome\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-9 col-sm-12 no-padding clearfix\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-4 col-xs-12 col-sm-6 wid_1024 \"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"event_list_main\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"event_list_left\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"evnt_img\"");

WriteAttribute("src", Tuple.Create(" src=\"", 450), Tuple.Create("\"", 475)
, Tuple.Create(Tuple.Create("", 456), Tuple.Create<System.Object, System.Int32>(Href("~/Images/event1.jpg")
, 456), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                   \r\n                </div>\r\n                <div");

WriteLiteral(" class=\"event_list_right\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    <select");

WriteLiteral(" id=\"dllEventList\"");

WriteLiteral(">\r\n\r\n\r\n                    </select>\r\n                    <p");

WriteLiteral(" class=\"event_desc\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                    </p>\r\n                    ");

WriteLiteral("\r\n\r\n                    ");

WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        ");

WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-3 col-sm-12 clearfix\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"the_buz \"");

WriteLiteral("><h2>What\'s the BUZZ?</h2></div>\r\n            <div");

WriteLiteral(" class=\"event_list_main buzz_right_main \"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"event_list_right buzz_right\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"event_tit buz_title\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">To Tattoo or Not... 5 of the Hottest Tat Types for Summer</a></p>\r\n             " +
"       <p");

WriteLiteral(" class=\"event_desc buz_desc\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(@">
                            Sun National Bank Arena
                            81 Hamilton Avenue
                            Trenton, NJ , 08611
                            New York, New York
                        </a>
                    </p>
                </div>
                <div");

WriteLiteral(" class=\"event_list_left\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"evnt_img_right\"");

WriteAttribute("src", Tuple.Create(" src=\"", 5234), Tuple.Create("\"", 5259)
, Tuple.Create(Tuple.Create("", 5240), Tuple.Create<System.Object, System.Int32>(Href("~/Images/event1.jpg")
, 5240), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"event_list_main buzz_right_main\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"event_list_right buzz_right\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"event_tit buz_title\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">To Tattoo or Not... 5 of the Hottest Tat Types for Summer</a></p>\r\n             " +
"       <p");

WriteLiteral(" class=\"event_desc buz_desc\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(@">
                            Sun National Bank Arena
                            81 Hamilton Avenue
                            Trenton, NJ , 08611
                            New York, New York
                        </a>
                    </p>
                </div>
                <div");

WriteLiteral(" class=\"event_list_left\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"evnt_img_right\"");

WriteAttribute("src", Tuple.Create(" src=\"", 6025), Tuple.Create("\"", 6050)
, Tuple.Create(Tuple.Create("", 6031), Tuple.Create<System.Object, System.Int32>(Href("~/Images/event1.jpg")
, 6031), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(@">
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).prop('title', 'Eventcombo - Find and Enjoy Cool Events, Create Your Own, Sell Tickets For Free');
    $(document).ready(function () {
        $.ajax({
            url: '");

            
            #line 126 "..\..\Views\Home\Index.cshtml"
             Write(Url.Action("GetEventURL", "CreateEvent"));

            
            #line default
            #line hidden
WriteLiteral(@"',
            type: ""Post"",
            success: function (data) {
                if (data != """")
                    $(""#dllEventList"").html(data);
           },
        });
        $(""#dllEventList"").change(function () {
            window.location.href = $(""#dllEventList"").val();
        });
        $(""#btTest"").click(function () {
           // alert(""button click"");
            window.location.href = '");

            
            #line 138 "..\..\Views\Home\Index.cshtml"
                               Write(Url.Action("ViewEvent", "ViewEvent", new { strEventDs = "a", strEventId = "74" }));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\r\n        });\r\n    });\r\n  \r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
