#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EventCombo;
    
    #line 1 "..\..\Views\Shared\_AccountLayout.cshtml"
    using EventCombo.ViewModels;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_AccountLayout.cshtml")]
    public partial class _Views_Shared__AccountLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__AccountLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n    <!-- The above 3 meta tags *must* come first in the head; any other head c" +
"ontent must come *after* these tags -->\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" href=\"../../favicon.ico\"");

WriteLiteral(">\r\n    <title>eventcombo</title>\r\n    <!-- Bootstrap core CSS -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 553), Tuple.Create("\"", 578)
, Tuple.Create(Tuple.Create("", 560), Tuple.Create<System.Object, System.Int32>(Href("~/Content/font.css")
, 560), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Styles.Render("~/Content/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Styles.Render("~/Content/timepicker"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Styles.Render("~/Content/summernote"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 18 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Styles.Render("~/Content/multiselect"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Styles.Render("~/Content/datetimepicker"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Styles.Render("~/Content/fontawsome"));

            
            #line default
            #line hidden
WriteLiteral(@"
   

    <!-- Custom styles for this template -->
   
   
    <!--[if lt IE 9]>
      <script src=""https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js""></script>
      <script src=""https://oss.maxcdn.com/respond/1.4.2/respond.min.js""></script>
    <![endif]-->
 
");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Scripts.Render("~/bundles/jquery11.2"));

            
            #line default
            #line hidden
WriteLiteral("\r\n   \r\n");

WriteLiteral("    ");

            
            #line 33 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 34 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Scripts.Render("~/bundles/timezonescripts"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Scripts.Render("~/bundles/summernote"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 36 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Scripts.Render("~/bundles/boostrapmulti"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 37 "..\..\Views\Shared\_AccountLayout.cshtml"
Write(Scripts.Render("~/bundles/validation"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n   \r\n    ");

WriteLiteral("\r\n   \r\n\r\n</head>\r\n<body>\r\n    ");

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"container-fluid headr_main fix_head\"");

WriteLiteral(" id=\"mainhead\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"logo\"");

WriteLiteral(" href=\"/Home/Index\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 1769), Tuple.Create("\"", 1792)
, Tuple.Create(Tuple.Create("", 1775), Tuple.Create<System.Object, System.Int32>(Href("~/Images/logo.png")
, 1775), false)
);

WriteLiteral(" /></a>\r\n            </div>\r\n");

            
            #line 51 "..\..\Views\Shared\_AccountLayout.cshtml"
 if (HttpContext.Current.Session["AppId"] != null)
{

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-sm-5 head_left_nav\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"navbar-right frnt-top-header  xs-signup-height\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"msg_icn\"");

WriteLiteral("><span>12</span> </li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Welcome ");

            
            #line 56 "..\..\Views\Shared\_AccountLayout.cshtml"
                                              Html.RenderAction("UserName", "Home");
            
            #line default
            #line hidden
WriteLiteral("!</a> </li>\r\n                    <li");

WriteLiteral(" onclick=\"CheckUserOrgStatus();\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 58 "..\..\Views\Shared\_AccountLayout.cshtml"
                   Write(Html.ActionLink("My Account", "MyAccount", "Account", routeValues: null, htmlAttributes: new { title = "Account" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li>\r\n");

            
            #line 61 "..\..\Views\Shared\_AccountLayout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Shared\_AccountLayout.cshtml"
                         using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" href=\"javascript:document.getElementById(\'logoutForm\').submit()\"");

WriteLiteral(">Log Out </a>\r\n");

            
            #line 64 "..\..\Views\Shared\_AccountLayout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </li>\r\n                </ul>\r\n            </div>\r\n");

            
            #line 68 "..\..\Views\Shared\_AccountLayout.cshtml"
                        }
                        else
                        {


            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"col-sm-5 head_left_nav clearfix\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"navbar-right frnt-top-header xs-signup-height\"");

WriteLiteral(">\r\n\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#myModal\"");

WriteLiteral(" id=\"loginPopup\"");

WriteLiteral(">LogIn | SignUp </a>  </li>\r\n\r\n                                </ul>\r\n\r\n         " +
"                   </div>\r\n");

            
            #line 80 "..\..\Views\Shared\_AccountLayout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-sm-1 text-right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"social_icn\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"https://www.facebook.com/Eventcombo\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 3460), Tuple.Create("\"", 3481)
, Tuple.Create(Tuple.Create("", 3466), Tuple.Create<System.Object, System.Int32>(Href("~/Images/fb.png")
, 3466), false)
);

WriteLiteral(" /></a>\r\n                    <a");

WriteLiteral(" href=\"https://www.twitter.com/Eventcombo\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 3576), Tuple.Create("\"", 3597)
, Tuple.Create(Tuple.Create("", 3582), Tuple.Create<System.Object, System.Int32>(Href("~/Images/tw.png")
, 3582), false)
);

WriteLiteral(" /></a>\r\n                 \r\n                </div>\r\n            </div>\r\n         " +
"   <div");

WriteLiteral(" class=\"Fix_Head mt10\"");

WriteLiteral(" title=\"Turn on to fix header\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"switch\"");

WriteLiteral(">\r\n");

            
            #line 91 "..\..\Views\Shared\_AccountLayout.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Shared\_AccountLayout.cshtml"
                    

                      string header = CookieStore.GetCookie("ckHeader");


            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=", 3921), Tuple.Create("", 3962)
            
            #line 95 "..\..\Views\Shared\_AccountLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3928), Tuple.Create<System.Object, System.Int32>(CookieStore.GetCookie("ckHeader")
            
            #line default
            #line hidden
, 3928), false)
);

WriteLiteral(" id=\"hdheader\"");

WriteLiteral(" />\r\n");

            
            #line 96 "..\..\Views\Shared\_AccountLayout.cshtml"
                      if ((header != null) && (header != ""))
                      {
                          if (header == "on")
                          {

            
            #line default
            #line hidden
WriteLiteral("                            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"switch-input\"");

WriteLiteral(" id=\"idchecked\"");

WriteLiteral(" checked");

WriteLiteral(" onchange=\"changeheader(this.id);\"");

WriteLiteral(">\r\n");

            
            #line 101 "..\..\Views\Shared\_AccountLayout.cshtml"
                          }
                          else
                          {

            
            #line default
            #line hidden
WriteLiteral("                            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"switch-input\"");

WriteLiteral(" id=\"idchecked\"");

WriteLiteral(" onchange=\"changeheader(this.id);\"");

WriteLiteral(">\r\n");

            
            #line 105 "..\..\Views\Shared\_AccountLayout.cshtml"
                          }
                      }
                      else
                      {

            
            #line default
            #line hidden
WriteLiteral("                        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"switch-input\"");

WriteLiteral(" id=\"idchecked\"");

WriteLiteral(" onchange=\"changeheader(this.id);\"");

WriteLiteral(">\r\n");

            
            #line 110 "..\..\Views\Shared\_AccountLayout.cshtml"
                      }

                
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                    <span");

WriteLiteral(" class=\"switch-label\"");

WriteLiteral(" data-on=\"On\"");

WriteLiteral(" data-off=\"Off\"");

WriteLiteral(" ></span>\r\n                    <span");

WriteLiteral(" class=\"switch-handle\"");

WriteLiteral("></span>\r\n                </label>\r\n            </div>\r\n        </div>\r\n        <" +
"div");

WriteLiteral(" class=\"col-sm-12 filter_sep cont_margin\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5039), Tuple.Create("\"", 5122)
, Tuple.Create(Tuple.Create("", 5045), Tuple.Create<System.Object, System.Int32>(Href("~/Images/desi-")
, 5045), false)
            
            #line 120 "..\..\Views\Shared\_AccountLayout.cshtml"
, Tuple.Create(Tuple.Create("", 5059), Tuple.Create<System.Object, System.Int32>(HttpContext.Current.Session["logo"].ToString().Trim()
            
            #line default
            #line hidden
, 5059), false)
, Tuple.Create(Tuple.Create("", 5113), Tuple.Create("-logo.gif", 5113), true)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"cus_left_kick\"");

WriteLiteral("><</div>\r\n          \r\n        </div>\r\n\r\n    </div>\r\n\r\n   <div");

WriteLiteral(" class=\"container-fluid cont_margin\"");

WriteLiteral(" id=\"bodysec\"");

WriteLiteral(">\r\n");

            
            #line 128 "..\..\Views\Shared\_AccountLayout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 128 "..\..\Views\Shared\_AccountLayout.cshtml"
         if (HttpContext.Current.Session["Fromname"].ToString() == "events" || HttpContext.Current.Session["Fromname"].ToString() == "deals")
        {
            
            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\Shared\_AccountLayout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\Shared\_AccountLayout.cshtml"
                         
         

        }
        else
        {



            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row xs-ip6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-2 nav_ipad_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"affix-top\"");

WriteLiteral(" id=\"navtop\"");

WriteLiteral(">\r\n                    <nav");

WriteLiteral(" class=\"navbar navbar-default nav_cus_main \"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle collapsed nav_btn\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\"#navbar\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" aria-controls=\"navbar\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                            </button>\r\n\r\n                        </div>" +
"\r\n                        <div");

WriteLiteral(" id=\"navbar\"");

WriteLiteral(" class=\"navbar-collapse collapse nav_cus\"");

WriteLiteral(">\r\n");

            
            #line 152 "..\..\Views\Shared\_AccountLayout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 152 "..\..\Views\Shared\_AccountLayout.cshtml"
                             if (IsSectionDefined("sidenav"))
                            {
                                
            
            #line default
            #line hidden
            
            #line 154 "..\..\Views\Shared\_AccountLayout.cshtml"
                           Write(RenderSection("sidenav", false));

            
            #line default
            #line hidden
            
            #line 154 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                                
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" id=\"sidebar\"");

WriteLiteral(" class=\"nav nav-stacked\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"accordion\"");

WriteLiteral(" class=\"panel-group\"");

WriteLiteral(">\r\n\r\n                                        <div");

WriteLiteral(" class=\"panel panel-default menu_list\"");

WriteLiteral(">\r\n                                            <a");

WriteLiteral(" id=\"mgacnt\"");

WriteLiteral(" class=\"menu_title\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#accordion\"");

WriteLiteral(" href=\"#collapse1\"");

WriteLiteral(">\r\n                                              <div");

WriteLiteral(" id=\"dvacmang\"");

WriteAttribute("class", Tuple.Create(" class=\"", 7090), Tuple.Create("\"", 7163)
, Tuple.Create(Tuple.Create("", 7098), Tuple.Create("panel-heading", 7098), true)
            
            #line 163 "..\..\Views\Shared\_AccountLayout.cshtml"
      , Tuple.Create(Tuple.Create("", 7111), Tuple.Create<System.Object, System.Int32>(ViewBag.CurrentItem == "account" ? " active" : ""
            
            #line default
            #line hidden
, 7111), false)
);

WriteLiteral(">\r\n                                                Account <b");

WriteLiteral(" class=\"closed\"");

WriteLiteral("></b>\r\n                                              </div>\r\n                    " +
"                        </a>\r\n\r\n                                          <div");

WriteLiteral(" id=\"collapse1\"");

WriteAttribute("class", Tuple.Create(" class=\"", 7414), Tuple.Create("\"", 7493)
, Tuple.Create(Tuple.Create("", 7422), Tuple.Create("panel-collapse", 7422), true)
, Tuple.Create(Tuple.Create(" ", 7436), Tuple.Create("collapse", 7437), true)
            
            #line 168 "..\..\Views\Shared\_AccountLayout.cshtml"
             , Tuple.Create(Tuple.Create("", 7445), Tuple.Create<System.Object, System.Int32>(ViewBag.CurrentItem == "account" ? " in" : ""
            
            #line default
            #line hidden
, 7445), false)
);

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"panel-body no-padding\"");

WriteLiteral(">\r\n                                              <p>");

            
            #line 170 "..\..\Views\Shared\_AccountLayout.cshtml"
                                            Write(Html.ActionLink("Personal Information", "MyAccount", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                              <p>");

            
            #line 171 "..\..\Views\Shared\_AccountLayout.cshtml"
                                            Write(Html.ActionLink("My Purchased Ticket", "PurchasedTicket", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                              <p>");

            
            #line 172 "..\..\Views\Shared\_AccountLayout.cshtml"
                                            Write(Html.ActionLink("My Purchased Deals", "PurchasedDeals", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                              <p>");

            
            #line 173 "..\..\Views\Shared\_AccountLayout.cshtml"
                                            Write(Html.ActionLink("Manage Organizer", "OrganizerProfile", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                            </div>\r\n                       " +
"                   </div>\r\n                                        </div>\r\n     " +
"                                   <div");

WriteLiteral(" class=\"panel panel-default menu_list\"");

WriteLiteral(">\r\n\r\n                                            <a");

WriteLiteral(" id=\"mgnav\"");

WriteLiteral(" class=\"menu_title\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#accordion\"");

WriteLiteral(" href=\"#collapse2\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" id=\"dvManage\"");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                                                    Manage Events <b");

WriteLiteral(" class=\"closed\"");

WriteLiteral("></b>\r\n                                                </div>\r\n                  " +
"                          </a>\r\n\r\n                                            <d" +
"iv");

WriteLiteral(" id=\"collapse2\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"panel-body no-padding\"");

WriteLiteral(">\r\n                                                    \r\n                        " +
"                            <p><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"pAcc\"");

WriteLiteral(">Create Event</a></p>\r\n                                                    <p>");

            
            #line 189 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("My Events", "EventList", "EventList"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                  \r\n                       " +
"                             <p>");

            
            #line 191 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Events Help", "EventHelp", "Account"));

            
            #line default
            #line hidden
WriteLiteral(@"</p>

                                                   
                                                </div>
                                            </div>
                                        </div>
                                        <div");

WriteLiteral(" class=\"panel panel-default menu_list\"");

WriteLiteral(">\r\n\r\n                                            <a");

WriteLiteral(" id=\"dealnav\"");

WriteLiteral(" class=\"menu_title\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#accordion\"");

WriteLiteral(" href=\"#collapse3\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" id=\"dvmngdeal\"");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                                                    Manage Deals <b");

WriteLiteral(" class=\"closed\"");

WriteLiteral("></b>\r\n                                                </div>\r\n                  " +
"                          </a>\r\n\r\n                                            <d" +
"iv");

WriteLiteral(" id=\"collapse3\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"panel-body no-padding\"");

WriteLiteral(">\r\n                                                    <p>Create Deal</p>\r\n      " +
"                                              <p>");

            
            #line 208 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Deals Dashboard", "DealsDashboard", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                    <p>");

            
            #line 209 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Current Deals", "CurrentDeals", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                    <p>");

            
            #line 210 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Past Deals", "PastDeals", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                    <p>");

            
            #line 211 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Feedback", "Feedback", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                    <p>");

            
            #line 212 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Overview", "Overview", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                    <p>");

            
            #line 213 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Impact Report", "ImpactReport", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                    <p>");

            
            #line 214 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Invoice History", "InvoiceHistory", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                    <p>");

            
            #line 215 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Customers", "Customers", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                    <p>");

            
            #line 216 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Deals Help", "DealsHelp", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                    <p>");

            
            #line 217 "..\..\Views\Shared\_AccountLayout.cshtml"
                                                  Write(Html.ActionLink("Merchant Profile", "MerchantProfile", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                                </div>\r\n                   " +
"                         </div>\r\n                                        </div>\r" +
"\n                                    </div>\r\n                                </d" +
"iv>\r\n");

            
            #line 223 "..\..\Views\Shared\_AccountLayout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                                  \r\n                                  \r\n         " +
"           </div>\r\n            </nav>\r\n                </div>\r\n            </div" +
">\r\n            <div");

WriteLiteral(" class=\"col-sm-10 nav_ipad_right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"midd_cont\"");

WriteLiteral(" id=\"midsection\"");

WriteLiteral(">\r\n                    \r\n");

WriteLiteral("                    ");

            
            #line 233 "..\..\Views\Shared\_AccountLayout.cshtml"
               Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 238 "..\..\Views\Shared\_AccountLayout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"dtBox\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"UserOrgnizer\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-dialog modal-sm confirm-msg ok-msg custom\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                <form");

WriteLiteral(" id=\"contactForm\"");

WriteLiteral(" class=\"fullw1 add\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"modal-body text-center pv50 txt-msg\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"msg\"");

WriteLiteral(" id=\"hId\"");

WriteLiteral(">You are not authorized to create event, please contact admin</h4>\r\n             " +
"       </div>\r\n                    <div");

WriteLiteral(" class=\"modal-footer msg-action-btn ok\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary yes ok\"");

WriteLiteral(" id=\"btMessOk\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">OK</button>\r\n                    </div>\r\n                </form>\r\n            </" +
"div>\r\n        </div><!-- confirm-msg -->\r\n    </div>\r\n\r\n    <div>\r\n        <a");

WriteLiteral(" class=\"td-btn\"");

WriteLiteral(" id=\"btOkMes\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(" href=\"#UserOrgnizer\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n        </a>\r\n    </div>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(window).load(function () {\r\n\r\n            var headervale = $(\"#hdhea" +
"der\").val();;\r\n         \r\n            if (headervale != undefined && headervale " +
"!= null && headervale != \'\') {\r\n\r\n                if (headervale == \"on\") {\r\n   " +
"                 $(\'#mainhead\').addClass(\'fix_head\');\r\n                    $(\'#b" +
"odysec\').addClass(\'cont_margin\');\r\n                    $(\'#navtop\').addClass(\'af" +
"fix-top\');\r\n                    $(\'#midsection\').addClass(\'midd_cont\');\r\n       " +
"             $(\'#eventtop\').addClass(\'event_top\');\r\n                    $(\'#even" +
"ttopscoll\').addClass(\'event_top\');\r\n\r\n                    $(\'#divsuccerr\').addCl" +
"ass(\'aler_container\');\r\n                    $(\'#eventtopscoll\').addClass(\'viewev" +
"ent_container\');\r\n                  \r\n                }\r\n                else {\r" +
"\n                    $(\'#mainhead\').removeClass(\'fix_head\');\r\n                  " +
"  $(\'#bodysec\').removeClass(\'cont_margin\');\r\n                    $(\'#navtop\').re" +
"moveClass(\'affix-top\');\r\n                    $(\'#midsection\').removeClass(\'midd_" +
"cont\');\r\n                    $(\'#eventtopscoll\').removeClass(\'event_top\');\r\n    " +
"                $(\'#eventtop\').removeClass(\'event_top\');\r\n                    $(" +
"\'#divsuccerr\').removeClass(\'aler_container\');\r\n\r\n                    $(\'#eventto" +
"pscoll\').removeClass(\'viewevent_container\');\r\n                  \r\n\r\n            " +
"    }\r\n            } else {\r\n                $(\'#mainhead\').removeClass(\'fix_hea" +
"d\');\r\n                $(\'#bodysec\').removeClass(\'cont_margin\');\r\n               " +
" $(\'#navtop\').removeClass(\'affix-top\');\r\n                $(\'#midsection\').remove" +
"Class(\'midd_cont\');\r\n                $(\'#eventtopscoll\').removeClass(\'event_top\'" +
");\r\n                $(\'#eventtop\').removeClass(\'event_top\');\r\n                $(" +
"\'#divsuccerr\').removeClass(\'aler_container\');\r\n\r\n                $(\'#eventtopsco" +
"ll\').removeClass(\'viewevent_container\');;\r\n              \r\n            }\r\n\r\n\r\n\r\n" +
"\r\n\r\n\r\n        });\r\n\r\n        $(\"#pAcc\").click(function () {\r\n            $.ajax(" +
"{\r\n                url: \'");

            
            #line 316 "..\..\Views\Shared\_AccountLayout.cshtml"
                 Write(Url.Action("UserOrgStatus", "Home"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                type: ""GET"",
                datatype: ""Text"",
                success: function (data) {
                    if (data==""N"")
                    {
                        $(""#btOkMes"").click();
                    }
                    else {
                        window.location.href = '");

            
            #line 325 "..\..\Views\Shared\_AccountLayout.cshtml"
                                           Write(Url.Action("CreateEvent", "CreateEvent"));

            
            #line default
            #line hidden
WriteLiteral(@"';
                    
                    }
                },
                error: function (data) {
                    return false
                }
            });

        });

   




    function changeheader(e)
    {
        if ($('#idchecked').is("":checked"") == true) {
            $.ajax({
                url: '");

            
            #line 345 "..\..\Views\Shared\_AccountLayout.cshtml"
                 Write(Url.Action("Setheader", "Home"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                type: ""Post"",
                data: { header: ""on"" },
                success: function (data) {


                },
                error: function (data) {
                   
                    return false
                }
            });

           
            $('#mainhead').addClass('fix_head');
            $('#bodysec').addClass('cont_margin');
            $('#navtop').addClass('affix-top');
            $('#midsection').addClass('midd_cont');
            $('#eventtop').addClass('event_top');
            $('#eventtopscoll').addClass('event_top');

            $('#divsuccerr').addClass('aler_container');
            $('#eventtopscoll').addClass('viewevent_container');
        } else
        {
            $.ajax({
                url: '");

            
            #line 371 "..\..\Views\Shared\_AccountLayout.cshtml"
                 Write(Url.Action("Setheader", "Home"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                type: ""Post"",
                data: { header: ""off"" },
                success: function (data) {


                },
                error: function (data) {
                   
                    return false
                }
            });
           
            $('#mainhead').removeClass('fix_head');
            $('#bodysec').removeClass('cont_margin');
            $('#navtop').removeClass('affix-top');
            $('#midsection').removeClass('midd_cont');
            $('#eventtopscoll').removeClass('event_top');
            $('#eventtop').removeClass('event_top');
            $('#divsuccerr').removeClass('aler_container');

            $('#eventtopscoll').removeClass('viewevent_container');
        }
    }
    </script>


    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50065120-1', 'auto');
  ga('send', 'pageview');

    </script>
</body>

</html>



");

        }
    }
}
#pragma warning restore 1591
