#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EventCombo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n    <!-- The above 3 meta tags *must* come first in the head; any other head c" +
"ontent must come *after* these tags -->\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n    <title>eventcombo</title>\r\n    <!-- Bootstrap core CSS -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 509), Tuple.Create("\"", 539)
, Tuple.Create(Tuple.Create("", 516), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap.css")
, 516), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n \r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 576), Tuple.Create("\"", 614)
, Tuple.Create(Tuple.Create("", 583), Tuple.Create<System.Object, System.Int32>(Href("~/Content/jquery.timepicker.css")
, 583), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    \r\n\r\n    <!-- Custom styles for this template -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 702), Tuple.Create("\"", 733)
, Tuple.Create(Tuple.Create("", 709), Tuple.Create<System.Object, System.Int32>(Href("~/Content/eventcombo.css")
, 709), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(@" />
    <!--  <link href=""http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"" rel=""stylesheet""> -->
    <!--[if lt IE 9]>
      <script src=""https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js""></script>
      <script src=""https://oss.maxcdn.com/respond/1.4.2/respond.min.js""></script>
    <![endif]-->

    <script");

WriteLiteral(" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1196), Tuple.Create("\"", 1228)
, Tuple.Create(Tuple.Create("", 1202), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/bootstrap.min.js")
, 1202), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1252), Tuple.Create("\"", 1275)
, Tuple.Create(Tuple.Create("", 1258), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/main.js")
, 1258), false)
);

WriteLiteral("></script>\r\n   \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1304), Tuple.Create("\"", 1340)
, Tuple.Create(Tuple.Create("", 1310), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.timepicker.js")
, 1310), false)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1366), Tuple.Create("\"", 1398)
, Tuple.Create(Tuple.Create("", 1372), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.cookie.js")
, 1372), false)
);

WriteLiteral("></script>\r\n   \r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        html {\r\n  overflow-x: hidden;\r\n  overflow-y: auto;\r\n}\r\n\r\n    </style>\r" +
"\n</head>\r\n\r\n<body>\r\n\r\n\r\n\r\n    <!-- Header -->\r\n    <div");

WriteLiteral(" class=\"home_fixed_header\"");

WriteLiteral(" id=\"divmain\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid headr_main \"");

WriteLiteral(" id=\"divsecmain\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"logo\"");

WriteLiteral(" href=\"/Home/Index\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 1817), Tuple.Create("\"", 1851)
, Tuple.Create(Tuple.Create(" ", 1823), Tuple.Create<System.Object, System.Int32>(Href(" ~/Images/EventCombo_Red.jpg")
, 1824), false)
);

WriteLiteral(" /></a>\r\n                </div>\r\n");

            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
                 if (HttpContext.Current.Session["AppId"] != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"col-sm-5 head_left_nav\"");

WriteLiteral(">\r\n                        <ul");

WriteLiteral(" class=\"navbar-right frnt-top-header\"");

WriteLiteral(">\r\n\r\n                            <li>");

            
            #line 62 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.Partial("_Logout"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\r\n                        </ul>\r\n\r\n                    </div>\r\n");

            
            #line 67 "..\..\Views\Shared\_Layout.cshtml"

                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"col-sm-5 head_left_nav\"");

WriteLiteral(">\r\n                        <ul");

WriteLiteral(" class=\"navbar-right frnt-top-header\"");

WriteLiteral(">\r\n\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#myModal\"");

WriteLiteral(" id=\"loginPopup\"");

WriteLiteral(">LogIn | SignUp </a>  </li>\r\n\r\n                        </ul>\r\n\r\n                 " +
"   </div>\r\n");

            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"Fix_Head\"");

WriteLiteral(" title=\"Turn on to fix header\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"switch\"");

WriteLiteral(">\r\n                       <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"switch-input\"");

WriteLiteral(" checked");

WriteLiteral("  id=\"idchecked\"");

WriteLiteral(" onchange=\"changeheader(this.id);\"");

WriteLiteral(" >\r\n                        <span");

WriteLiteral(" class=\"switch-label\"");

WriteLiteral(" data-on=\"On\"");

WriteLiteral(" data-off=\"Off\"");

WriteLiteral("></span>\r\n                        <span");

WriteLiteral(" class=\"switch-handle\"");

WriteLiteral("></span>\r\n                    </label>\r\n                </div>\r\n                <" +
"div");

WriteLiteral(" class=\"col-sm-1 text-right\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"social_icn\"");

WriteLiteral(" style=\"width:40px; margin-top:10px;\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://www.facebook.com/Eventcombo\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 3297), Tuple.Create("\"", 3318)
, Tuple.Create(Tuple.Create("", 3303), Tuple.Create<System.Object, System.Int32>(Href("~/Images/fb.png")
, 3303), false)
);

WriteLiteral(" /></a>\r\n                        <a");

WriteLiteral(" href=\"http://www.twitter.com/Eventcombo\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 3416), Tuple.Create("\"", 3437)
, Tuple.Create(Tuple.Create("", 3422), Tuple.Create<System.Object, System.Int32>(Href("~/Images/tw.png")
, 3422), false)
);

WriteLiteral(" /></a>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n" +
"        </div>\r\n\r\n");

            
            #line 97 "..\..\Views\Shared\_Layout.cshtml"
 if (HttpContext.Current.Session["Fromname"] == null)
{

            
            #line default
            #line hidden
WriteLiteral("     <!-- Sub Header -->\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"container-fluid cont_margin2\"");

WriteLiteral(" id=\"divcontmain\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row cyan-line-new\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                <form>\r\n                    <div");

WriteLiteral(" class=\"input-group stylish-input-group\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control place_hold\"");

WriteLiteral(" onfocus=\"javascript:this.value=\'\'\"");

WriteLiteral(" placeholder=\"Search for Event\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"glyphicon glyphicon-search\"");

WriteLiteral("></span>\r\n                            </button>\r\n                        </span>\r" +
"\n                    </div>\r\n                </form>\r\n            </div>\r\n      " +
"      <div");

WriteLiteral(" class=\"col-sm-2 disc_title_head\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" onclick=\"setsession(this.id);\"");

WriteLiteral(" id=\'discover\'");

WriteLiteral(">Discover Events</a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-sm-2 disc_title_head\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" onclick=\"setsession(this.id);\"");

WriteLiteral(" id=\'GetBuzz\'");

WriteLiteral(">Get the Buzz</a>");

WriteLiteral("  </div>\r\n            <div");

WriteLiteral(" class=\"col-sm-5 frnt_cret_evnt\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"psst\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" onclick=\"checksession();\"");

WriteLiteral(">Create Event</a>\r\n                </div>\r\n\r\n            \r\n            </div>\r\n\r\n" +
"        </div>\r\n    </div>\r\n");

WriteLiteral("        <!-- Body Section -->\r\n");

            
            #line 130 "..\..\Views\Shared\_Layout.cshtml"
        }
        else
        {
            
            if (HttpContext.Current.Session["Fromname"].ToString() == "events")
            {


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-12 filter_sep cont_margin\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5262), Tuple.Create("\"", 5297)
, Tuple.Create(Tuple.Create("", 5268), Tuple.Create<System.Object, System.Int32>(Href("~/Images/desi-events-logo.gif")
, 5268), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"cus_left_kick\"");

WriteLiteral("><</div>\r\n        </div>\r\n");

            
            #line 141 "..\..\Views\Shared\_Layout.cshtml"

    }
    else
    {


            
            #line default
            #line hidden
WriteLiteral("     <!-- Sub Header -->\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"container-fluid cont_margin2\"");

WriteLiteral(" id=\"divcontmain\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row cyan-line-new\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                    <form>\r\n                        <div");

WriteLiteral(" class=\"input-group stylish-input-group\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control place_hold\"");

WriteLiteral(" onfocus=\"javascript:this.value=\'\'\"");

WriteLiteral(" placeholder=\"Searh for Event\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-search\"");

WriteLiteral("></span>\r\n                                </button>\r\n                            " +
"</span>\r\n                        </div>\r\n                    </form>\r\n          " +
"      </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-2 disc_title_head\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" onclick=\"setsession(this.id);\"");

WriteLiteral(" id=\'discover\'");

WriteLiteral(">Discover Events</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-2 disc_title_head\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" onclick=\"setsession(this.id);\"");

WriteLiteral(" id=\'GetBuzz\'");

WriteLiteral(">Get the Buzz</a>");

WriteLiteral("  </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-5 frnt_cret_evnt\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"psst\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" onclick=\"checksession();\"");

WriteLiteral(">Create Event</a>\r\n                    </div>\r\n\r\n                   \r\n           " +
"     </div>\r\n\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <!-- Body Section -->\r\n");

            
            #line 177 "..\..\Views\Shared\_Layout.cshtml"

    }

}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n      \r\n    </div>\r\n        <div>\r\n");

WriteLiteral("            ");

            
            #line 186 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n");

            
            #line 189 "..\..\Views\Shared\_Layout.cshtml"
 if (HttpContext.Current.Session["Fromname"] == null)
{


            
            #line default
            #line hidden
WriteLiteral("        <!--Footer Section-->\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"container-fluid foot_bg\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-12 foot_logo\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 7314), Tuple.Create("\"", 7343)
, Tuple.Create(Tuple.Create("", 7320), Tuple.Create<System.Object, System.Int32>(Href("~/Images/logo_small.png")
, 7320), false)
);

WriteLiteral(" /></a>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"row fot_cont\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">About Us</a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Contact Us</a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Terms Of Service</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Ticket Purchase FAQ </a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Ticket Fulfillment Policy</a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Privacy Policy</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Facebook</a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Twitter</a>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </d" +
"iv>\r\n");

            
            #line 222 "..\..\Views\Shared\_Layout.cshtml"

}
else
{
  
    if (HttpContext.Current.Session["Fromname"].ToString() == "events")
    {
    }
    else
    {


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"container-fluid foot_bg\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-12 foot_logo\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 8496), Tuple.Create("\"", 8525)
, Tuple.Create(Tuple.Create("", 8502), Tuple.Create<System.Object, System.Int32>(Href("~/Images/logo_small.png")
, 8502), false)
);

WriteLiteral(" /></a>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"row fot_cont\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">About Us</a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Contact Us</a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Terms Of Service</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Ticket Purchase FAQ </a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Ticket Fulfillment Policy</a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Privacy Policy</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Facebook</a>\r\n                    <br>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Twitter</a>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </d" +
"iv>\r\n");

            
            #line 262 "..\..\Views\Shared\_Layout.cshtml"

    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n        <!-- Dialouge Box Start -->\r\n        <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"myModal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myModalLabel\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content login_pop\"");

WriteLiteral(" id=\"login_up\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                        <h3");

WriteLiteral(" class=\"modal-title \"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral(">Login / Sign-up</h3>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 276 "..\..\Views\Shared\_Layout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 276 "..\..\Views\Shared\_Layout.cshtml"
                             using (Html.BeginForm("Login", "Account", new { ReturnUrl = Session["ReturnUrl"] }, FormMethod.Post, new { role = "form", id = "formlogin", @class = "form-horizontal acnt_form" }))
                            {

                               


            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"err_main\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"er_UI_main alert-danger\"");

WriteLiteral(" id=\"diverrologin\"");

WriteLiteral(" style=\"display :none;width:100%\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" class=\"close closebtn\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btndiverrologin\"");

WriteLiteral(">&#215;</button>\r\n                                        <div");

WriteLiteral(" class=\"er_UI_img\"");

WriteLiteral("></div>\r\n                                        <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(" id=\"dverrui\"");

WriteLiteral(">  </div>\r\n                                    </div>\r\n                          " +
"      </div>\r\n");

            
            #line 288 "..\..\Views\Shared\_Layout.cshtml"



            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"err_main\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"er_UI_main alert-danger\"");

WriteLiteral(" id=\"diverro1login\"");

WriteLiteral(" style=\"display :none;width:100%\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" class=\"close closebtn\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btndiverro1login\"");

WriteLiteral(">&#215;</button>\r\n                                        <div");

WriteLiteral(" class=\"er_sys_img\"");

WriteLiteral("></div>\r\n                                        <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(" id=\"dverrsys\"");

WriteLiteral(">  </div>\r\n                                    </div>\r\n                          " +
"      </div>\r\n");

WriteLiteral("                                <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 298 "..\..\Views\Shared\_Layout.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-sm-5 login_form_bot\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"loginemail\"");

WriteLiteral(" name=\"Email\"");

WriteLiteral(" placeholder=\"Email\"");

WriteLiteral(" class=\"form-control login_place\"");

WriteLiteral("  maxlength=\"256\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                                                ");

WriteLiteral("\r\n                                            </div>\r\n                           " +
"                 <div");

WriteLiteral(" class=\"col-sm-5 login_form_bot\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"loginpassword\"");

WriteLiteral(" name=\"Password\"");

WriteLiteral(" placeholder=\"Password\"");

WriteLiteral(" class=\"form-control login_place\"");

WriteLiteral(" maxlength=\"15\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n\r\n                                                ");

WriteLiteral("\r\n                                            </div>\r\n                           " +
"                 <div");

WriteLiteral(" class=\"col-sm-2 login_form_bot\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hderror\"");

WriteLiteral(" />\r\n                                                <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"LOGIN\"");

WriteLiteral(" class=\"btn btn-primary login_btn_sub\"");

WriteLiteral(" id=\"btnSavelogin\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" />\r\n                                            </div>\r\n                        " +
"                </div>\r\n                                    </div>\r\n            " +
"                    </div>\r\n");

            
            #line 318 "..\..\Views\Shared\_Layout.cshtml"




                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            ");

WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 328 "..\..\Views\Shared\_Layout.cshtml"
                       Write(Html.ActionLink("forgot password?", "ForgetPassword", "Home", null, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                           \r\n                        </div>\r\n                  " +
"      <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"social_net_log\"");

WriteLiteral(">Use your social network login below or &nbsp;</span> <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"signUpPopup\"");

WriteLiteral(" class=\"btn btn-primary login_btn_sub\"");

WriteLiteral(">Sign UP</a>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                        <div");

WriteLiteral(" class=\"col-md-12 social-buttons text-center \"");

WriteLiteral(">\r\n                            <form");

WriteLiteral(" id=\"login-launch\"");

WriteAttribute("action", Tuple.Create(" action=\"", 14211), Tuple.Create("\"", 14259)
            
            #line 336 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 14220), Tuple.Create<System.Object, System.Int32>(Url.Action("ExternalLogin", "Account")
            
            #line default
            #line hidden
, 14220), false)
);

WriteLiteral(" method=\"POST\"");

WriteLiteral(" target=\"login-popup\"");

WriteLiteral(" onsubmit=\"invokeLogin();\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"provider\"");

WriteLiteral(" name=\"provider\"");

WriteLiteral(" />\r\n                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"returnUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 14651), Tuple.Create("\"", 14677)
            
            #line 340 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 14659), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnUrl
            
            #line default
            #line hidden
, 14659), false)
);

WriteLiteral(" />\r\n\r\n                                    <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" onclick=\"$(\'#provider\').attr(\'value\', \'Facebook\'); $(\'#login-launch\').submit();\"" +
"");

WriteLiteral(" class=\"btn btn-block btn-social btn-facebook\"");

WriteLiteral(" id=\"Facebook\"");

WriteLiteral(" name=\"provider\"");

WriteLiteral(" value=\"Facebook\"");

WriteLiteral(" title=\"Log in using your Facebook account\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-facebook\"");

WriteLiteral("></i>Facebook</button>\r\n\r\n                                    </div>\r\n\r\n         " +
"                           <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" onclick=\"$(\'#provider\').attr(\'value\', \'Google\'); $(\'#login-launch\').submit(); \"");

WriteLiteral(" class=\"btn btn-block btn-social btn-google-plus\"");

WriteLiteral(" id=\"Google\"");

WriteLiteral(" name=\"provider\"");

WriteLiteral(" value=\"Google\"");

WriteLiteral(" title=\"Log in using your Google account\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-google-plus\"");

WriteLiteral("></i>Google</button>\r\n                                    </div>\r\n\r\n             " +
"                   ");

WriteLiteral("\r\n                                </form>\r\n                                ");

WriteLiteral("\r\n</div>\r\n                    </div>\r\n                </div>\r\n\r\n                <" +
"div");

WriteLiteral(" id=\"sign_up\"");

WriteLiteral(" class=\"modal-content login_pop sign_up\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close closefrgt\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(" ><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                        <h3");

WriteLiteral(" class=\"modal-title \"");

WriteLiteral(">Sign-up</h3>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\r\n");

            
            #line 366 "..\..\Views\Shared\_Layout.cshtml"
 using (Html.BeginForm("Signup", "Home", FormMethod.Post, new { role = "form", id = "form", @class = "form-horizontal acnt_form" }))
{

    if (ViewData["Message"] != null)
    {
            
            #line default
            #line hidden
WriteLiteral("<div");

WriteLiteral(" class=\"err_main\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"er_suc_main\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"er_suc_img\"");

WriteLiteral("></div>\r\n                                    <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(">ViewData[\"Message\"] </div>\r\n                                </div>\r\n            " +
"                </div>\r\n");

            
            #line 376 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"err_main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"er_UI_main alert-danger\"");

WriteLiteral(" id=\"diverro\"");

WriteLiteral(" style=\"display :none;width:100%\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"close closebtn\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btndiverro\"");

WriteLiteral(">&#215;</button>\r\n            <div");

WriteLiteral(" class=\"er_UI_img\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(" id=\"dverrsignui\"");

WriteLiteral(">  </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 384 "..\..\Views\Shared\_Layout.cshtml"



            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"err_main\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"er_UI_main alert-danger\"");

WriteLiteral(" id=\"diverro1\"");

WriteLiteral(" style=\"display :none;width:100%\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"close closebtn\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btndiverro1\"");

WriteLiteral(">&#215;</button>\r\n                <div");

WriteLiteral(" class=\"er_sys_img\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(" id=\"dverrsignsys\"");

WriteLiteral(">  </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-5 login_form_bot\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SignupEmail\"");

WriteLiteral(" name=\"Email\"");

WriteLiteral(" placeholder=\"Email\"");

WriteLiteral(" class=\"form-control login_place\"");

WriteLiteral(" maxlength=\"256\"");

WriteLiteral("  autocomplete=\"off\"");

WriteLiteral("/>\r\n\r\n                            ");

WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-5 login_form_bot\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"SignupPassword\"");

WriteLiteral(" name=\"Password\"");

WriteLiteral(" placeholder=\"Password\"");

WriteLiteral(" class=\"form-control login_place\"");

WriteLiteral(" maxlength=\"15\"");

WriteLiteral("  autocomplete=\"off\"");

WriteLiteral("/>\r\n\r\n                            ");

WriteLiteral("\r\n\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-2 login_form_bot\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"SignUp\"");

WriteLiteral(" class=\"btn btn-primary login_btn_sub\"");

WriteLiteral(" id=\"btnsave\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" />\r\n                        </div>\r\n\r\n                   \r\n                    <" +
"/div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(" id=\"divsignupfrgt\"");

WriteLiteral(">\r\n                 \r\n");

WriteLiteral("                    ");

            
            #line 418 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.ActionLink("forgot password?", "ForgetPassword", "Home",null, new { id="ASignupfrgt"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div>\r\n            </div>\r\n");

            
            #line 422 "..\..\Views\Shared\_Layout.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                            ");

WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n               <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"url\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n</body>\r\n</html>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

    var WindowObjectReference;
    function invokeLogin() {
        debugger;
        var chrome = 100;       
        var width = 600;        
        var height = 500;       
        var left = (screen.width - width) / 2;
        var top = (screen.height - height - chrome) / 2;
        var options = ""location=0, menubar=0, status=0, toolbar=0, scrollbars=0, resizable=0,left="" + left + "",top="" + top + "",width="" + width + "",height="" + height;
        WindowObjectReference= window.open(""about:blank"", ""login-popup"", options);
        WindowObjectReference.screenX = 0;
        WindowObjectReference.screenY = 0;
        WindowObjectReference
    }
</script>
<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function loginCallback(success, returnUrl) {
        if (returnUrl.indexOf('~') > -1)
        {
            urlarray = returnUrl.split('~');
            returnUrl = urlarray[1];
        }
        if (returnUrl) {
            window.location.href = returnUrl;
        } else {
            ");

WriteLiteral(@"
        }
    }

    function changeheader(e)
    {
        if ($('#idchecked').is("":checked"") == true) {
            $('#divmain').addClass('home_fixed_header');
            $('#eventtopscoll').addClass('event_top');
            $('#scrollhome').addClass('con_scr0l_home');
            $('#divcontmain').addClass('mt15');
            $('#buttonscroll').addClass('mt5');
            $('#eventtopscoll').addClass('viewevent_container');
        } else
        {
            $('#eventtopscoll').removeClass('event_top');
            $('#scrollhome').removeClass('con_scr0l_home');
            $('#divmain').removeClass('home_fixed_header');
            $('#buttonscroll').removeClass('mt5');
            $('#divcontmain').removeClass('mt15');
           
            $('#eventtopscoll').removeClass('viewevent_container');
        }
    }
    function setsession(e) {
        $.ajax({
            url: '");

            
            #line 492 "..\..\Views\Shared\_Layout.cshtml"
             Write(Url.Action("setsessid", "Home"));

            
            #line default
            #line hidden
WriteLiteral(@"',
            data:{id:e},
            type: ""Post"",
            success: function (data) {

            },
            error: function (data) {
                alert(""Sorry there is some problem."");
                return false
            }
        });
   
        if (e == ""discover"") {

            window.location.href = '");

            
            #line 506 "..\..\Views\Shared\_Layout.cshtml"
                               Write(Url.Action("DiscoverEvents", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\r\n\r\n\r\n        }\r\n\r\n        if (e == \"GetBuzz\") {\r\n            window.location" +
".href = \'");

            
            #line 513 "..\..\Views\Shared\_Layout.cshtml"
                               Write(Url.Action("GetBuzz", "Home"));

            
            #line default
            #line hidden
WriteLiteral(@"';
      



        }
    }
    $(""#signUpPopup"").on('click', function () {
        $('#SignupEmail').css(""border"", ""black solid 1px"");
        $('#SignupPassword').css(""border"", ""black solid 1px"");
        $('#diverro1').css('display', 'none');
        $('#diverro').css(""display"", ""none"");
      $(""#login_up"").css({""display"":""none""});
      $(""#sign_up"").css({ ""display"": ""block"" });
      $('#divsignupfrgt').css({""display"":""none""});

    });

    $(""#loginPopup"").on('click', function () {
        if (loginemail != '' || loginpwd != '') {
            $('#btnSavelogin').removeAttr(""disabled"");
        }
        $('#loginemail').css(""border"", ""black solid 1px"");
        $('#loginpassword').css(""border"", ""black solid 1px"");
        $('#diverro1login').css('display', 'none');
        $('#diverrologin').css(""display"", ""none"");
      $(""#login_up"").css({""display"":""block""});
      $(""#sign_up"").css({""display"":""none""});

    });
   
    function checksession()
    {
        $.ajax({
            url: '");

            
            #line 547 "..\..\Views\Shared\_Layout.cshtml"
             Write(Url.Action("checkid", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            type: \"Post\",\r\n            success: function (data) {\r\n          " +
"    \r\n                if (data == \"Y\") {\r\n                    $(\"#loginPopup\").c" +
"lick();\r\n                    url.val(\'");

            
            #line 553 "..\..\Views\Shared\_Layout.cshtml"
                        Write(Url.Action("CreateEvent", "CreateEvent"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n                    return false;\r\n                } else {\r\n               " +
"     window.location.href = \'");

            
            #line 556 "..\..\Views\Shared\_Layout.cshtml"
                                       Write(Url.Action("CreateEvent", "CreateEvent"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n                    return true;\r\n                }\r\n            },\r\n        " +
"    error: function (data) {\r\n                alert(\"Sorry there is some problem" +
".\");\r\n                return false\r\n            }\r\n        });\r\n\r\n    }\r\n</scrip" +
"t>\r\n\r\n\r\n");

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n\r\n    $(document).click(function () {\r\n       \r\n     \r\n\r\n              $(\'#d" +
"iverrologin\').css(\'display\', \'none\');\r\n              $(\'#diverro1login\').css(\'di" +
"splay\', \'none\');\r\n\r\n\r\n              $(\"input\").removeClass(\'err-bor\');\r\n        " +
"  });\r\n          $(\'#btndiverrologin\').click(function () {\r\n              $(\'#di" +
"verrologin\').css(\'display\', \'none\');\r\n              $(\'#diverro1login\').css(\'dis" +
"play\', \'none\');\r\n\r\n              $(\"input\").removeClass(\'err-bor\');\r\n          }" +
")\r\n          $(\'#btndiverro1login\').click(function () {\r\n              $(\'#diver" +
"rologin\').css(\'display\', \'none\');\r\n              $(\'#diverro1login\').css(\'displa" +
"y\', \'none\');\r\n\r\n              $(\"input\").removeClass(\'err-bor\');\r\n          })\r\n" +
"          $(window).load(function () {\r\n\r\n           \r\n              var loginem" +
"ail = $(\'#loginemail\').val();\r\n              var loginpwd = $(\'#loginpassword\')." +
"val();\r\n              var signupemail = $(\'#SignupEmail\').val();\r\n              " +
"var signuppwd = $(\'#SignupPassword\').val();\r\n\r\n              if (loginemail != \'" +
"\' || loginpwd!=\'\') {\r\n                  $(\'#btnSavelogin\').removeAttr(\"disabled\"" +
");\r\n\r\n              }\r\n              if (signupemail != \' \' || signuppwd!=\' \') {" +
"\r\n                  $(\'#btnsave\').removeAttr(\"disabled\");\r\n                 \r\n  " +
"            }\r\n              \r\n\r\n          });\r\n   \r\n          $(document).ready" +
"(function () {\r\n              var loginemail = $(\'#loginemail\').val();\r\n        " +
"      var loginpwd = $(\'#loginpassword\').val();\r\n              var signupemail =" +
" $(\'#SignupEmail\').val();\r\n              var signuppwd = $(\'#SignupPassword\').va" +
"l();\r\n\r\n              if (loginemail != \'\' || loginpwd != \'\') {\r\n               " +
"   $(\'#btnSavelogin\').removeAttr(\"disabled\");\r\n\r\n              }\r\n              " +
"if (signupemail != \' \' || signuppwd != \' \') {\r\n                  $(\'#btnsave\').r" +
"emoveAttr(\"disabled\");\r\n                 \r\n              }\r\n             \r\n\r\n   " +
"           $(\'#loginemail\').removeClass(\'err-bor\');\r\n              $(\'#loginpass" +
"word\').removeClass(\'err-bor\');\r\n\r\n              $(\'#diverro1login\').css(\'display" +
"\', \'none\');\r\n              $(\'#diverrologin\').css(\"display\", \"none\");\r\n\r\n\r\n     " +
"         $(\'#loginemail\').keyup(function () {\r\n\r\n                  if ($(this).v" +
"al() != \'\' && $(\'#loginpassword\').val()!=\'\')\r\n                  {\r\n             " +
"         $(\'#btnSavelogin\').removeAttr(\"disabled\");\r\n\r\n                  } else " +
"{\r\n\r\n                      $(\'#btnSavelogin\').attr(\"disabled\", true);\r\n         " +
"         }\r\n\r\n              })\r\n              $(\'#loginpassword\').keyup(function" +
" () {\r\n                  if ($(this).val() != \'\' && $(\'#loginemail\').val()!=\'\')\r" +
"\n                  {\r\n\r\n                      $(\'#btnSavelogin\').removeAttr(\"dis" +
"abled\");\r\n\r\n                  } else {\r\n\r\n                      $(\'#btnSavelogin" +
"\').attr(\"disabled\", true);\r\n                  }\r\n\r\n              })\r\n\r\n\r\n       " +
"   });\r\n\r\n                function validationLogin()\r\n                {\r\n       " +
"             var msglogin = \"\";\r\n                    var Emaillogin = $(\"#logine" +
"mail\").val();\r\n\r\n                    var Passowrdlogin = $(\"#loginpassword\").val" +
"();\r\n                    if (!validateEmail(Emaillogin)) {\r\n                    " +
"    $(\'#loginemail\').focus();\r\n                        $(\'#loginemail\').addClass" +
"(\'err-bor\');\r\n                        msglogin += ajaxsetup(\'Login\', \'LoginEmail" +
"ValidationUI\');\r\n\r\n\r\n                    } else {\r\n\r\n                        msg" +
"login = \"\";\r\n                        $(\'#loginemail\').focus();\r\n                " +
"        $(\'#loginemail\').removeClass(\'err-bor\');\r\n                    }\r\n\r\n     " +
"               if (Passowrdlogin.length < 4) {\r\n                        $(\'#logi" +
"npassword\').focus();\r\n                        $(\'#loginpassword\').addClass(\'err-" +
"bor\');\r\n                        msglogin += \"<br />\" + ajaxsetup(\'Login\', \'Login" +
"PasswordValidationUI\');\r\n\r\n\r\n                    } else {\r\n                     " +
"   if (msglogin == \"\") {\r\n                            msglogin = \"\";\r\n          " +
"              }\r\n                        $(\'#loginpassword\').focus();\r\n         " +
"               $(\'#loginpassword\').removeClass(\'err-bor\');\r\n\r\n\r\n                " +
"    }\r\n                    return msglogin;\r\n                }\r\n                " +
"function ajaxsetup(strname, strFormTag)\r\n                {\r\n                    " +
"var msgnew = \"\";\r\n\r\n                    var request = $.ajax({\r\n                " +
"        url: \'");

            
            #line 708 "..\..\Views\Shared\_Layout.cshtml"
                         Write(Url.Action("Index", "ValidationMessage"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                        async: false,
                        data: { strFormName: strname, strFormTag: strFormTag },
                        type: 'Post'
                    });
                    request.done(function (msg) {
                        msgnew += msg;
                    });

                    request.fail(function (jqXHR, textStatus) {
                        msgnew += ""Some Error occur!!"";
                    });
                    return msgnew;
                }
                function validateEmail(sEmail) {
                    var filter = /^[\w\-\.\+]+\");

WriteLiteral("@[a-zA-Z0-9\\.\\-]+\\.[a-zA-z0-9]{2,4}$/;\r\n\r\n                    if (filter.test(sEm" +
"ail)) {\r\n\r\n                        return true;\r\n                    }\r\n        " +
"            else {\r\n\r\n\r\n                        return false;\r\n                 " +
"   }\r\n                }\r\n\r\n                $(\"#btnSavelogin\").click(function () " +
"{\r\n                    var msgloginn = validationLogin();\r\n\r\n                   " +
" var flag1login = true;\r\n                    if (msgloginn == \"\") {\r\n           " +
"             $(\'#diverrologin\').css(\"display\", \"none\");\r\n                       " +
" flag1 = true;\r\n                    }\r\n                    else {\r\n             " +
"           $(\'#diverro1login\').css(\'display\', \'none\');\r\n                        " +
"$(\'#dverrui\').html(msgloginn);\r\n                        $(\'#diverrologin\').css(\"" +
"display\", \"block\");\r\n\r\n                        return false;\r\n                  " +
"  }\r\n                    if (flag1login) {\r\n\r\n                        var flaglo" +
"gin = false;\r\n                        var Emaillogin = $(\"#loginemail\").val();\r\n" +
"                        var Emailpassword = $(\"#loginpassword\").val();\r\n\r\n\r\n    " +
"                    $.ajax({\r\n                            url: \"/Home/IsValidID\"" +
",\r\n                            data: { Email: Emaillogin, Password: Emailpasswor" +
"d },\r\n                            dataType: \"text\",\r\n                           " +
" type: \'Post\',\r\n                            success: function (data, textStatus," +
" xhr) {\r\n                              if (data != \'\') {\r\n                      " +
"              if (data ==\"NotFound\")\r\n                                    {\r\n   " +
"                                     $(\'#loginemail\').focus();\r\n                " +
"                        $(\'#loginemail\').addClass(\'err-bor\');\r\n\r\n               " +
"                         $(\'#diverrologin\').css(\"display\", \"none\");\r\n           " +
"                             $(\'#diverro1login\').css(\'display\', \'block\');\r\n     " +
"                                  var msg= ajaxsetup(\'Login\', \'LoginEmailNotExis" +
"tSy\');\r\n                                       $(\'#dverrsys\').html(msg);\r\n\r\n    " +
"                                    return false;\r\n\r\n                           " +
"         } else if (data == \"PasswordNotMatch\")\r\n                               " +
"     {\r\n                                        $(\'#loginemail\').focus();\r\n     " +
"                                   $(\'#loginemail\').addClass(\'err-bor\');\r\n      " +
"                                  $(\'#loginpassword\').addClass(\'err-bor\');\r\n\r\n  " +
"                                      $(\'#diverrologin\').css(\"display\", \"none\");" +
"\r\n                                        $(\'#diverro1login\').css(\'display\', \'bl" +
"ock\');\r\n                                        var msg = ajaxsetup(\'Login\', \'Lo" +
"ginPwdNotExistSy\');\r\n                                        $(\'#dverrsys\').html" +
"(msg);\r\n\r\n                                    }\r\n                               " +
"     else if (data == \"PasswordMatch\")\r\n                                    {\r\n " +
"                                       $(\'#formlogin\').submit();\r\n\r\n            " +
"                        }\r\n\r\n\r\n                                }\r\n              " +
"              },\r\n                            error: function (xhr, textStatus, " +
"errorThrown) {\r\n                                alert(\"Req \" + xhr + \" status \" " +
"+ textStatus + \"  Error \" + errorThrown);\r\n                            }\r\n      " +
"                  });\r\n\r\n\r\n\r\n                    }\r\n                });\r\n</scrip" +
"t>\r\n\r\n\r\n    ");

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(document).click(function () {\r\n        $(\'#diverro\').css(\'display\', \'non" +
"e\');\r\n        $(\'#diverro1\').css(\'display\', \'none\');\r\n\r\n\r\n        $(\"input\").rem" +
"oveClass(\'err-bor\');\r\n    });\r\n    $(\'#btndiverro\').click(function () {\r\n       " +
" $(\'#diverro\').css(\'display\', \'none\');\r\n        $(\'#diverro1\').css(\'display\', \'n" +
"one\');\r\n\r\n\r\n        $(\"input\").removeClass(\'err-bor\');\r\n    })\r\n    $(\'#btndiver" +
"ro1\').click(function () {\r\n        $(\'#diverro\').css(\'display\', \'none\');\r\n      " +
"  $(\'#diverro1\').css(\'display\', \'none\');\r\n\r\n\r\n        $(\"input\").removeClass(\'er" +
"r-bor\');\r\n    })\r\n    $(document).ready(function () {\r\n\r\n        $(\'#SignupEmail" +
"\').removeClass(\'err-bor\');\r\n        $(\'#SignupPassword\').removeClass(\'err-bor\');" +
"\r\n\r\n        $(\'#diverro1\').css(\'display\', \'none\');\r\n        $(\'#diverro\').css(\"d" +
"isplay\", \"none\");\r\n        $(\'#SignupEmail\').keyup(function () {\r\n\r\n            " +
"if ($(this).val() != \'\' && $(\'#SignupPassword\').val() != \'\') {\r\n                " +
"$(\'#btnsave\').removeAttr(\"disabled\");\r\n                \r\n            } else { \r\n" +
"                $(\'#btnsave\').attr(\"disabled\", true);\r\n            }\r\n          " +
"  if ($(this).val() == \'\' && $(\'#SignupPassword\').val() == \'\')\r\n            { $(" +
"\'#divsignupfrgt\').css(\'display\', \'none\'); }\r\n        })\r\n        $(\'#SignupPassw" +
"ord\').keyup(function () {\r\n            if ($(this).val() != \'\' && $(\'#SignupEmai" +
"l\').val() != \'\') {\r\n\r\n                $(\'#btnsave\').removeAttr(\"disabled\");\r\n   " +
"            \r\n            } else {\r\n              \r\n                $(\'#btnsave\'" +
").attr(\"disabled\", true);\r\n            }\r\n            if ($(this).val() == \'\' &&" +
" $(\'#SignupEmail\').val() == \'\')\r\n            { $(\'#divsignupfrgt\').css(\'display\'" +
", \'none\'); }\r\n        })\r\n    });\r\n\r\n    </script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n                function validation()\r\n                {\r\n                  " +
"  var msg = \"\";\r\n                    var Email = $(\"#SignupEmail\").val();\r\n\r\n   " +
"                 var Passowrdw = $(\"#SignupPassword\").val();\r\n\r\n                " +
"    if (!validateEmail(Email)) {\r\n                        $(\'#SignupEmail\').focu" +
"s();\r\n                        $(\'#SignupEmail\').addClass(\'err-bor\');\r\n          " +
"              \r\n                        msg += ajaxsetup(\'Signup\', \'SignupEmailV" +
"alidationUI\');\r\n                        \r\n\r\n                    } else {\r\n\r\n    " +
"                    msg = \"\";\r\n                        $(\'#SignupEmail\').focus()" +
";\r\n                        $(\'#SignupEmail\').removeClass(\'err-bor\');\r\n          " +
"          }\r\n                    //console.log(Passowrdw.length);\r\n             " +
"       if (Passowrdw.length < 4) {\r\n                        $(\'#SignupPassword\')" +
".focus();\r\n                        $(\'#SignupPassword\').addClass(\'err-bor\');\r\n  " +
"                      msg += \"</br>\" + ajaxsetup(\'Signup\', \'SignupPasswordValida" +
"tionUI\');\r\n                       \r\n\r\n                    } else {\r\n            " +
"            if (msg == \"\") {\r\n                            msg = \"\";\r\n           " +
"             }\r\n                        $(\'#SignupPassword\').focus();\r\n         " +
"               $(\'#SignupPassword\').removeClass(\'err-bor\');\r\n\r\n                 " +
"   }\r\n                    return msg;\r\n                }\r\n\r\n\r\n                $(" +
"\"#btnsave\").click(function (event) {\r\n\r\n                  var msg = validation()" +
";\r\n                    var flag1 = true;\r\n                    if (msg == \"\") {\r\n" +
"                        $(\'#diverro\').css(\"display\", \"none\");\r\n                 " +
"       flag1 = true;\r\n                    }\r\n                    else {\r\n       " +
"                 $(\'#diverro1\').css(\'display\', \'none\');\r\n                       " +
" $(\'#dverrsignui\').html(msg);\r\n                        $(\'#diverro\').css(\"displa" +
"y\", \"block\");\r\n\r\n                        return false;\r\n                    }\r\n " +
"                   if (flag1) {\r\n                        var flag = false;\r\n    " +
"                    var Emailsignin = $(\"#SignupEmail\").val();\r\n\r\n              " +
"          $.ajax({\r\n                            url: \"/Home/IsValid\",\r\n         " +
"                   data: \'Email=\'+Emailsignin,\r\n                            data" +
"Type: \"text\",\r\n                            success: function (data, textStatus, " +
"xhr) {\r\n\r\n                               if (data != \'\') {\r\n                    " +
"                if (data ==\"NotFound\")\r\n                                        " +
"        {\r\n                                                    flag = true;\r\n   " +
"                                                 $(\'#divsignupfrgt\').css(\'displa" +
"y\', \'none\');\r\n                                                    $(\'#form\').sub" +
"mit();\r\n\r\n                                                } else if (data == \"Fo" +
"und\")\r\n                                                {\r\n                      " +
"                              \r\n                                                " +
"    $(\'#SignupEmail\').focus();\r\n                                                " +
"    $(\'#SignupEmail\').addClass(\'err-bor\');\r\n                                    " +
"                $(\'#diverro\').css(\"display\", \"none\");\r\n                         " +
"                           $(\'#diverro1\').css(\'display\', \'block\');\r\n            " +
"                                        var msg = ajaxsetup(\'Signup\', \'SignupEma" +
"ilAlreadyExistSY\');\r\n                                                 \r\n        " +
"                                            $(\'#dverrsignsys\').html(msg);\r\n     " +
"                                               $(\'#divsignupfrgt\').css(\'display\'" +
", \'block\');\r\n                                                    flag = false;\r\n" +
"                                                    return false;\r\n             " +
"                                   }\r\n                                }\r\n       " +
"                     },\r\n                            error: function (xhr, textS" +
"tatus, errorThrown) {\r\n                                $(\'#diverro\').css(\"displa" +
"y\", \"none\");\r\n                                $(\'#diverro1\').css(\'display\', \'blo" +
"ck\');\r\n                                $(\'#dverrsignsys\').html(\"Some Problem in " +
"system contact your admin!!\");\r\n                            }\r\n                 " +
"       });\r\n                     \r\n\r\n\r\n                    }\r\n                })" +
";\r\n\r\n\r\n\r\n\r\n                $(\'.closefrgt\').click(function () {\r\n                " +
"    $(\'#divsignupfrgt\').css(\'display\', \'none\');\r\n\r\n                });\r\n\r\n\r\n\r\n  " +
"              function validateEmail(sEmail) {\r\n                    var filter =" +
" /^[\\w\\-\\.\\+]+\\");

WriteLiteral(@"@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/;

                    if (filter.test(sEmail)) {

                        return true;
                    }
                    else {


                        return false;
                    }
                }

             
                   
            

    </script>");

        }
    }
}
#pragma warning restore 1591
