#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EventCombo;
    
    #line 2 "..\..\Views\Shared\_signuppartial.cshtml"
    using EventCombo.Models;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Views\Shared\_signuppartial.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_signuppartial.cshtml")]
    public partial class _Views_Shared__signuppartial_cshtml : System.Web.Mvc.WebViewPage<LoginViewModel>
    {
        public _Views_Shared__signuppartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\_signuppartial.cshtml"
  
    ViewBag.Title = "Sign in";


            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n");

            
            #line 11 "..\..\Views\Shared\_signuppartial.cshtml"
 using (Html.BeginForm("Signup", "Home", FormMethod.Post, new { role = "form" ,id="form",@class= "form-horizontal acnt_form"}))
{
   
    if (ViewData["Message"] != null)
    {
            
            #line default
            #line hidden
WriteLiteral("<div");

WriteLiteral(" class=\"err_main\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"er_suc_main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"er_suc_img\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(">ViewData[\"Message\"] </div>\r\n    </div>\r\n    </div>\r\n");

            
            #line 21 "..\..\Views\Shared\_signuppartial.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"err_main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"er_UI_main alert-danger\"");

WriteLiteral(" id=\"diverro\"");

WriteLiteral(" style=\"display :none;width:100%\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"close closebtn\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btndiverro\"");

WriteLiteral(">&#215;</button>\r\n            <div");

WriteLiteral(" class=\"er_UI_img\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(" id=\"dverrsignui\"");

WriteLiteral(" >  </div>\r\n        </div>\r\n        </div>\r\n");

            
            #line 29 "..\..\Views\Shared\_signuppartial.cshtml"

 

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"err_main\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"er_UI_main alert-danger\"");

WriteLiteral(" id=\"diverro1\"");

WriteLiteral(" style=\"display :none;width:100%\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"close closebtn\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btndiverro1\"");

WriteLiteral(">&#215;</button>\r\n                <div");

WriteLiteral(" class=\"er_sys_img\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(" id=\"dverrsignsys\"");

WriteLiteral(">  </div>\r\n            </div>\r\n            </div>\r\n");

WriteLiteral("           <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-5 login_form_bot\"");

WriteLiteral(">\r\n                           \r\n");

WriteLiteral("                            ");

            
            #line 44 "..\..\Views\Shared\_signuppartial.cshtml"
                       Write(Html.TextBoxFor(m => m.Email, new { @maxlength = 256, @placeholder = "Email", @class = "form-control login_place", @id = "SignupEmail" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-5 login_form_bot\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 47 "..\..\Views\Shared\_signuppartial.cshtml"
                       Write(Html.PasswordFor(m => m.Password, new { @maxlength = 15, @placeholder = "Password", @class = "form-control login_place", @id = "SignupPassword" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                           \r\n                        </div>\r\n                  " +
"      <div");

WriteLiteral(" class=\"col-sm-2 login_form_bot\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"SignUp\"");

WriteLiteral(" class=\"btn btn-primary login_btn_sub\"");

WriteLiteral(" id=\"btnsave\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n            </div>\r\n");

            
            #line 57 "..\..\Views\Shared\_signuppartial.cshtml"

          



          



            

            }

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(document).click(function () {
        $('#diverro').css('display', 'none');
        $('#diverro1').css('display', 'none');


        $(""input"").removeClass('err-bor');
    });
    $('#btndiverro').click(function () {
        $('#diverro').css('display', 'none');
        $('#diverro1').css('display', 'none');


        $(""input"").removeClass('err-bor');
    })
    $('#btndiverro1').click(function () {
        $('#diverro').css('display', 'none');
        $('#diverro1').css('display', 'none');


        $(""input"").removeClass('err-bor');
    })
    $(document).ready(function () {

        $('#SignupEmail').removeClass('err-bor');
        $('#SignupPassword').removeClass('err-bor');
      
        $('#diverro1').css('display', 'none');
        $('#diverro').css(""display"", ""none"");
        $('#SignupEmail').keyup(function () {

            if ($(this).val() != '' && $('#SignupPassword').val() != '') {
                $('#btnsave').removeAttr(""disabled"");

            } else {

                $('#btnsave').attr(""disabled"", true);
            }

        })
        $('#SignupPassword').keyup(function () {
            if ($(this).val() != '' && $('#SignupEmail').val() != '') {

                $('#btnsave').removeAttr(""disabled"");

            } else {

                $('#btnsave').attr(""disabled"", true);
            }

        })
    });

</script>
            <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n             \r\n                function validation()\r\n                {\r\n     " +
"               var msg = \"\";\r\n                    var Email = $(\"#SignupEmail\")." +
"val();\r\n\r\n                    var Passowrdw = $(\"#SignupPassword\").val();\r\n\r\n   " +
"                 if (!validateEmail(Email)) {\r\n                        $(\'#Signu" +
"pEmail\').focus();\r\n                        $(\'#SignupEmail\').addClass(\'err-bor\')" +
";\r\n                        msg += \"Invalid Email!! </br>\"\r\n\r\n                   " +
" } else {\r\n\r\n                        msg = \"\";\r\n                        $(\'#Sign" +
"upEmail\').focus();\r\n                        $(\'#SignupEmail\').removeClass(\'err-b" +
"or\');\r\n                    }\r\n                    //console.log(Passowrdw.length" +
");\r\n                    if (Passowrdw.length < 4) {\r\n                        $(\'" +
"#SignupPassword\').focus();\r\n                        $(\'#SignupPassword\').addClas" +
"s(\'err-bor\');\r\n                        msg += \"Password Length can\'t be less tha" +
"n 4!! </br>\"\r\n\r\n                    } else {\r\n                        if (msg ==" +
" \"\") {\r\n                            msg = \"\";\r\n                        }\r\n      " +
"                  $(\'#SignupPassword\').focus();\r\n                        $(\'#Sig" +
"nupPassword\').removeClass(\'err-bor\');\r\n\r\n                    }\r\n                " +
"    return msg;\r\n                }\r\n          \r\n    \r\n                $(\"#btnsav" +
"e\").click(function (event) {\r\n                  \r\n                  var msg = va" +
"lidation();\r\n                    var flag1 = true;\r\n                    if (msg " +
"== \"\") {\r\n                        $(\'#diverro\').css(\"display\", \"none\");\r\n       " +
"                 flag1 = true;\r\n                    }\r\n                    else " +
"{\r\n                        $(\'#diverro1\').css(\'display\', \'none\');\r\n             " +
"           $(\'#dverrsignui\').html(msg);\r\n                        $(\'#diverro\').c" +
"ss(\"display\", \"block\");\r\n                       \r\n                        return" +
" false;\r\n                    }\r\n                    if (flag1) {\r\n              " +
"          var flag = false;\r\n                        var Emailsignin = $(\"#Signu" +
"pEmail\").val();\r\n                      \r\n                        $.ajax({\r\n     " +
"                       url: \"/Home/IsValid\",\r\n                            data: " +
"\'Email=\'+Emailsignin,\r\n                            dataType: \"text\",\r\n          " +
"                  success: function (data, textStatus, xhr) {\r\n                 " +
"             \r\n                               if (data != \'\') {\r\n               " +
"                     if (data ==\"NotFound\")\r\n                                   " +
"             {\r\n                                                    flag = true;" +
"\r\n\r\n                                                    $(\'#form\').submit();\r\n\r\n" +
"                                                } else if (data == \"Found\")\r\n   " +
"                                             {\r\n                                " +
"                    console.log(\'Enter\');\r\n                                     " +
"               $(\'#SignupEmail\').focus();\r\n                                     " +
"               $(\'#SignupEmail\').addClass(\'err-bor\');\r\n                         " +
"                           $(\'#diverro\').css(\"display\", \"none\");\r\n              " +
"                                      $(\'#diverro1\').css(\'display\', \'block\');\r\n " +
"                                                   $(\'#dverrsignsys\').html(\'Emai" +
"l Already Exist!!!\');\r\n                                                    flag " +
"= false;\r\n                                                    return false;\r\n   " +
"                                             }\r\n                                " +
"}\r\n                            },\r\n                            error: function (" +
"xhr, textStatus, errorThrown) {\r\n                                //alert(\"Req \" " +
"+ xhr + \" status \" + textStatus + \"  Error \" + errorThrown);\r\n                  " +
"          }\r\n                        });\r\n                        //alert(Email)" +
";\r\n                        //$.ajax({\r\n                        //    url: \'/Acco" +
"unt/IsValid\',\r\n                        //    type: \'Post\',\r\n                    " +
"    //    data: {\"Email\": Emailsignin},\r\n                        //    //cache: " +
"false,\r\n                        //    //contentType: \"text/plain\",\r\n            " +
"            //    dataType: \"text\",\r\n                        //    success: func" +
"tion (data) {\r\n                        //        alert(data);\r\n                 " +
"       //        console.log(data);\r\n                        //        if (data " +
"==\"NotFound\")\r\n                        //        {\r\n                        //  " +
"          flag = true;\r\n\r\n                        //            $(\'#form\').submi" +
"t();\r\n\r\n                        //        } else if (data == \"Found\")\r\n         " +
"               //        {\r\n                        //            console.log(\'E" +
"nter\');\r\n                        //            $(\'#SignupEmail\').focus();\r\n     " +
"                   //            $(\'#SignupEmail\').css(\"border\", \"red solid 1px\"" +
");\r\n                        //            $(\'#diverro\').css(\"display\", \"none\");\r" +
"\n                        //            $(\'#diverro1\').css(\'display\', \'block\');\r\n" +
"                        //            $(\'.er_suc\').html(\'Email Already Exist!!!\'" +
");\r\n                        //            flag = false;\r\n                       " +
" //            return false;\r\n                        //        }\r\n             " +
"                  \r\n                        //    },\r\n                        //" +
"    error: function (data1) {\r\n\r\n                        //        alert(\'error\'" +
");\r\n                        //    }\r\n                        //});\r\n            " +
"          \r\n                    \r\n                    }\r\n                });\r\n\r\n" +
"\r\n\r\n\r\n\r\n           \r\n\r\n             \r\n\r\n                function validateEmail(s" +
"Email) {\r\n                    var filter = /^[\\w\\-\\.\\+]+\\");

WriteLiteral(@"@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/;

                    if (filter.test(sEmail)) {

                        return true;
                    }
                    else {


                        return false;
                    }
                }

            </script>
");

        }
    }
}
#pragma warning restore 1591
