//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCombo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleAuthor
    {
        public long ArticleAuthorId { get; set; }
        public Nullable<long> ECImageId { get; set; }
        public string Name { get; set; }
        public string TwitterLink { get; set; }
    }
}
