//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCombo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventECImage
    {
        public long EventECImageId { get; set; }
        public long EventId { get; set; }
        public long ECImageId { get; set; }
    
        public virtual ECImage ECImage { get; set; }
        public virtual Event Event { get; set; }
    }
}
