//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCombo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTemplateQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTemplateQuestion()
        {
            this.OrderTemplateQuestionVariants = new HashSet<OrderTemplateQuestionVariant>();
            this.OrderTemplateQuestionTickets = new HashSet<OrderTemplateQuestionTicket>();
        }
    
        public long OrderTemplateQuestionId { get; set; }
        public long OrderTemplateId { get; set; }
        public long QuestionTypeId { get; set; }
        public bool Include { get; set; }
        public bool Require { get; set; }
        public string QuestionText { get; set; }
        public int SortNum { get; set; }
        public long ControlTypeId { get; set; }
        public bool ShowForTickets { get; set; }
        public bool LimitQuantity { get; set; }
        public bool ShowAnswer { get; set; }
        public bool EnableSubquestions { get; set; }
        public long ParentId { get; set; }
    
        public virtual QuestionType QuestionType { get; set; }
        public virtual OrderTemplate OrderTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTemplateQuestionVariant> OrderTemplateQuestionVariants { get; set; }
        public virtual ControlType ControlType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTemplateQuestionTicket> OrderTemplateQuestionTickets { get; set; }
    }
}
