//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCombo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publish_Event_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publish_Event_Detail()
        {
            this.Ticket_Quantity_Detail = new HashSet<Ticket_Quantity_Detail>();
        }
    
        public long PE_Id { get; set; }
        public Nullable<long> PE_Event_Id { get; set; }
        public string PE_Address_Ids { get; set; }
        public Nullable<long> PE_MultipleVenue_id { get; set; }
        public Nullable<long> PE_SingleVenue_Id { get; set; }
        public string PE_Tickets_Ids { get; set; }
        public string PE_Scheduled_Date { get; set; }
        public string PE_Start_Time { get; set; }
        public string PE_End_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Quantity_Detail> Ticket_Quantity_Detail { get; set; }
        public virtual EventVenue EventVenue { get; set; }
        public virtual MultipleEvent MultipleEvent { get; set; }
    }
}
