//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCombo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Locked_Detail
    {
        public long TLD_Id { get; set; }
        public string TLD_User_Id { get; set; }
        public Nullable<long> TLD_Locked_Qty { get; set; }
        public Nullable<long> TLD_Event_Id { get; set; }
        public Nullable<long> TLD_TQD_Id { get; set; }
        public Nullable<System.DateTime> Locktime { get; set; }
        public string TLD_GUID { get; set; }
        public Nullable<decimal> TLD_Donate { get; set; }
        public Nullable<decimal> TicketAmount { get; set; }
        public Nullable<int> TLD_PromoCodeId { get; set; }

        public Nullable<decimal> TLD_PromoCodeAmount { get; set; }

    }
}
