//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCombo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketBack2015
    {
        public long T_Id { get; set; }
        public Nullable<long> E_Id { get; set; }
        public string T_name { get; set; }
        public long Qty_Available { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> TicketTypeID { get; set; }
        public string T_Sold { get; set; }
        public string Registration_Recorded { get; set; }
        public string T_Desc { get; set; }
        public string Show_T_Desc { get; set; }
        public string Fees_Type { get; set; }
        public Nullable<System.DateTime> Sale_Start_Date { get; set; }
        public string Sale_Start_Time { get; set; }
        public Nullable<System.DateTime> Sale_End_Date { get; set; }
        public string Sale_End_Time { get; set; }
        public string Hide_Ticket { get; set; }
        public string Auto_Hide_Sche { get; set; }
        public Nullable<System.DateTime> Hide_Untill_Date { get; set; }
        public string Hide_Untill_Time { get; set; }
        public Nullable<System.DateTime> Hide_After_Date { get; set; }
        public string Hide_After_Time { get; set; }
        public Nullable<decimal> Min_T_Qty { get; set; }
        public Nullable<decimal> Max_T_Qty { get; set; }
        public string T_Disable { get; set; }
        public string T_Mark_SoldOut { get; set; }
        public Nullable<long> T_Sold_Qty { get; set; }
        public Nullable<byte> T_order { get; set; }
        public Nullable<decimal> EC_Fee { get; set; }
        public Nullable<decimal> Customer_Fee { get; set; }
        public string T_Displayremaining { get; set; }
        public string T_AutoSechduleType { get; set; }
        public Nullable<decimal> Additional_Fee { get; set; }
        public Nullable<decimal> T_Discount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    }
}
