//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCombo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Users
    {
        public Nullable<long> Sno { get; set; }
        public string EMail { get; set; }
        public string Id { get; set; }
        public string Organiser { get; set; }
        public string Merchant { get; set; }
        public string UserStatus { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Online { get; set; }
        public string State { get; set; }
        public string Ipcountry { get; set; }
        public string IpState { get; set; }
        public string Ipcity { get; set; }
        public string OrganiserId { get; set; }
        public string MerchantId { get; set; }
        public string UserStatusId { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> EventCount { get; set; }
        public Nullable<long> TicketPurchased { get; set; }
        public string RoleType { get; set; }
        public int deals { get; set; }
        public int dealpurchased { get; set; }
    }
}
