#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 2 "..\..\Views\Account\MyAccount.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EventCombo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/MyAccount.cshtml")]
    public partial class _Views_Account_MyAccount_cshtml : System.Web.Mvc.WebViewPage<EventCombo.Models.myAccount>
    {
        public _Views_Account_MyAccount_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\MyAccount.cshtml"
  
    ViewBag.Title = "MyAccount";
    Layout = "~/Views/Shared/_AccountLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 163), Tuple.Create("\"", 202)
, Tuple.Create(Tuple.Create("", 170), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Filer/jquery.filer.css")
, 170), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 232), Tuple.Create("\"", 289)
, Tuple.Create(Tuple.Create("", 239), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Filer/jquery.filer-dragdropbox-theme.css")
, 239), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 319), Tuple.Create("\"", 356)
, Tuple.Create(Tuple.Create("", 325), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/filer/jquery.filer.js")
, 325), false)
);

WriteLiteral(@"></script>

<style>
.jFiler-input-dragDrop{width:200px; height:auto; padding:0px; }
.jFiler-item-thumb-image{ }
.jFiler-item-thumb-image img{ width:100%; height:150px; }
.jFiler-item-list{ margin:0px;}
.jFiler-input-dragDrop .jFiler-input-icon{ margin-top:0px; height: 150px;}
.jFiler-item .jFiler-item-container{ margin:0px; padding:0px; }
.jFiler-item .jFiler-item-container .jFiler-item-assets{ margin-top:0px;}
.jFiler-item .jFiler-item-container .jFiler-item-assets .jFiler-jProgressBar{ width:226px;  margin-left:0px; }
.can_btn i{ font-size:25px;}
.can_btn{ padding:0px;}
.jFiler-input-text{ margin-bottom:5px;}
.jFiler-input-icon i{position: relative;
    top: 35px;}
.coun_lef{ color:#000; margin-top:5px;}

   
</style>

");

            
            #line 32 "..\..\Views\Account\MyAccount.cshtml"
  Html.EnableClientValidation();
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 33 "..\..\Views\Account\MyAccount.cshtml"
  Html.EnableUnobtrusiveJavaScript();
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n    <h3");

WriteLiteral(" class=\"acnt_title\"");

WriteLiteral(">ACCOUNT</h3>\r\n    <p");

WriteLiteral(" class=\"p_info\"");

WriteLiteral(">Personal Information</p>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 40 "..\..\Views\Account\MyAccount.cshtml"
 using (Html.BeginForm("MyAccount", "Account", FormMethod.Post, new { role = "form", @class = "form-horizontal",autocomplete="off" }))
{
    
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Account\MyAccount.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Account\MyAccount.cshtml"
                            
    if (ViewData["Message"] != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-10 mb10 col-xs-12\"");

WriteLiteral(" id=\"divaccsuc\"");

WriteLiteral(" >\r\n            <div");

WriteLiteral(" class=\"er_suc_main \"");

WriteLiteral(" >\r\n            \r\n                <div");

WriteLiteral(" class=\"er_suc_img\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(">");

            
            #line 49 "..\..\Views\Account\MyAccount.cshtml"
                               Write(ViewData["Message"]);

            
            #line default
            #line hidden
WriteLiteral(" </div>\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btndivaccsuc\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(">&#215;</button>\r\n            </div>\r\n        </div>\r\n");

            
            #line 53 "..\..\Views\Account\MyAccount.cshtml"
    }
    if (!ViewData.ModelState.IsValid)
    {


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-10 mb10 col-xs-12\"");

WriteLiteral(" id=\"diverro1acc\"");

WriteLiteral(" >\r\n            <div");

WriteLiteral(" class=\"er_UI_main\"");

WriteLiteral(" >\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"er_sys_img\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(" id=\"erraccsucc\"");

WriteLiteral(">");

            
            #line 62 "..\..\Views\Account\MyAccount.cshtml"
                                               Write(Html.ValidationMessage("Error"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btndiverro1acc\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(">&#215;</button>\r\n            </div>\r\n\r\n         </div>\r\n");

            
            #line 67 "..\..\Views\Account\MyAccount.cshtml"
            }

            
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Account\MyAccount.cshtml"
                   


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-10 mb10 col-xs-12\"");

WriteLiteral("  id=\"diverroacc\"");

WriteLiteral(" style=\"display :none;\"");

WriteLiteral(" >\r\n            <div");

WriteLiteral(" class=\"er_UI_main\"");

WriteLiteral(">\r\n\r\n                ");

WriteLiteral("\r\n\r\n                <div");

WriteLiteral(" class=\"er_UI_img\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"er_suc\"");

WriteLiteral(" id=\"erraccmsg\"");

WriteLiteral(">  </div>\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btndiverroacc\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(">&#215;</button>\r\n                ");

WriteLiteral("\r\n\r\n\r\n            </div>\r\n\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n            <div>\r\n\r\n                <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" name=\"image\"");

WriteLiteral(" id=\"input2\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n");

            
            #line 98 "..\..\Views\Account\MyAccount.cshtml"



            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label \"");

WriteLiteral(">Name</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 106 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.Firstname, new { @maxlength = 35, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini\"");

WriteLiteral(">First Name</small>\r\n                        </div>\r\n                        <div" +
"");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 110 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.Lastname, new { @maxlength = 35, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini\"");

WriteLiteral(">Last Name</small>\r\n                        </div>\r\n\r\n                    </div>\r" +
"\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Date of Birth</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-4 add_form_bot mb0 dropheight\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 123 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.DropDownList("month", Enumerable.Range(1, 12).Select(i => new SelectListItem
                           {
                               Value = i.ToString(),
                               Text = Thread.CurrentThread.CurrentUICulture.DateTimeFormat.GetMonthName(i),
                               Selected = i == Model.month

                           }), new { @class = "form-control selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-4 add_form_bot mb0 dropheight\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 133 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.DropDownList("day", Enumerable.Range(1, 31).Select(i => new SelectListItem
                           {
                               Value = i.ToString(),
                               Text = i.ToString(),
                               Selected = i == Model.day

                           }), new { @class = "form-control selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-4 add_form_bot mb0 dropheight\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 142 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.DropDownList("year", Enumerable.Range(1980, 36).Select(i => new SelectListItem
                           {
                               Value = i.ToString(),
                               Text = i.ToString(),
                               Selected = i == Model.year

                           }), new { @class = "form-control selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Gender</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 add_form_bot mb0 dropheight\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 160 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.DropDownList("Gender", new List<SelectListItem>{
        new SelectListItem{ Text="Male", Value="Male"},
        new SelectListItem{ Text="Female", Value="Female"}
        }, "--- Select ---", new { @class = "form-control selectpicker" }
        ));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Address</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 add_form_bot\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 175 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.StreetAddress1, new { @maxlength = 256, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini\"");

WriteLiteral(">Street Address</small>\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini pull-right coun_lef\"");

WriteLiteral(" id=\"cntstreetadd1\"");

WriteLiteral(">Count Left 256</small>\r\n                        </div>\r\n                        " +
"<div");

WriteLiteral(" class=\"col-xs-12 add_form_bot\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 180 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.StreeAddress2, new { @maxlength = 256, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini\"");

WriteLiteral(">Street Address 2</small>\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini pull-right coun_lef\"");

WriteLiteral(" id=\"cntstreetadd2\"");

WriteLiteral(">Count Left 256</small>\r\n                        </div>\r\n                    </di" +
"v>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6 add_form_bot\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 187 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.City, new { @maxlength = 256, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini\"");

WriteLiteral(">City</small>\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini pull-right coun_lef\"");

WriteLiteral(" id=\"cntcityadd1\"");

WriteLiteral(">Count Left 256</small>\r\n                        </div>\r\n                        " +
"<div");

WriteLiteral(" class=\"col-xs-6 add_form_bot\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 193 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.State, new { @maxlength = 256, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini\"");

WriteLiteral(">State</small>\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini pull-right coun_lef\"");

WriteLiteral(" id=\"cntcitystate\"");

WriteLiteral(">Count Left 256</small>\r\n                        </div>\r\n\r\n                    </" +
"div>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 201 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.Zip, new { @maxlength = 5, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini\"");

WriteLiteral(">Zip</small>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-6 add_form_bot mb0 dropheight\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 205 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.DropDownList("Country", ViewBag.Countries as List<SelectListItem>, new { @class = "form-control selectpicker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <small");

WriteLiteral(" class=\"acnt_form_name_mini\"");

WriteLiteral(">Country</small>\r\n                        </div>\r\n\r\n                    </div>\r\n " +
"               </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Home Number</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 218 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.MainPhone, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Cellular Number</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 228 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.SecondPhone, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Work Number</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-6 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 238 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.WorkPhone, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Email</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 248 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.HiddenFor(m => m.PreviousEmail, new { id = "hdEmail" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 249 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control", @maxlength = 256 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">E-mail Verification</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 259 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.ConfirmEmail, new { @class = "form-control", @maxlength = 256 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Website</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 269 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.TextBoxFor(m => m.WebsiteURL, new { @class = "form-control", @maxlength = 256 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Current Password</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 279 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.PasswordFor(m => m.Password, new { @class = "form-control", @maxlength = 15 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">New Password</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 289 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.PasswordFor(m => m.NewPassword, new { @class = "form-control", @maxlength = 15 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-md-3 control-label acnt_form_label\"");

WriteLiteral(">Confirm New Password</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12 add_form_bot mb0\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 299 "..\..\Views\Account\MyAccount.cshtml"
                       Write(Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @maxlength = 15 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-info col-md-offset-3 acnt_btn mb10\"");

WriteLiteral(" value=\"Save\"");

WriteLiteral(" id=\"btnsave\"");

WriteLiteral(" />\r\n");

WriteLiteral("            ");

            
            #line 305 "..\..\Views\Account\MyAccount.cshtml"
       Write(Html.HiddenFor(m => m.ImagePresent));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 306 "..\..\Views\Account\MyAccount.cshtml"
       Write(Html.HiddenFor(m => m.userimage));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <input");

WriteLiteral(" id=\"image_count\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" />\r\n\r\n        </div>\r\n");

            
            #line 310 "..\..\Views\Account\MyAccount.cshtml"

        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" id=\"imageeror\"");

WriteLiteral(" />\r\n\r\n\r\n\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n            $(document).ready(function () {\r\n                $(\'#mgacnt\').cl" +
"ick();\r\n                $(\'#dvacmang\').addClass(\"active\");\r\n                $(\'#" +
"dvacmang b\').addClass(\'opened new-opend\');\r\n\r\n                $(\'#dvacmang\').cli" +
"ck(function (e) {\r\n\r\n                    var $dvEle = $(\'#dvacmang b\');\r\n       " +
"             var vclassname = $dvEle.attr(\'class\');\r\n                    if ($dv" +
"Ele.hasClass(\"new-opend\")) {\r\n                        $dvEle.removeClass(\'opened" +
" new-opend\').addClass(\'closed\');\r\n                    }\r\n                    els" +
"e {\r\n                        $dvEle.addClass(\'opened new-opend\');\r\n             " +
"       }\r\n                });\r\n            });\r\n\r\n\r\n            $(document).clic" +
"k(function () {\r\n                $(\'#diverro1acc\').css(\'display\', \'none\');\r\n    " +
"            $(\'#diverroacc\').css(\'display\', \'none\');\r\n                $(\'#divacc" +
"suc\').css(\'display\', \'none\');\r\n                $(\"input\").removeClass(\'err-bor\')" +
";\r\n                $(\"#month\").removeClass(\'err-bor\');\r\n                $(\"#day\"" +
").removeClass(\'err-bor\');\r\n                $(\"#year\").removeClass(\'err-bor\');\r\n " +
"           });\r\n            $(\'#btndivaccsuc\').click(function () {\r\n            " +
"    $(\'#diverro1acc\').css(\'display\', \'none\');\r\n                $(\'#diverroacc\')." +
"css(\'display\', \'none\');\r\n                $(\'#divaccsuc\').css(\'display\', \'none\');" +
"\r\n                $(\"input\").removeClass(\'err-bor\');\r\n                $(\"#month\"" +
").removeClass(\'err-bor\');\r\n                $(\"#day\").removeClass(\'err-bor\');\r\n  " +
"              $(\"#year\").removeClass(\'err-bor\');\r\n\r\n            })\r\n            " +
"$(\'#btndiverro1acc\').click(function () {\r\n                $(\'#diverro1acc\').css(" +
"\'display\', \'none\');\r\n                $(\'#diverroacc\').css(\'display\', \'none\');\r\n " +
"               $(\"input\").removeClass(\'err-bor\');\r\n                $(\"#month\").r" +
"emoveClass(\'err-bor\');\r\n                $(\"#day\").removeClass(\'err-bor\');\r\n     " +
"           $(\"#year\").removeClass(\'err-bor\');\r\n\r\n            })\r\n            $(\'" +
"#btndiverroacc\').click(function () {\r\n                $(\"#imageeror\").val(\'0\');\r" +
"\n                $(\'#diverro1acc\').css(\'display\', \'none\');\r\n                $(\'#" +
"diverroacc\').css(\'display\', \'none\');\r\n                $(\"input\").removeClass(\'er" +
"r-bor\');\r\n                $(\"#month\").removeClass(\'err-bor\');\r\n                $" +
"(\"#day\").removeClass(\'err-bor\');\r\n                $(\"#year\").removeClass(\'err-bo" +
"r\');\r\n\r\n\r\n            })\r\n\r\n            $(window).load(function () {\r\n          " +
"      var cntstreet2 = 256 - $(\"#StreeAddress2\").val().length;\r\n                " +
"var cntstreet2 = 256 - $(\"#StreetAddress1\").val().length;\r\n                var c" +
"ntcity = 256 - $(\"#City\").val().length;\r\n                var cntstate = 256 - $(" +
"\"#State\").val().length;\r\n\r\n                $(\'#cntstreetadd2\').html(\"Count left " +
" \" + cntstreet2);\r\n                $(\'#cntstreetadd1\').html(\"Count left  \" + cnt" +
"street2);\r\n                $(\'#cntcityadd1\').html(\"Count left  \" + cntcity);\r\n  " +
"              $(\'#cntcitystate\').html(\"Count left  \" + cntstate);\r\n            }" +
");\r\n\r\n            $(\"#StreeAddress2\").keyup(function () {\r\n                var c" +
"s = $(this).val().length;\r\n                var left = 256 - cs;\r\n\r\n             " +
"   $(\'#cntstreetadd2\').html(\"Count left  \" + left);\r\n            });\r\n          " +
"  $(\"#StreetAddress1\").keyup(function () {\r\n                var cs = $(this).val" +
"().length;\r\n                var left = 256 - cs;\r\n\r\n                $(\'#cntstree" +
"tadd1\').html(\"Count left  \" + left);\r\n            });\r\n            $(\"#City\").ke" +
"yup(function () {\r\n                var cs = $(this).val().length;\r\n             " +
"   var left = 256 - cs;\r\n\r\n                $(\'#cntcityadd1\').html(\"Count left  \"" +
" + left);\r\n            });\r\n            $(\"#State\").keyup(function () {\r\n       " +
"         var cs = $(this).val().length;\r\n                var left = 256 - cs;\r\n\r" +
"\n                $(\'#cntcitystate\').html(\"Count left  \" + left);\r\n            })" +
";\r\n            $(\"#Country\").change(function () {\r\n                $(\"#Zip\").val" +
"(\"\");\r\n                $(\"#State\").val(\"\");\r\n                $(\"#City\").val(\"\");" +
"\r\n\r\n\r\n            });\r\n            jQuery(function ($) {\r\n                $(\"#Ma" +
"inPhone\").mask(\"999-999-9999\");\r\n                $(\"#SecondPhone\").mask(\"999-999" +
"-9999\");\r\n                $(\"#WorkPhone\").mask(\"999-999-9999\");\r\n\r\n            }" +
");\r\n            var Model = \"");

            
            #line 429 "..\..\Views\Account\MyAccount.cshtml"
                    Write(Html.Raw(Model.editsave));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n            var files1 = \'");

            
            #line 431 "..\..\Views\Account\MyAccount.cshtml"
                      Write(MvcHtmlString.Create(Json.Encode(ViewData["results"])));

            
            #line default
            #line hidden
WriteLiteral(@"';

            $(document).ready(function () {
                
                //$('#WebsiteURL').bind('keypress', function (event) {
                //    var regex = new RegExp(""^[a-zA-Z0-9]+$"");
                //    var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
                //    if (!regex.test(key)) {
                //        event.preventDefault();
                //        return false;
                //    }
                //});

                console.log(Model);
                var userProfileImage = """);

            
            #line 445 "..\..\Views\Account\MyAccount.cshtml"
                                   Write(Html.Raw(Model.UserProfileImage));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                var modelcontent = \"");

            
            #line 446 "..\..\Views\Account\MyAccount.cshtml"
                               Write(Html.Raw(Model.contentype));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                if (Model == \"Save\") {\r\n\r\n                } else {\r\n         " +
"           var imgdata = userProfileImage + \'¶\' + modelcontent;\r\n               " +
" }\r\n\r\n                console.log(imgdata);\r\n                //$(\'#WebsiteURL\')." +
"bind(\'cut copy paste\', function (event) {\r\n                //    event.preventDe" +
"fault();\r\n                //    return false;\r\n                //});\r\n\r\n\r\n      " +
"          if (Model == \"Save\") {\r\n                    $(\'#input2\').filer({\r\n    " +
"                    limit: \'1\',\r\n                        maxSize: \'2\',\r\n        " +
"                extensions: [\'jpg\', \'jpeg\', \'png\'],\r\n                        cha" +
"ngeInput: \'<div class=\"jFiler-input-dragDrop\" id=\"drag-drop\"><div class=\"jFiler-" +
"input-inner\"><div class=\"jFiler-input-icon\"><i class=\"icon-jfi-cloud-up-o\"></i><" +
"/div><div class=\"jFiler-input-text\"><h3>Drag  photo or normal upload</h3> </div>" +
"</div></div>\',\r\n                        showThumbs: true,\r\n                     " +
"   appendTo: \"#drag-drop\",\r\n                        theme: \"dragdropbox\",\r\n     " +
"                   onChange: false,\r\n                        templates: {\r\n     " +
"                       box: \'<ul class=\"jFiler-item-list profile-views clearfix\"" +
"></ul>\',\r\n                            item: \'<li class=\"jFiler-item\">\\\r\n        " +
"                            <div class=\"\">\\\r\n                                   " +
"         {{fi-image}}\\\r\n                                             <div class=" +
"\"jFiler-item-container\">\\\r\n                                <div class=\"jFiler-it" +
"em-inner\">\\\r\n                                     <div class=\"jFiler-item-assets" +
" jFiler-row\">\\\r\n                                        <ul class=\"list-inline p" +
"ull-left\">\\\r\n                                            <li>{{fi-progressBar}}<" +
"/li>\\\r\n                                        </ul>\\\r\n                         " +
"           </div>\\\r\n                                    </div>\\\r\n               " +
"             </div>\\\r\n                                            <span></span>\\" +
"\r\n                                             <button class=\"btn  jFiler-item-t" +
"rash-action can_btn\" type=\"button\">\\\r\n                                          " +
"      <i class=\"glyphicon glyphicon-remove-circle\"></i>\\\r\n                      " +
"                       </button>\\\r\n                                       </div>" +
"\\\r\n                        </li>\',\r\n                            itemAppend: \'<li" +
" class=\"jFiler-item\">\\\r\n                                    <div class=\"\">\\\r\n   " +
"                                         {{fi-image}}\\\r\n                        " +
"                     <button class=\"btn  jFiler-item-trash-action can_btn\" type=" +
"\"button\">\\\r\n                                                <i class=\"glyphicon " +
"glyphicon-remove-circle\"></i>\\\r\n                                             </b" +
"utton>\\\r\n                                       </div>\\\r\n                       " +
" </li>\',\r\n\r\n\r\n                            progressBar: \'<div class=\"bar\"></div>\'" +
",\r\n                            itemAppendToEnd: true,\r\n                         " +
"   removeConfirmation: false,\r\n                            _selectors: {\r\n      " +
"                          list: \'.jFiler-item-list\',\r\n                          " +
"      item: \'.jFiler-item\',\r\n                                progressBar: \'.bar\'" +
",\r\n                                remove: \'.jFiler-item-trash-action\',\r\n       " +
"                     }\r\n                        },\r\n                        uplo" +
"adFile: {\r\n                            url: \"/Account/SaveUploadedFile\",\r\n      " +
"                      data: {},\r\n                            type: \'POST\',\r\n    " +
"                        enctype: \'multipart/form-data\',\r\n                       " +
"     beforeSend: function () { },\r\n                            success: function" +
" (data, el) {\r\n\r\n                                var parent = el.find(\".jFiler-j" +
"ProgressBar\").parent();\r\n                                el.find(\".jFiler-jProgr" +
"essBar\").fadeOut(\"slow\", function () {\r\n                                    $(\"<" +
"div class=\\\"jFiler-item-others text-success\\\"><i class=\\\"icon-jfi-check-circle\\\"" +
"></i> Success</div>\").hide().appendTo(parent).fadeIn(\"slow\").remove();\r\n        " +
"                        });\r\n                                var image_count = $" +
"(\"#image_count\").val();\r\n                                var imagejson = jQuery." +
"parseJSON(JSON.stringify(data));\r\n                                var imgdata = " +
"imagejson.image_name + \'¶\' + imagejson.image_type;\r\n                            " +
"    //$(\"#image_count\").val(el[0].jfiler_id)\r\n                                $(" +
"\'#userimage\').val(imgdata);\r\n                                //$(\'<input>\').attr" +
"({\r\n                                //    type: \'hidden\',\r\n                     " +
"           //    id: \'image_hidden_\' + el[0].jfiler_id,\r\n                       " +
"         //    name: \'Eventpicture[\' + imgdata + \']\',\r\n                         " +
"       //    value: imgdata\r\n                                //}).appendTo(\'form" +
"\');\r\n\r\n                                $(\'#ImagePresent\').val(\"Yes\");\r\n\r\n       " +
"                         if ($.trim(image_count) == \'\') {\r\n                     " +
"               $(\"#image_count\").val(\'1\');\r\n                                } el" +
"se {\r\n                                    image_count = parseInt(image_count) + " +
"1;\r\n                                    $(\"#image_count\").val(image_count);\r\n   " +
"                             }\r\n\r\n                            },\r\n              " +
"              error: function (el) {\r\n\r\n                                //var pa" +
"rent = el.find(\".jFiler-jProgressBar\").parent();\r\n                              " +
"  //el.find(\".jFiler-jProgressBar\").fadeOut(\"slow\", function(){\r\n               " +
"                 //    $(\"<div class=\\\"jFiler-item-others text-error\\\"><i class=" +
"\\\"icon-jfi-minus-circle\\\"></i> Error</div>\").hide().appendTo(parent).fadeIn(\"slo" +
"w\");\r\n                                //});\r\n                            },\r\n   " +
"                         statusCode: {},\r\n                            onProgress" +
": function () { },\r\n                        },\r\n                        dragDrop" +
": {\r\n                            dragEnter: function () { },\r\n                  " +
"          dragLeave: function () { },\r\n                            drop: functio" +
"n () { },\r\n                        },\r\n                        addMore: false,\r\n" +
"                        clipBoardPaste: true,\r\n                        excludeNa" +
"me: null,\r\n                        beforeShow: function () { $(\".jFiler-input-in" +
"ner\").hide(); return true },\r\n                        onSelect: function () { $(" +
"\".jFiler-input-inner\").hide(); },\r\n                        afterShow: function (" +
") { $(\".jFiler-input-inner\").hide(); $(\".fi-progressBar\").hide(); },\r\n          " +
"              onRemove: function (el) {\r\n                            var image_c" +
"ount = $(\"#image_count\").val();\r\n                            image_count = parse" +
"Int(image_count) - 1;\r\n                            var id_div = el[0].jfiler_id;" +
"\r\n                            var hidden_image_element = \'image_hidden_\' + id_di" +
"v;\r\n\r\n                            $(\'#userimage\').val(\'\');\r\n                    " +
"        $(\'#input2\').click(function (e) {\r\n                                e.pre" +
"ventDefault();\r\n\r\n                            })\r\n                            $(" +
"\'#ImagePresent\').val(\"NO\");\r\n                        },\r\n                       " +
" onEmpty: function (el) {\r\n                            if ($(\"#imageeror\").val()" +
" == 0) {\r\n                                if ($(\".jFiler-items\").length == 1) { " +
"setTimeout(function () { $(\".jFiler-input-inner\").css(\'display\', \'block\'); $(\'#i" +
"nput2\').unbind(\'click\'); }, 200); };\r\n                            }\r\n           " +
"             },\r\n                        captions: {\r\n                          " +
"  button: \"Choose Files\",\r\n                            feedback: \"Choose files T" +
"o Upload\",\r\n                            feedback2: \"files were chosen\",\r\n       " +
"                     drop: \"Drop file here to Upload\",\r\n                        " +
"    removeConfirmation: \"Are you sure you want to remove this file?\",\r\n         " +
"                   errors: {\r\n                                filesLimit: ajaxse" +
"tup(\'MyAccount\', \'MyAccountImageCountValidationUI\'),\r\n                          " +
"      filesType: ajaxsetup(\'MyAccount\', \'MyAccountImagestypeValidationUI\'),\r\n   " +
"                             filesSize: ajaxsetup(\'MyAccount\', \'MyAccountImagesi" +
"zeValidationUI\'),\r\n                                filesSizeAll: ajaxsetup(\'MyAc" +
"count\', \'MyAccountImagesizeValidationUI\')\r\n                            }\r\n      " +
"                  }\r\n\r\n                    });\r\n                }\r\n             " +
"   else if (Model == \"Edit\") {\r\n                    $(\"#image_count\").val(\"1\");\r" +
"\n                    ");

WriteLiteral("\r\n\r\n                    $(\'#userimage\').val(imgdata);\r\n                    $(\'#in" +
"put2\').filer({\r\n                        limit: \'1\',\r\n                        max" +
"Size: \'2\',\r\n                        extensions: [\'jpg\', \'jpeg\', \'png\'],\r\n       " +
"                 changeInput: \'<div class=\"jFiler-input-dragDrop\" id=\"drag-drop\"" +
"><div class=\"jFiler-input-inner\"><div class=\"jFiler-input-icon\"><i class=\"icon-j" +
"fi-cloud-up-o\"></i></div><div class=\"jFiler-input-text\"><h3>Drag  photo or norma" +
"l upload</h3> </div></div></div>\',\r\n                        showThumbs: true,\r\n " +
"                       appendTo: \"#drag-drop\",\r\n                        theme: \"" +
"dragdropbox\",\r\n                        onChange: false,\r\n                       " +
" templates: {\r\n                            box: \'<ul class=\"jFiler-item-list pro" +
"file-views clearfix\"></ul>\',\r\n                            item: \'<li class=\"jFil" +
"er-item\">\\\r\n                                    <div class=\"\">\\\r\n               " +
"                             {{fi-image}}\\\r\n                                    " +
"         <div class=\"jFiler-item-container\">\\\r\n                                <" +
"div class=\"jFiler-item-inner\">\\\r\n                                     <div class" +
"=\"jFiler-item-assets jFiler-row\">\\\r\n                                        <ul " +
"class=\"list-inline pull-left\">\\\r\n                                            <li" +
">{{fi-progressBar}}</li>\\\r\n                                        </ul>\\\r\n     " +
"                               </div>\\\r\n                                    </di" +
"v>\\\r\n                            </div>\\\r\n                                      " +
"      <span></span>\\\r\n                                             <button class" +
"=\"btn  jFiler-item-trash-action can_btn\" type=\"button\">\\\r\n                      " +
"                          <i class=\"glyphicon glyphicon-remove-circle\"></i>\\\r\n  " +
"                                           </button>\\\r\n                         " +
"              </div>\\\r\n                        </li>\',\r\n                        " +
"    itemAppend: \'<li class=\"jFiler-item\">\\\r\n                                    " +
"<div class=\"\">\\\r\n                                            {{fi-image}}\\\r\n    " +
"                                         <button class=\"btn  jFiler-item-trash-a" +
"ction can_btn\" type=\"button\">\\\r\n                                                " +
"<i class=\"glyphicon glyphicon-remove-circle\"></i>\\\r\n                            " +
"                 </button>\\\r\n                                       </div>\\\r\n   " +
"                     </li>\',\r\n\r\n\r\n                            progressBar: \'<div" +
" class=\"bar\"></div>\',\r\n                            itemAppendToEnd: false,\r\n    " +
"                        removeConfirmation: false,\r\n                            " +
"_selectors: {\r\n                                list: \'.jFiler-item-list\',\r\n     " +
"                           item: \'.jFiler-item\',\r\n                              " +
"  progressBar: \'.bar\',\r\n                                remove: \'.jFiler-item-tr" +
"ash-action\',\r\n                            }\r\n                        },\r\n       " +
"                 uploadFile: {\r\n                            url: \"/Account/SaveU" +
"ploadedFile\",\r\n                            data: {},\r\n                          " +
"  type: \'POST\',\r\n                            enctype: \'multipart/form-data\',\r\n  " +
"                          beforeSend: function () { },\r\n                        " +
"    success: function (data, el) {\r\n\r\n                                var parent" +
" = el.find(\".jFiler-jProgressBar\").parent();\r\n                                el" +
".find(\".jFiler-jProgressBar\").fadeOut(\"slow\", function () {\r\n                   " +
"                 $(\"<div class=\\\"jFiler-item-others text-success\\\"><i class=\\\"ic" +
"on-jfi-check-circle\\\"></i> Success</div>\").hide().appendTo(parent).fadeIn(\"slow\"" +
").remove();\r\n                                });\r\n                              " +
"  var image_count = $(\"#image_count\").val();\r\n                                va" +
"r imagejson = jQuery.parseJSON(JSON.stringify(data));\r\n                         " +
"       var imgdata = imagejson.image_name + \'¶\' + imagejson.image_type;\r\n       " +
"                         $(\"#image_count\").val(el[0].jfiler_id)\r\n               " +
"                 $(\'#userimage\').val(imgdata);\r\n\r\n                              " +
"  $(\'#ImagePresent\').val(\"Yes\");\r\n\r\n                                if ($.trim(i" +
"mage_count) == \'\') {\r\n                                    $(\"#image_count\").val(" +
"\'1\');\r\n                                } else {\r\n                               " +
"     image_count = parseInt(image_count) + 1;\r\n                                 " +
"   $(\"#image_count\").val(image_count);\r\n                                }\r\n\r\n\r\n " +
"                           },\r\n                            error: function (el) " +
"{\r\n                                //var parent = el.find(\".jFiler-jProgressBar\"" +
").parent();\r\n                                //el.find(\".jFiler-jProgressBar\").f" +
"adeOut(\"slow\", function(){\r\n                                //    $(\"<div class=" +
"\\\"jFiler-item-others text-error\\\"><i class=\\\"icon-jfi-minus-circle\\\"></i> Error<" +
"/div>\").hide().appendTo(parent).fadeIn(\"slow\");\r\n                               " +
" //});\r\n                            },\r\n                            statusCode: " +
"{},\r\n                            onProgress: function () { },\r\n                 " +
"       },\r\n                        dragDrop: {\r\n                            drag" +
"Enter: function () { },\r\n                            dragLeave: function () { }," +
"\r\n                            drop: function () { },\r\n                        }," +
"\r\n                        addMore: false,\r\n                        clipBoardPast" +
"e: true,\r\n                        excludeName: null,\r\n                        be" +
"foreShow: function () { $(\".jFiler-input-inner\").hide(); return true },\r\n       " +
"                 onSelect: function () { $(\".jFiler-input-inner\").hide(); },\r\n  " +
"                      afterShow: function () { $(\".jFiler-input-inner\").hide(); " +
"},\r\n                        onRemove: function (el) {\r\n                         " +
"   var image_count = $(\"#image_count\").val();\r\n                            image" +
"_count = parseInt(image_count) - 1;\r\n                            var id_div = el" +
"[0].jfiler_id;\r\n                            var hidden_image_element = \'image_hi" +
"dden_\' + id_div;\r\n                            $(\'#userimage\').val(\'\');\r\n        " +
"                    $(\"#\" + hidden_image_element).remove();\r\n                   " +
"         $(\'#input2\').click(function (e) {\r\n                                e.pr" +
"eventDefault();\r\n\r\n                            })\r\n                            $" +
"(\'#ImagePresent\').val(\"NO\");\r\n\r\n\r\n                        },\r\n                  " +
"      onEmpty: function (el) {\r\n                            console.log(el);\r\n\r\n" +
"                            // alert($(\"#drag-drop div\").hasClass(\"jFiler-items\"" +
"))\r\n                            if ($(\"#imageeror\").val() == 0) {\r\n             " +
"                   if ($(\".jFiler-items\").length == 1) { setTimeout(function () " +
"{ $(\".jFiler-input-inner\").css(\'display\', \'block\'); $(\'#input2\').unbind(\'click\')" +
"; }, 200); };\r\n                            }\r\n                        },\r\n      " +
"                  captions: {\r\n                            button: \"Choose Files" +
"\",\r\n                            feedback: \"Choose files To Upload\",\r\n           " +
"                 feedback2: \"files were chosen\",\r\n                            dr" +
"op: \"Drop file here to Upload\",\r\n                            removeConfirmation:" +
" \"Are you sure you want to remove this file?\",\r\n                            erro" +
"rs: {\r\n\r\n\r\n                                filesLimit: ajaxsetup(\'MyAccount\', \'M" +
"yAccountImageCountValidationUI\'),\r\n                                filesType: aj" +
"axsetup(\'MyAccount\', \'MyAccountImagestypeValidationUI\'),\r\n                      " +
"          filesSize: ajaxsetup(\'MyAccount\', \'MyAccountImagesizeValidationUI\'),\r\n" +
"                                filesSizeAll: ajaxsetup(\'MyAccount\', \'MyAccountI" +
"magesizeValidationUI\')\r\n                            }\r\n                        }" +
",\r\n                        files: [{\r\n                            \"type\": \"");

            
            #line 741 "..\..\Views\Account\MyAccount.cshtml"
                                Write(Model.contentype);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                            \"name\": \"");

            
            #line 742 "..\..\Views\Account\MyAccount.cshtml"
                                Write(Model.UserProfileImage);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                            \"file\": \"");

            
            #line 743 "..\..\Views\Account\MyAccount.cshtml"
                                Write(Model.ImagePath);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                        }]\r\n\r\n                    });\r\n                }\r\n\r\n  " +
"          });\r\n\r\n\r\n        </script>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            function isleap(leapyear) {\r\n                var yr = leapyear;\r\n " +
"               if ((parseInt(yr) % 4) == 0) {\r\n                    if (parseInt(" +
"yr) % 100 == 0) {\r\n                        if (parseInt(yr) % 400 != 0) {\r\n\r\n   " +
"                         return \"false\";\r\n                        }\r\n           " +
"             if (parseInt(yr) % 400 == 0) {\r\n\r\n                            retur" +
"n \"true\";\r\n                        }\r\n                    }\r\n                   " +
" if (parseInt(yr) % 100 != 0) {\r\n\r\n                        return \"true\";\r\n     " +
"               }\r\n                }\r\n                if ((parseInt(yr) % 4) != 0" +
") {\r\n\r\n                    return \"false\";\r\n                }\r\n            }\r\n  " +
"          $(\'#btnsave\').click(function () {\r\n                debugger;\r\n        " +
"        var msg = \"\";\r\n                var firstnmae = $(\"#Firstname\").val();\r\n " +
"               var emailcount = 0, pwdcount = 0;;\r\n                var lastname " +
"= $(\"#Lastname\").val();\r\n                var ConfirmPassword = $(\"#ConfirmPasswo" +
"rd\").val();\r\n\r\n                var Email = $(\"#Email\").val();\r\n                v" +
"ar NewPassword = $(\"#NewPassword\").val();\r\n                var ConfirmEmail = $(" +
"\"#ConfirmEmail\").val();\r\n                var Websiteurl = $(\"#WebsiteURL\").val()" +
";\r\n                var Password = $(\"#Password\").val();\r\n                var Con" +
"firmPassword = $(\"#ConfirmPassword\").val();\r\n\r\n                var NewPassword =" +
" $(\"#NewPassword\").val();\r\n                var month = $(\"#month\").val();\r\n\r\n   " +
"             var year = $(\"#year\").val();\r\n                var day = $(\"#day\").v" +
"al();\r\n                var ily = returnleap(year);\r\n\r\n                if (ily ==" +
" true) {\r\n\r\n                    if (day > 29 && month == 2) {\r\n                 " +
"       msg += ajaxsetup(\'MyAccount\', \'MyAccountDateValidationUI\');\r\n\r\n          " +
"              $(\'#month\').addClass(\'err-bor\');\r\n                        $(\'#year" +
"\').addClass(\'err-bor\');\r\n                        $(\'#day\').addClass(\'err-bor\');\r" +
"\n                    }\r\n\r\n                }\r\n                else {\r\n           " +
"         if (day > 28 && month == 2) {\r\n\r\n                        msg += ajaxset" +
"up(\'MyAccount\', \'MyAccountDateValidationUI\');\r\n                        $(\'#month" +
"\').addClass(\'err-bor\');\r\n                        $(\'#year\').addClass(\'err-bor\');" +
"\r\n                        $(\'#day\').addClass(\'err-bor\');\r\n                    }\r" +
"\n                }\r\n                if (day > 30 && (month == 4 || month == 6 ||" +
" month == 9 || month == 11)) {\r\n\r\n                    msg += ajaxsetup(\'MyAccoun" +
"t\', \'MyAccountDateValidationUI\');\r\n                    $(\'#month\').addClass(\'err" +
"-bor\');\r\n                    $(\'#year\').addClass(\'err-bor\');\r\n                  " +
"  $(\'#day\').addClass(\'err-bor\');\r\n\r\n                }\r\n\r\n                if (fir" +
"stnmae == \"\") {\r\n                    msg = ajaxsetup(\'MyAccount\', \'MyAccountFnam" +
"eRequiredUI\');\r\n\r\n                    $(\'#Firstname\').addClass(\'err-bor\');\r\n    " +
"            } else {\r\n\r\n                    $(\'#Firstname\').removeClass(\'err-bor" +
"\');\r\n                }\r\n\r\n\r\n\r\n\r\n                if (Email != \"\") {\r\n            " +
"        if (!validateEmail(Email)) {\r\n                        emailcount += 1;\r\n" +
"                        $(\'#Email\').addClass(\'err-bor\');\r\n\r\n\r\n                  " +
"  } else {\r\n\r\n\r\n                        $(\'#Email\').removeClass(\'err-bor\');\r\n   " +
"                 }\r\n                } else {\r\n                    $(\'#Email\').ad" +
"dClass(\'err-bor\');\r\n                    msg += ajaxsetup(\'MyAccount\', \'MyAccount" +
"EmailRequiredUI\');\r\n\r\n                }\r\n\r\n\r\n                if (ConfirmEmail !=" +
" \"\") {\r\n\r\n                    if (!validateEmail(ConfirmEmail)) {\r\n             " +
"           emailcount += 1;\r\n                        $(\'#ConfirmEmail\').addClass" +
"(\'err-bor\');\r\n\r\n\r\n                    } else {\r\n                        $(\'#Conf" +
"irmEmail\').removeClass(\'err-bor\');\r\n\r\n                    }\r\n\r\n\r\n               " +
" }\r\n                if (Password != \"\") {\r\n                    if (Password.leng" +
"th < 4) {\r\n                        pwdcount += 1;\r\n                        $(\'#P" +
"assword\').addClass(\'err-bor\');\r\n\r\n\r\n                    }\r\n                }\r\n  " +
"              if (NewPassword != \"\") {\r\n                    if (NewPassword.leng" +
"th < 4) {\r\n                        pwdcount += 1;\r\n                        $(\'#N" +
"ewPassword\').addClass(\'err-bor\');\r\n\r\n\r\n                    }\r\n\r\n\r\n              " +
"  }\r\n                if (ConfirmPassword != \"\") {\r\n                    if (Confi" +
"rmPassword.length < 4) {\r\n                        pwdcount += 1;\r\n              " +
"          $(\'#ConfirmPassword\').addClass(\'err-bor\');\r\n\r\n                    }\r\n\r" +
"\n\r\n                }\r\n\r\n                if (emailcount > 0) {\r\n                 " +
"   msg += ajaxsetup(\'MyAccount\', \'MyAccountEmailValidationUI\');\r\n\r\n             " +
"   }\r\n                if (pwdcount > 0) {\r\n                    msg = ajaxsetup(\'" +
"MyAccount\', \'MyAccountPasswordValidationUI\');\r\n\r\n                }\r\n            " +
"    if (msg == \"\") {\r\n                    $(\'#diverroacc\').css(\"display\", \"none\"" +
");\r\n                    $(\"#imageeror\").val(\'0\');\r\n                    return tr" +
"ue;\r\n                }\r\n                else {\r\n\r\n                    $(\'#erracc" +
"msg\').html(msg);\r\n                    $(\'#diverro1acc\').css(\"display\", \"none\");\r" +
"\n                    $(\'#divaccsuc\').css(\"display\", \"none\");\r\n\r\n                " +
"    $(\'#diverroacc\').css(\"display\", \"block\");\r\n                    $(\'html,body\'" +
").animate({ scrollTop: 0 });\r\n                    //$(\'#btndiverroacc\').focus();" +
"\r\n                    return false;\r\n                }\r\n            });\r\n       " +
"  \r\n          \r\n            var val1, val2;\r\n            $(\'#Zip\').change(functi" +
"on () {\r\n                var country = $(\"#Country option:selected\").text().trim" +
"();\r\n\r\n                var city = \"\";\r\n                var state = \"\";\r\n\r\n      " +
"          var pincode = $(this).val();\r\n                $.ajax({\r\n              " +
"      url: \'http://maps.googleapis.com/maps/api/geocode/json\',\r\n                " +
"    data: \'&address=\' + pincode + \'&sensor=true\',\r\n                    dataType:" +
" \'json\',\r\n                    cache: false,\r\n                    success: functi" +
"on (data) {\r\n\r\n\r\n                        if (data.status == \'OK\') {\r\n\r\n         " +
"                   for (var i = 0; i < data.results[0].address_components.length" +
"; i++) {\r\n                                var obj = data.results[0].address_comp" +
"onents[i];\r\n\r\n                                var obj2 = obj[\'types\'];\r\n\r\n      " +
"                          for (var j = 0; j < obj2.length; j++) {\r\n             " +
"                       if (obj2[j] == \'locality\' || obj2[j] == \'postal_town\' || " +
"obj2[j] == \'sublocality_level_1\' || obj2[j] == \'sublocality_level_2\' || obj2[j] " +
"== \'sublocality_level_3\' || obj2[j] == \'sublocality_level_4\' || obj2[j] == \'subl" +
"ocality_level_5\' || obj2[j] == \'ward\')\r\n                                    {\r\n " +
"                                       city = obj[\'long_name\'];\r\n\r\n\r\n           " +
"                         }\r\n                                     if (obj2[j] == " +
"\'administrative_area_level_1\') {\r\n                                        state " +
"= obj[\'long_name\'];\r\n\r\n                                    }\r\n                  " +
"                  if (obj2[j] == \'country\') {\r\n                                 " +
"       if (obj[\'long_name\'] == country) {\r\n                                     " +
"       $(\'#City\').val(city);\r\n                                            $(\'#St" +
"ate\').val(state);\r\n\r\n\r\n                                        }\r\n\r\n            " +
"                        }\r\n\r\n                                }\r\n\r\n\r\n\r\n          " +
"                  }\r\n\r\n                        }\r\n\r\n\r\n\r\n                        " +
"else {\r\n                            var msg = ajaxsetup(\'MyAccount\', \'MyAccountZ" +
"ipValidationUI\');\r\n                            $(\'#erraccmsg\').html(msg);\r\n     " +
"                       $(\'#diverro1acc\').css(\"display\", \"none\");\r\n              " +
"              $(\'#divaccsuc\').css(\"display\", \"none\");\r\n\r\n                       " +
"     $(\'#diverroacc\').css(\"display\", \"block\");\r\n                         \r\n\r\n   " +
"                         $(\'#Zip\').addClass(\'err-bor\');\r\n                       " +
"     return false;\r\n                        }\r\n                    }\r\n          " +
"      });\r\n            });\r\n\r\n            function ajaxsetup(strname, strFormTag" +
") {\r\n                var msgnew = \"\";\r\n\r\n                var request = $.ajax({\r" +
"\n                    url: \'");

            
            #line 1001 "..\..\Views\Account\MyAccount.cshtml"
                     Write(Url.Action("Index", "ValidationMessage"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                    async: false,
                    data: { strFormName: strname, strFormTag: strFormTag },
                    type: 'Post'
                });
                request.done(function (msg) {
                    msgnew += msg;
                });

                request.fail(function (jqXHR, textStatus) {
                    msgnew += ""Some Error occur!!"";
                });
                return msgnew;
            }
        </script>
        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 45799), Tuple.Create("\"", 45840)
, Tuple.Create(Tuple.Create("", 45805), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.maskedinput.min.js")
, 45805), false)
);

WriteLiteral("></script>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
