#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 1 "..\..\Views\Account\PurchasedTicket.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 2 "..\..\Views\Account\PurchasedTicket.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EventCombo;
    
    #line 3 "..\..\Views\Account\PurchasedTicket.cshtml"
    using EventCombo.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/PurchasedTicket.cshtml")]
    public partial class _Views_Account_PurchasedTicket_cshtml : System.Web.Mvc.WebViewPage<OrderViewModel>
    {
        public _Views_Account_PurchasedTicket_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Account\PurchasedTicket.cshtml"
  
  ViewBag.Title = "PurchasedTicket";
  Layout = "~/Views/Shared/_AccountLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 211), Tuple.Create("\"", 247)
, Tuple.Create(Tuple.Create("", 218), Tuple.Create<System.Object, System.Int32>(Href("~/Content/PurchasedTicket.css")
, 218), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n\r\n\r\n<div");

WriteLiteral(" id=\"purchasedTicketContainer\"");

WriteLiteral(">\r\n  <h2");

WriteLiteral(" class=\"purchasedTitleHead\"");

WriteLiteral(">PURCHASED TICKETS</h2>\r\n\r\n");

            
            #line 17 "..\..\Views\Account\PurchasedTicket.cshtml"
  
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Account\PurchasedTicket.cshtml"
    
    long upcomingCount = Model.OrderTypeInfo.Where(m => m.OrderType == OrderTypes.Upcoming).First().TotalCount;
    long pastCount = Model.OrderTypeInfo.Where(m => m.OrderType == OrderTypes.Past).First().TotalCount;
    long favoriteCount = Model.OrderTypeInfo.Where(m => m.OrderType == OrderTypes.Favorite).First().TotalCount;
  
            
            #line default
            #line hidden
WriteLiteral("\r\n  <ul");

WriteLiteral(" class=\"nav nav-tabs purchaseTicketHeaderTabs\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" href=\"#UpcomingEvents\"");

WriteLiteral(">Upcoming Events (");

            
            #line 23 "..\..\Views\Account\PurchasedTicket.cshtml"
                                                                               Write(upcomingCount);

            
            #line default
            #line hidden
WriteLiteral(")</a></li>\r\n    <li><a");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" href=\"#PastEvents\"");

WriteLiteral(">Past Events (");

            
            #line 24 "..\..\Views\Account\PurchasedTicket.cshtml"
                                                        Write(pastCount);

            
            #line default
            #line hidden
WriteLiteral(")</a></li>\r\n    <li><a");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" href=\"#FavoriteEvents\"");

WriteLiteral(">Favorite Events (");

            
            #line 25 "..\..\Views\Account\PurchasedTicket.cshtml"
                                                                Write(favoriteCount);

            
            #line default
            #line hidden
WriteLiteral(")</a></li>\r\n  </ul>\r\n\r\n  <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"UpcomingEvents\"");

WriteLiteral(" data-ttype=\"");

            
            #line 29 "..\..\Views\Account\PurchasedTicket.cshtml"
                                    Write(OrderTypes.Upcoming);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(">\r\n      <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1203), Tuple.Create("\"", 1251)
, Tuple.Create(Tuple.Create("", 1208), Tuple.Create("tableplace", 1208), true)
            
            #line 30 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 1218), Tuple.Create<System.Object, System.Int32>(OrderTypes.Upcoming.ToString()
            
            #line default
            #line hidden
, 1218), false)
);

WriteLiteral(">\r\n");

            
            #line 31 "..\..\Views\Account\PurchasedTicket.cshtml"
        
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Account\PurchasedTicket.cshtml"
           Html.RenderAction("PurchasedTicketList", new { OrderType = OrderTypes.Upcoming, SortBy = Model.State.SortBy, Page = Model.State.Page, PerPage = Model.State.PerPage }); 
            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1461), Tuple.Create("\"", 1527)
, Tuple.Create(Tuple.Create("", 1466), Tuple.Create("orderPaginationMainContainer", 1466), true)
            
            #line 33 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 1494), Tuple.Create<System.Object, System.Int32>(OrderTypes.Upcoming.ToString()
            
            #line default
            #line hidden
, 1494), false)
);

WriteLiteral(" class=\"orderListPagination\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-8 col-xs-12 orderPagination\"");

WriteLiteral(">\r\n          <ul");

WriteAttribute("id", Tuple.Create(" id=\"", 1630), Tuple.Create("\"", 1686)
, Tuple.Create(Tuple.Create("", 1635), Tuple.Create("paginationRecordUL", 1635), true)
            
            #line 35 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 1653), Tuple.Create<System.Object, System.Int32>(OrderTypes.Upcoming.ToString()
            
            #line default
            #line hidden
, 1653), false)
);

WriteLiteral(" class=\"pagination\"");

WriteLiteral("></ul>\r\n        </div>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n          $(function () {\r\n            setPagination(\"");

            
            #line 39 "..\..\Views\Account\PurchasedTicket.cshtml"
                       Write(OrderTypes.Upcoming.ToString());

            
            #line default
            #line hidden
WriteLiteral("\", \"");

            
            #line 39 "..\..\Views\Account\PurchasedTicket.cshtml"
                                                           Write(upcomingCount);

            
            #line default
            #line hidden
WriteLiteral("\", 0);\r\n          });\r\n        </script>\r\n        <div");

WriteLiteral(" class=\"col-sm-4 col-xs-12 orderViewCount\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1972), Tuple.Create("\"", 2027)
, Tuple.Create(Tuple.Create("", 1980), Tuple.Create("display:", 1980), true)
            
            #line 42 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 1988), Tuple.Create<System.Object, System.Int32>(upcomingCount>20 ? "block" : "none"
            
            #line default
            #line hidden
, 1988), false)
, Tuple.Create(Tuple.Create("", 2026), Tuple.Create(";", 2026), true)
);

WriteLiteral(">\r\n          <ul");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" id=\"recordShow20\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2099), Tuple.Create("\"", 2166)
, Tuple.Create(Tuple.Create("", 2109), Tuple.Create("SetPerPage(this,", 2109), true)
, Tuple.Create(Tuple.Create(" ", 2125), Tuple.Create("\'", 2126), true)
            
            #line 44 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 2127), Tuple.Create<System.Object, System.Int32>(OrderTypes.Upcoming.ToString()
            
            #line default
            #line hidden
, 2127), false)
, Tuple.Create(Tuple.Create("", 2160), Tuple.Create("\',", 2160), true)
, Tuple.Create(Tuple.Create(" ", 2162), Tuple.Create("20)", 2163), true)
);

WriteLiteral(" class=\"active recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">20</a></li>\r\n            <li");

WriteLiteral(" id=\"recordShow50\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2271), Tuple.Create("\"", 2338)
, Tuple.Create(Tuple.Create("", 2281), Tuple.Create("SetPerPage(this,", 2281), true)
, Tuple.Create(Tuple.Create(" ", 2297), Tuple.Create("\'", 2298), true)
            
            #line 45 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 2299), Tuple.Create<System.Object, System.Int32>(OrderTypes.Upcoming.ToString()
            
            #line default
            #line hidden
, 2299), false)
, Tuple.Create(Tuple.Create("", 2332), Tuple.Create("\',", 2332), true)
, Tuple.Create(Tuple.Create(" ", 2334), Tuple.Create("50)", 2335), true)
);

WriteLiteral(" class=\"recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">50</a></li>\r\n            <li");

WriteLiteral(" id=\"recordShow100\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2437), Tuple.Create("\"", 2505)
, Tuple.Create(Tuple.Create("", 2447), Tuple.Create("SetPerPage(this,", 2447), true)
, Tuple.Create(Tuple.Create(" ", 2463), Tuple.Create("\'", 2464), true)
            
            #line 46 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 2465), Tuple.Create<System.Object, System.Int32>(OrderTypes.Upcoming.ToString()
            
            #line default
            #line hidden
, 2465), false)
, Tuple.Create(Tuple.Create("", 2498), Tuple.Create("\',", 2498), true)
, Tuple.Create(Tuple.Create(" ", 2500), Tuple.Create("100)", 2501), true)
);

WriteLiteral(" class=\"recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">100</a></li>\r\n            <li");

WriteLiteral(" id=\"recordShow0\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2603), Tuple.Create("\"", 2669)
, Tuple.Create(Tuple.Create("", 2613), Tuple.Create("SetPerPage(this,", 2613), true)
, Tuple.Create(Tuple.Create(" ", 2629), Tuple.Create("\'", 2630), true)
            
            #line 47 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 2631), Tuple.Create<System.Object, System.Int32>(OrderTypes.Upcoming.ToString()
            
            #line default
            #line hidden
, 2631), false)
, Tuple.Create(Tuple.Create("", 2664), Tuple.Create("\',", 2664), true)
, Tuple.Create(Tuple.Create(" ", 2666), Tuple.Create("0)", 2667), true)
);

WriteLiteral(" class=\"recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">ALL</a></li>\r\n          </ul>\r\n        </div>\r\n      </div>\r\n\r\n    </div>\r\n    <" +
"div");

WriteLiteral(" id=\"PastEvents\"");

WriteLiteral(" data-ttype=\"");

            
            #line 53 "..\..\Views\Account\PurchasedTicket.cshtml"
                                Write(OrderTypes.Past);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(">\r\n      <div");

WriteAttribute("id", Tuple.Create(" id=\"", 2885), Tuple.Create("\"", 2929)
, Tuple.Create(Tuple.Create("", 2890), Tuple.Create("tableplace", 2890), true)
            
            #line 54 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 2900), Tuple.Create<System.Object, System.Int32>(OrderTypes.Past.ToString()
            
            #line default
            #line hidden
, 2900), false)
);

WriteLiteral(">\r\n");

            
            #line 55 "..\..\Views\Account\PurchasedTicket.cshtml"
        
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Account\PurchasedTicket.cshtml"
           Html.RenderAction("PurchasedTicketList", new { OrderType = OrderTypes.Past, SortBy = Model.State.SortBy, Page = Model.State.Page, PerPage = Model.State.PerPage }); 
            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteAttribute("id", Tuple.Create(" id=\"", 3135), Tuple.Create("\"", 3197)
, Tuple.Create(Tuple.Create("", 3140), Tuple.Create("orderPaginationMainContainer", 3140), true)
            
            #line 57 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 3168), Tuple.Create<System.Object, System.Int32>(OrderTypes.Past.ToString()
            
            #line default
            #line hidden
, 3168), false)
);

WriteLiteral(" class=\"orderListPagination\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-8 col-xs-12 orderPagination\"");

WriteLiteral(">\r\n          <ul");

WriteAttribute("id", Tuple.Create(" id=\"", 3300), Tuple.Create("\"", 3352)
, Tuple.Create(Tuple.Create("", 3305), Tuple.Create("paginationRecordUL", 3305), true)
            
            #line 59 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 3323), Tuple.Create<System.Object, System.Int32>(OrderTypes.Past.ToString()
            
            #line default
            #line hidden
, 3323), false)
);

WriteLiteral(" class=\"pagination\"");

WriteLiteral("></ul>\r\n        </div>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n          $(function () {\r\n            setPagination(\"");

            
            #line 63 "..\..\Views\Account\PurchasedTicket.cshtml"
                       Write(OrderTypes.Past.ToString());

            
            #line default
            #line hidden
WriteLiteral("\", \"");

            
            #line 63 "..\..\Views\Account\PurchasedTicket.cshtml"
                                                       Write(pastCount);

            
            #line default
            #line hidden
WriteLiteral("\", 0);\r\n          });\r\n        </script>\r\n        <div");

WriteLiteral(" class=\"col-sm-4 col-xs-12 orderViewCount\"");

WriteAttribute("style", Tuple.Create(" style=\"", 3630), Tuple.Create("\"", 3681)
, Tuple.Create(Tuple.Create("", 3638), Tuple.Create("display:", 3638), true)
            
            #line 66 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 3646), Tuple.Create<System.Object, System.Int32>(pastCount>20 ? "block" : "none"
            
            #line default
            #line hidden
, 3646), false)
, Tuple.Create(Tuple.Create("", 3680), Tuple.Create(";", 3680), true)
);

WriteLiteral(">\r\n          <ul");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" id=\"recordShow20\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 3753), Tuple.Create("\"", 3816)
, Tuple.Create(Tuple.Create("", 3763), Tuple.Create("SetPerPage(this,", 3763), true)
, Tuple.Create(Tuple.Create(" ", 3779), Tuple.Create("\'", 3780), true)
            
            #line 68 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 3781), Tuple.Create<System.Object, System.Int32>(OrderTypes.Past.ToString()
            
            #line default
            #line hidden
, 3781), false)
, Tuple.Create(Tuple.Create("", 3810), Tuple.Create("\',", 3810), true)
, Tuple.Create(Tuple.Create(" ", 3812), Tuple.Create("20)", 3813), true)
);

WriteLiteral(" class=\"active recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">20</a></li>\r\n            <li");

WriteLiteral(" id=\"recordShow50\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 3921), Tuple.Create("\"", 3984)
, Tuple.Create(Tuple.Create("", 3931), Tuple.Create("SetPerPage(this,", 3931), true)
, Tuple.Create(Tuple.Create(" ", 3947), Tuple.Create("\'", 3948), true)
            
            #line 69 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 3949), Tuple.Create<System.Object, System.Int32>(OrderTypes.Past.ToString()
            
            #line default
            #line hidden
, 3949), false)
, Tuple.Create(Tuple.Create("", 3978), Tuple.Create("\',", 3978), true)
, Tuple.Create(Tuple.Create(" ", 3980), Tuple.Create("50)", 3981), true)
);

WriteLiteral(" class=\"recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">50</a></li>\r\n            <li");

WriteLiteral(" id=\"recordShow100\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 4083), Tuple.Create("\"", 4147)
, Tuple.Create(Tuple.Create("", 4093), Tuple.Create("SetPerPage(this,", 4093), true)
, Tuple.Create(Tuple.Create(" ", 4109), Tuple.Create("\'", 4110), true)
            
            #line 70 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 4111), Tuple.Create<System.Object, System.Int32>(OrderTypes.Past.ToString()
            
            #line default
            #line hidden
, 4111), false)
, Tuple.Create(Tuple.Create("", 4140), Tuple.Create("\',", 4140), true)
, Tuple.Create(Tuple.Create(" ", 4142), Tuple.Create("100)", 4143), true)
);

WriteLiteral(" class=\"recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">100</a></li>\r\n            <li");

WriteLiteral(" id=\"recordShow0\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 4245), Tuple.Create("\"", 4307)
, Tuple.Create(Tuple.Create("", 4255), Tuple.Create("SetPerPage(this,", 4255), true)
, Tuple.Create(Tuple.Create(" ", 4271), Tuple.Create("\'", 4272), true)
            
            #line 71 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 4273), Tuple.Create<System.Object, System.Int32>(OrderTypes.Past.ToString()
            
            #line default
            #line hidden
, 4273), false)
, Tuple.Create(Tuple.Create("", 4302), Tuple.Create("\',", 4302), true)
, Tuple.Create(Tuple.Create(" ", 4304), Tuple.Create("0)", 4305), true)
);

WriteLiteral(" class=\"recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">ALL</a></li>\r\n          </ul>\r\n        </div>\r\n      </div>\r\n    </div>\r\n\r\n    <" +
"div");

WriteLiteral(" id=\"FavoriteEvents\"");

WriteLiteral(" data-ttype=\"");

            
            #line 77 "..\..\Views\Account\PurchasedTicket.cshtml"
                                    Write(OrderTypes.Favorite);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(">\r\n      <div");

WriteAttribute("id", Tuple.Create(" id=\"", 4531), Tuple.Create("\"", 4579)
, Tuple.Create(Tuple.Create("", 4536), Tuple.Create("tableplace", 4536), true)
            
            #line 78 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 4546), Tuple.Create<System.Object, System.Int32>(OrderTypes.Favorite.ToString()
            
            #line default
            #line hidden
, 4546), false)
);

WriteLiteral(">\r\n");

            
            #line 79 "..\..\Views\Account\PurchasedTicket.cshtml"
        
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Account\PurchasedTicket.cshtml"
           Html.RenderAction("PurchasedTicketList", new { OrderType = OrderTypes.Favorite, SortBy = Model.State.SortBy, Page = Model.State.Page, PerPage = Model.State.PerPage }); 
            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteAttribute("id", Tuple.Create(" id=\"", 4789), Tuple.Create("\"", 4855)
, Tuple.Create(Tuple.Create("", 4794), Tuple.Create("orderPaginationMainContainer", 4794), true)
            
            #line 81 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 4822), Tuple.Create<System.Object, System.Int32>(OrderTypes.Favorite.ToString()
            
            #line default
            #line hidden
, 4822), false)
);

WriteLiteral(" class=\"orderListPagination\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-8 col-xs-12 orderPagination\"");

WriteLiteral(">\r\n          <ul");

WriteAttribute("id", Tuple.Create(" id=\"", 4958), Tuple.Create("\"", 5014)
, Tuple.Create(Tuple.Create("", 4963), Tuple.Create("paginationRecordUL", 4963), true)
            
            #line 83 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 4981), Tuple.Create<System.Object, System.Int32>(OrderTypes.Favorite.ToString()
            
            #line default
            #line hidden
, 4981), false)
);

WriteLiteral(" class=\"pagination\"");

WriteLiteral("></ul>\r\n        </div>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n          $(function () {\r\n            setPagination(\"");

            
            #line 87 "..\..\Views\Account\PurchasedTicket.cshtml"
                       Write(OrderTypes.Favorite.ToString());

            
            #line default
            #line hidden
WriteLiteral("\", \"");

            
            #line 87 "..\..\Views\Account\PurchasedTicket.cshtml"
                                                           Write(favoriteCount);

            
            #line default
            #line hidden
WriteLiteral("\", 0);\r\n          });\r\n        </script>\r\n        <div");

WriteLiteral(" class=\"col-sm-4 col-xs-12 orderViewCount\"");

WriteAttribute("style", Tuple.Create(" style=\"", 5300), Tuple.Create("\"", 5355)
, Tuple.Create(Tuple.Create("", 5308), Tuple.Create("display:", 5308), true)
            
            #line 90 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 5316), Tuple.Create<System.Object, System.Int32>(favoriteCount>20 ? "block" : "none"
            
            #line default
            #line hidden
, 5316), false)
, Tuple.Create(Tuple.Create("", 5354), Tuple.Create(";", 5354), true)
);

WriteLiteral(">\r\n          <ul");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" id=\"recordShow20\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 5427), Tuple.Create("\"", 5494)
, Tuple.Create(Tuple.Create("", 5437), Tuple.Create("SetPerPage(this,", 5437), true)
, Tuple.Create(Tuple.Create(" ", 5453), Tuple.Create("\'", 5454), true)
            
            #line 92 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 5455), Tuple.Create<System.Object, System.Int32>(OrderTypes.Favorite.ToString()
            
            #line default
            #line hidden
, 5455), false)
, Tuple.Create(Tuple.Create("", 5488), Tuple.Create("\',", 5488), true)
, Tuple.Create(Tuple.Create(" ", 5490), Tuple.Create("20)", 5491), true)
);

WriteLiteral(" class=\"active recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">20</a></li>\r\n            <li");

WriteLiteral(" id=\"recordShow50\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 5599), Tuple.Create("\"", 5666)
, Tuple.Create(Tuple.Create("", 5609), Tuple.Create("SetPerPage(this,", 5609), true)
, Tuple.Create(Tuple.Create(" ", 5625), Tuple.Create("\'", 5626), true)
            
            #line 93 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 5627), Tuple.Create<System.Object, System.Int32>(OrderTypes.Favorite.ToString()
            
            #line default
            #line hidden
, 5627), false)
, Tuple.Create(Tuple.Create("", 5660), Tuple.Create("\',", 5660), true)
, Tuple.Create(Tuple.Create(" ", 5662), Tuple.Create("50)", 5663), true)
);

WriteLiteral(" class=\"recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">50</a></li>\r\n            <li");

WriteLiteral(" id=\"recordShow100\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 5765), Tuple.Create("\"", 5833)
, Tuple.Create(Tuple.Create("", 5775), Tuple.Create("SetPerPage(this,", 5775), true)
, Tuple.Create(Tuple.Create(" ", 5791), Tuple.Create("\'", 5792), true)
            
            #line 94 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 5793), Tuple.Create<System.Object, System.Int32>(OrderTypes.Favorite.ToString()
            
            #line default
            #line hidden
, 5793), false)
, Tuple.Create(Tuple.Create("", 5826), Tuple.Create("\',", 5826), true)
, Tuple.Create(Tuple.Create(" ", 5828), Tuple.Create("100)", 5829), true)
);

WriteLiteral(" class=\"recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">100</a></li>\r\n            <li");

WriteLiteral(" id=\"recordShow0\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 5931), Tuple.Create("\"", 5997)
, Tuple.Create(Tuple.Create("", 5941), Tuple.Create("SetPerPage(this,", 5941), true)
, Tuple.Create(Tuple.Create(" ", 5957), Tuple.Create("\'", 5958), true)
            
            #line 95 "..\..\Views\Account\PurchasedTicket.cshtml"
, Tuple.Create(Tuple.Create("", 5959), Tuple.Create<System.Object, System.Int32>(OrderTypes.Favorite.ToString()
            
            #line default
            #line hidden
, 5959), false)
, Tuple.Create(Tuple.Create("", 5992), Tuple.Create("\',", 5992), true)
, Tuple.Create(Tuple.Create(" ", 5994), Tuple.Create("0)", 5995), true)
);

WriteLiteral(" class=\"recordLiItem\"");

WriteLiteral("><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">ALL</a></li>\r\n          </ul>\r\n        </div>\r\n      </div>\r\n    </div>\r\n  </div" +
">\r\n  <div");

WriteLiteral(" id=\"spinner\"");

WriteLiteral(" class=\"spinner\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n    <img");

WriteLiteral(" id=\"img-spinner\"");

WriteAttribute("src", Tuple.Create(" src=\"", 6217), Tuple.Create("\"", 6247)
, Tuple.Create(Tuple.Create("", 6223), Tuple.Create<System.Object, System.Int32>(Href("~/Images/ajaxloader1.gif")
, 6223), false)
);

WriteLiteral(" alt=\"Loading\"");

WriteLiteral(" />\r\n  </div>\r\n</div>\r\n\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n  var cStates = [{\r\n    Page: \"");

            
            #line 110 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(Model.State.Page);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    PerPage: \"");

            
            #line 111 "..\..\Views\Account\PurchasedTicket.cshtml"
          Write(Model.State.PerPage);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    SortBy: \"");

            
            #line 112 "..\..\Views\Account\PurchasedTicket.cshtml"
         Write(Model.State.SortBy);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    SortDesc: \"");

            
            #line 113 "..\..\Views\Account\PurchasedTicket.cshtml"
           Write(Model.State.SortDesc);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    Total: \"");

            
            #line 114 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(upcomingCount);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    OrderType: \"");

            
            #line 115 "..\..\Views\Account\PurchasedTicket.cshtml"
           Write(OrderTypes.Upcoming);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n  }, {\r\n    Page: \"");

            
            #line 117 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(Model.State.Page);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    PerPage: \"");

            
            #line 118 "..\..\Views\Account\PurchasedTicket.cshtml"
          Write(Model.State.PerPage);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    SortBy: \"");

            
            #line 119 "..\..\Views\Account\PurchasedTicket.cshtml"
         Write(Model.State.SortBy);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    SortDesc: \"");

            
            #line 120 "..\..\Views\Account\PurchasedTicket.cshtml"
           Write(Model.State.SortDesc);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    Total: \"");

            
            #line 121 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(pastCount);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    OrderType: \"");

            
            #line 122 "..\..\Views\Account\PurchasedTicket.cshtml"
           Write(OrderTypes.Past);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n  }, {\r\n    Page: \"");

            
            #line 124 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(Model.State.Page);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    PerPage: \"");

            
            #line 125 "..\..\Views\Account\PurchasedTicket.cshtml"
          Write(Model.State.PerPage);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    SortBy: \"");

            
            #line 126 "..\..\Views\Account\PurchasedTicket.cshtml"
         Write(Model.State.SortBy);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    SortDesc: \"");

            
            #line 127 "..\..\Views\Account\PurchasedTicket.cshtml"
           Write(Model.State.SortDesc);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    Total: \"");

            
            #line 128 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(favoriteCount);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n    OrderType: \"");

            
            #line 129 "..\..\Views\Account\PurchasedTicket.cshtml"
           Write(OrderTypes.Favorite);

            
            #line default
            #line hidden
WriteLiteral(@"""
  }];

  $(function () {
    $(document).on({
      ajaxStart: function () { $(""#spinner"").show(); },
      ajaxStop: function () { $(""#spinner"").hide(); }
    });
  });

  function expandEditMenu(obj, name, id) {
    var detail = $('#' + name + id);
    if ($(detail).data('popped') == '0') {
      $.ajax({
        type: 'GET',
        url: '");

            
            #line 144 "..\..\Views\Account\PurchasedTicket.cshtml"
         Write(Url.Action("PurchasedTicketDetail", "Account"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        data: { OrderId: id },\r\n        datatype: \'html\',\r\n        success: f" +
"unction (data) {\r\n          $(obj).parent().parent().css(\'background-color\', \'#f" +
"1f1f1\');\r\n          $(detail).html(data);\r\n          $(detail).css(\'background-c" +
"olor\', \'#f1f1f1\');\r\n          $(detail).css(\'border-top\', \'none\');\r\n          $(" +
"detail).data(\'popped\', \'1\');\r\n          $(detail).slideDown();\r\n        }\r\n     " +
" });\r\n    }\r\n    else {\r\n      $(detail).html(\'\');\r\n      $(obj).parent().parent" +
"().css(\'background-color\', \'#ffffff\');\r\n      $(detail).data(\'popped\', \'0\');\r\n  " +
"    $(detail).slideUp();\r\n    }\r\n\r\n  }\r\n\r\n  function setCheckBoxChecked(obj) {\r\n" +
"    if ($(obj).hasClass(\'basicInfoUnCheckBox\')) {\r\n      $(obj).addClass(\'basicI" +
"nfoCheckBox\');\r\n      $(obj).removeClass(\'basicInfoUnCheckBox\');\r\n    }\r\n    els" +
"e {\r\n      $(obj).removeClass(\'basicInfoCheckBox\');\r\n      $(obj).addClass(\'basi" +
"cInfoUnCheckBox\');\r\n    }\r\n  }\r\n\r\n\r\n  function sortBy(obj, sort) {\r\n    var cur " +
"= findState(obj);\r\n    if ((cStates[cur].SortDesc == \'False\') && (cStates[cur].S" +
"ortBy == sort))\r\n      cStates[cur].SortDesc = \'True\';\r\n    else\r\n      cStates[" +
"cur].SortDesc = \'False\';\r\n    cStates[cur].SortBy = sort;\r\n    getTicketList($(o" +
"bj).closest(\'div[id^=\"tableplace\"\').attr(\'id\'), cStates[cur]);\r\n  }\r\n\r\n  functio" +
"n findState(obj) {\r\n    var tabpane = $(obj).closest(\'.tab-pane\');\r\n    var tTyp" +
"e = $(tabpane).data(\'ttype\');\r\n\r\n    var cur = 0;\r\n    for (var i = 0; i < cStat" +
"es.length; i++)\r\n      if (cStates[i].OrderType == tType) {\r\n        cur = i;\r\n " +
"       break;\r\n      }\r\n    return cur;\r\n  }\r\n\r\n  function getCurrentState(state" +
") {\r\n    var cState = null;\r\n    cStates.forEach(function (x) {\r\n      if (x.Ord" +
"erType == state)\r\n        cState = x;\r\n    });\r\n    return cState;\r\n  }\r\n\r\n  fun" +
"ction getTicketList(id, query) {\r\n    $.ajax({\r\n      type: \"GET\",\r\n      url: \"" +
"");

            
            #line 213 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(Url.Action("PurchasedTicketList", "Account"));

            
            #line default
            #line hidden
WriteLiteral(@""",
      data: query,
      datatype: ""html"",
      success: function (data) {
        $('#' + id).html(data);
      }
    });
  }

  function saveChangeFunc(id) {
    var query = {
      OrderId: id,
      SendEmail: $('#sendConfirmationEmail' + id).hasClass('basicInfoCheckBox'),
      Attendees: []
    };
    $('input[id^=""UETableTDSUbDivName' + id + '_""]').each(function () {
      query.Attendees.push({
        TicketbearerId: $(this).data('bearerid'),
        Name: $(this).val(),
        Email: $('#UETableTDSUbDivEmail' + id + '_' + $(this).data('bearerid')).val()
      })
    });
    $.ajax({
      type: ""POST"",
      url: """);

            
            #line 237 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(Url.Action("SavePurchasedTicketDetail", "Account"));

            
            #line default
            #line hidden
WriteLiteral(@""",
      data: query,
      datatype: ""html"",
      success: function (data) {
        $('#ajaxanswer' + id).html(data);
      }
    });
  }

  function SendCancelOrder(obj, oId) {
    if ($(obj).closest('table').parent().parent().data('orderstate') != 1) {
      $('#ajaxanswer' + oId).html(""Order already cancelled."");
      return;
    }
    $.ajax({
      type: ""POST"",
      url: """);

            
            #line 253 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(Url.Action("CancelOrder", "Account"));

            
            #line default
            #line hidden
WriteLiteral(@""",
      data: { OrderId: oId },
      datatype: ""html"",
      success: function (data) {
        if (data > 0) {
          var caption = $(obj).closest('table').parent().parent().prev('tr').find('td').last();
          $(caption).html($(caption).html() + ' - Cancelled');
          $('#ajaxanswer' + oId).html(""Order cancelled."");
        }
        else
          $('#ajaxanswer' + oId).html(""Order wasn't cancelled."");
      }
    });
  }

  function SendOrganizerMessage(oId) {
    var query = {
      OrderId: oId,
      Name: $('#nameContact' + oId).val(),
      Email: $('#emailContact' + oId).val(),
      Message: $('#messageContact' + oId).val()
    }
    $.ajax({
      type: ""POST"",
      url: """);

            
            #line 277 "..\..\Views\Account\PurchasedTicket.cshtml"
       Write(Url.Action("SaveMessage", "Account"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n      data: query,\r\n      datatype: \"html\",\r\n      success: function (data) {" +
"\r\n        if (data > 0) {\r\n          $(\'#ajaxanswer\' + oId).html(\"Message saved." +
"\");\r\n        }\r\n        else\r\n          $(\'#ajaxanswer\' + oId).html(\"Message not" +
" saved.\");\r\n      }\r\n    });\r\n  }\r\n\r\n  function setPagination(page, total, cur) " +
"{\r\n    $(\'#paginationRecordUL\' + page).empty();\r\n    var cState = getCurrentStat" +
"e(page);\r\n    if (cState != null) {\r\n      cState.Total = total;\r\n      if ((par" +
"seInt(total, 10) > parseInt(cState.PerPage, 10)) && (parseInt(cState.PerPage, 10" +
") > 0)) {\r\n        var totalPages = Math.ceil(total / cState.PerPage);\r\n        " +
"cur = cur >= totalPages ? totalPages - 1 : cur;\r\n        var startVal = ((cur + " +
"2) >= totalPages) ? (totalPages - 5) : (cur - 2);\r\n        startVal = (startVal " +
">= 0) ? startVal : 0;\r\n        var endVal = ((startVal + 4) >= totalPages) ? tot" +
"alPages - 1 : (startVal + 4);\r\n        $(\"#paginationRecordUL\" + page).append(\'<" +
"li id=\"paginationFirst\" onclick=\"setPagination(\\\'\' + page + \'\\\', \' + total + \', " +
"0)\" class=\"paginationLiItem\" ><a href=\"javascript:void(0)\">First</a></li>\' +\r\n  " +
"        \'<li id=\"paginationPrevious\" onclick=\"setPagination(\\\'\' + page + \'\\\', \' " +
"+ total + \', \' + (cur > 0 ? cur - 1 : cur) + \')\" class=\"paginationLiItem\"><a hre" +
"f=\"javascript:void(0)\">Previous</a></li>\');\r\n        if (startVal > 0)\r\n        " +
"  $(\"#paginationRecordUL\" + page).append(\'<li id=\"paginationPrevSome\" onclick=\"s" +
"etPagination(\\\'\' + page + \'\\\', \' + total + \', \' + (startVal - 1) + \')\" class=\"pa" +
"ginationLiItem\" ><a href=\"javascript:void(0)\">...</a></li>\');\r\n        for (i = " +
"startVal; i <= endVal; i++) {\r\n          $(\"#paginationRecordUL\" + page).append(" +
"\'<li id=\"pagination\"\' + i + \' onclick=\"setPagination(\\\'\' + page + \'\\\', \' + total" +
" + \', \' + i + \')\" class=\"paginationLiItem\' + (i == cur ? \' active\' : \'\') + \'\" ><" +
"a href=\"javascript:void(0)\">\' + (i + 1) + \'</a></li>\');\r\n        }\r\n        if (" +
"endVal < totalPages - 1)\r\n          $(\"#paginationRecordUL\" + page).append(\'<li " +
"id=\"paginationNextSome\" onclick=\"setPagination(\\\'\' + page + \'\\\', \' + total + \', " +
"\' + (endVal + 1) + \')\" class=\"paginationLiItem\" ><a href=\"javascript:void(0)\">.." +
".</a></li>\');\r\n        $(\"#paginationRecordUL\" + page).append(\'<li id=\"paginatio" +
"nNext\" onclick=\"setPagination(\\\'\' + page + \'\\\', \' + total + \', \' + (cur < (total" +
"Pages - 1) ? cur + 1 : cur) + \')\" class=\"paginationLiItem\" ><a href=\"javascript:" +
"void(0)\">Next</a></li>\' +\r\n          \'<li id=\"paginationLast\" onclick=\"setPagina" +
"tion(\\\'\' + page + \'\\\', \' + total + \', \' + (totalPages - 1) + \')\" class=\"paginati" +
"onLiItem\"><a href=\"javascript:void(0)\">Last</a></li>\');\r\n        cState.Page = c" +
"ur;\r\n      }\r\n      else\r\n        cState.Page = 0;\r\n      getTicketList(\"tablepl" +
"ace\" + page, cState);\r\n    }\r\n  }\r\n\r\n  function SetPerPage(obj, page, num) {\r\n  " +
"  $(obj).siblings(\'li\').removeClass(\'active\');\r\n    $(obj).addClass(\'active\');\r\n" +
"    var cState = getCurrentState(page);\r\n    if (cState != null) {\r\n      var cu" +
"rRec = cState.Page * cState.PerPage;\r\n      cState.PerPage = num;\r\n      setPagi" +
"nation(page, cState.Total, Math.floor(curRec / num));\r\n    }\r\n  }\r\n</script>\r\n<s" +
"cript");

WriteAttribute("src", Tuple.Create(" src=\"", 14356), Tuple.Create("\"", 14386)
, Tuple.Create(Tuple.Create("", 14362), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/socialshare.js")
, 14362), false)
);

WriteLiteral("></script>\r\n");

        }
    }
}
#pragma warning restore 1591
