//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventVenue
    {
        public long EventVenueID { get; set; }
        public long EventID { get; set; }
        public long AddressId { get; set; }
        public Nullable<System.DateTime> EventStartDate { get; set; }
        public Nullable<System.DateTime> EventEndDate { get; set; }
        public Nullable<System.TimeSpan> EventStartTime { get; set; }
        public Nullable<System.TimeSpan> EventEndTime { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual EventVenue EventVenue1 { get; set; }
        public virtual EventVenue EventVenue2 { get; set; }
    }
}
