//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    
    public partial class EventCreation
    {
        public string EventTitle { get; set; }
        public string EventType { get; set; }
        public string EventCategory { get; set; }
        public string EventSubCategory { get; set; }
        public string EventTiming { get; set; }
        public long EventID { get; set; }
        public int Feature { get; set; }
    }
}
