BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Event ADD
	ECBackgroundId bigint NULL,
	BackgroundColor varchar(10) NULL
GO
CREATE NONCLUSTERED INDEX FK_ECBackgroundId ON dbo.Event
	(
	ECBackgroundId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.Event SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
GO

BEGIN TRANSACTION
GO
ALTER TABLE dbo.Organizer_Master ADD
	ECImageId bigint NULL
GO
CREATE NONCLUSTERED INDEX FK_ECImageId ON dbo.Organizer_Master
	(
	ECImageId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.Organizer_Master SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
GO

SET IDENTITY_INSERT TicketType ON
INSERT INTO TicketType (TicketTypeID, TicketType)
VALUES (1, 'Free')
INSERT INTO TicketType (TicketTypeID, TicketType)
VALUES (2, 'Paid')
INSERT INTO TicketType (TicketTypeID, TicketType)
VALUES (3, 'Donation')
SET IDENTITY_INSERT TicketType OFF

GO
